### ISSUE TITLE
False negative on Circular Dependency

### ISSUE THREAD

**Issue by ysansone** [mebigfatguy/fb-contrib#101]
(FB.W.CORRECTNESS) Cd circular dependency
    Class com.monits.agilefant.A has a circular dependency with other classes

We are not getting an error report when a class A uses B.class and at the same time said class B extends from the first one. For example when we create an intent using B.class as a parameter when said class B extends from A, we do have a circular dependency but we are not getting any report of it:

```
public class A extends Activity {
    @Override
    protected void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        final Intent intent = new Intent(this, B.class);
        startActivity(intent);
    }
}
```

But, in the case where B uses A and A uses a method/instance of class B we do get the report. For example when we create an intent using a method from B called getIntent when that class B extends from A, we also have a circular dependency and we get the error report:

```
public class A extends Activity {
    @Override
    protected void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        startActivity(B.getIntent(this));
    }
}
public class B extends A {
    /**
     * This factory method returns an intent of this class
     *
     * @param context A Context of class A
     * @return An intent
     */
    public static Intent getIntent(final Context context) {
        return new Intent(context, B.class);
    }
}
```
In resume, we are not getting an error over a circular dependency issue when we use .class and we should.

**Comment by mebigfatguy** [comment]
Thanks for the report. to be clear you are saying it's a false negative, right?

**Comment by ysansone** [comment]
Yes, it is a false negative

**Comment by mebigfatguy** [comment]
Thanks again for the report, hopefully this will now be reported for you in the next release, or pull and build from the master branch to check.
