### ISSUE TITLE
Bogus Exception false positives for AspectJ woven code

### ISSUE THREAD

**Issue by krzyk** [mebigfatguy/fb-contrib#102]
When I use AspectJ to weave my classes bogus exception reports errors where there are none.

I know what AspectJ generates code that has no equivalents in java code, but maybe it is possible to ignore those additions?

**Comment by mebigfatguy** [comment]
Are the reports done in methods that don't exist in src form? Ie is the whole method synthetic? If so I can fix that. If however the AOP is merely embellishing an existing method, there's really not much I can do.

**Comment by krzyk** [comment]
I'm not sure if I understand, let me give an example:
```
public DecoratedStream extends InputStream {

private final InputStream stream;

    public DecoratedStream(InputStream stream) {
        this.stream = stream;
    }
 
    @RetryOnFailure
    public final int read() throws IOException {
        return this.stream.read();
    }
}
```

Where `@RetryOnFailure` does retry three times of the method and if all of them fail it throws the exception that was caught (see https://github.com/jcabi/jcabi-aspects/blob/master/src/main/java/com/jcabi/aspects/aj/Repeater.java for the source).
Or similar annotation `@Loggable` (https://github.com/jcabi/jcabi-aspects/blob/master/src/main/java/com/jcabi/aspects/aj/MethodLogger.java) that just logs "this method was executed with following commands".

**Comment by mebigfatguy** [comment]
it would be good if you could attach the .class file of the effected class to this issue.

**Comment by krzyk** [comment]
Here it is
[CheckstyleValidator.zip](https://github.com/mebigfatguy/fb-contrib/files/134576/CheckstyleValidator.zip)

**Comment by mebigfatguy** [comment]
ok, thank you. Now. can you tell me what findbugs is reporting a BED on? what is the method name that is flagged in com.qulice.checkstyle.CheckstyleValidator ?

**Comment by krzyk** [comment]
Here's how the method looks (it is in a class that is `final`):
```
    @Override
    @Loggable
    public void validate(final Environment env) throws ValidationException {
```

**Comment by krzyk** [comment]
@mebigfatguy Do you think it is doable with weaved classes?

**Comment by mebigfatguy** [comment]
The class you posted (thanks) didn't show an example of an invalid BED being detected, so was unable to look at it further.

**Comment by krzyk** [comment]
@mebigfatguy exactly that's the problem, if I remove the annotation BED works, if I add annotation (and waving) BED stops working.

**Comment by mebigfatguy** [comment]
unless i can get a .class file showing the problem, i won't be able to fix it.

**Comment by krzyk** [comment]
The one from https://github.com/mebigfatguy/fb-contrib/issues/102#issuecomment-185256948 is not enough?

**Comment by mebigfatguy** [comment]
i ran findbugs/fb-contrib against CheckStyleValidator.class as provided in the above zip(thanks) as well as running it on the entire jcabi-aspects project, and did not produce a BED detection on anything. So not sure how to proceed.
