### ISSUE TITLE
Incorrect guard clause in CopiedOverriddenMethod.visitCode?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#103]
``CopiedOverriddenMethod`` uses a guard clause in ``visitCode`` that would allow it to examine public/protected abstract methods. Is this expected behavior?

**Comment by ThrawnCA** [comment]
The current clause is

        if ((!m.isPublic() && !m.isProtected() && !m.isAbstract()) || m.isSynthetic()) {
            return;
        }

I think it should be

        if (!m.isPublic() && !m.isProtected() || m.isAbstract() || m.isSynthetic()) {
            return;
        }

**Comment by mebigfatguy** [comment]
Yes, definitely right. thanks ... applied
