### ISSUE TITLE
Redundant condition in UnboundMethodTemplateParameter?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#104]
``UnboundMethodTemplateParameter.visitMethod`` has a condition that checks the contents of a string twice, but the first check is a broader match than the second - so the second must always fail if the first did.

    if (!ts.signature.contains('T' + templateParm.templateType + ';') && !ts.signature.contains("[T" + templateParm.templateType + ';')) {

Unless I'm missing something, the second condition can simply be dropped.

**Comment by mebigfatguy** [comment]
yes, good catch. committed.
