### ISSUE TITLE
InefficientStringBuffering always passes null to private methods?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#106]
``InefficientStringBuffering.sawOpcode`` initialises a local variable ``userValue`` to null, then on some branches, it passes it to the private ``sawInvokeSpecial`` or ``sawInvokeVirtual`` methods without ever setting it to anything else.

These are the only calls to the two private methods, so any code in them that handles non-null parameters will never be executed.

**Comment by ThrawnCA** [comment]
``SillynessPotPourri.sawOpcode`` seems to have similar behavior.

**Comment by mebigfatguy** [comment]
thanks
