### ISSUE TITLE
OPM low-priority false positives on MethodInfo

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#107]
``OPM_OVERLY_PERMISSIVE_METHOD`` is reporting what appear to be false positives on:

``MethodInfo.wasCalledProtectedly``
``MethodInfo.wasCalledPackagely``

both of which are called from, ironically, the OPM detector itself, in a different package.

**Comment by mebigfatguy** [comment]
good catch. thanks
