### ISSUE TITLE
OpcodeUtils declares public methods that are only used privately?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#108]
``OpcodeUtils`` declares a number of methods (eg ``isDLoad``) that are only used by itself. This trips the OPM detector with low priority.

Are these methods expected to be used externally in future? Should static methods of utility classes (ie classes with only a private constructor) be excluded from OPM?

**Comment by mebigfatguy** [comment]
thanks, i really should be using those to simplify.
