### ISSUE TITLE
UTAO_TESTNG_ASSERTION_ODDITIES_USE_ASSERT_NULL false positive on Mockito-powered method calls

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#109]
We use Mockito to set up unit tests, eg:

    when(mockObject.methodCall()).thenReturn(someObject)

but UTAO_TESTNG_ASSERTION_ODDITIES_USE_ASSERT_NULL does not recognise this, and thinks that the result of ``methodCall()`` will be null, which causes false positives.

Sample code:

    public interface Repository {
        Object findByUuid(String uuid);
    }

Class that uses repository:

    import com.opensymphony.xwork2.Action;

    public class StrutsAction implements Action {

        private final Repository repository;
        private Object domainObject;
        private String uuid;

        public StrutsAction(Repository repository) {
            this.repository = repository;
        }

        public String execute() {
            domainObject = repository.findByUuid(uuid);
            return SUCCESS;
        }

        public void setUuid(String uuid) {
            this.uuid = uuid;
        }

        public Object getDomainObject() {
            return domainObject;
        }
    }

Test:

    import com.opensymphony.xwork2.Action;

    import org.mockito.Mock;
    import org.mockito.MockitoAnnotations;
    import org.testng.annotations.Test;

    import static org.mockito.Mockito.when;
    import static org.testng.Assert.assertEquals;

    public class MockitoBasedTest {
        private static final String UUID = "some uuid";

        @Mock private Repository repository;
        @Mock private Object domainObject;

        @Test
        public void shouldReturnDomainObjectForUuid() throws Exception {
            MockitoAnnotations.initMocks(this);

            StrutsAction action = new StrutsAction(repository);
            when(repository.findByUuid(UUID)).thenReturn(domainObject);

            action.setUuid(UUID);
            assertEquals(action.execute(), Action.SUCCESS);
            // this assertion triggers the detector
            assertEquals(action.getDomainObject(), domainObject);
        }

    }

**Comment by mebigfatguy** [comment]
for some reason the sample i've added in an attempt to match your experience doesn't report the FP. I'm assuming i just need to honor the @Mock and assume that isn't null, but i'd like to be able to reproduce.

**Comment by ThrawnCA** [comment]
Were you able to trigger the false positive using my original sample? I notice that the committed sample has been significantly refactored.

The FP appears to have been introduced with fb-contrib 6.4.0.

**Comment by ThrawnCA** [comment]
Update: I can reproduce the issue with your sample. Hmm...

**Comment by mebigfatguy** [comment]
Yeah i'm not able to reproduce with the sample.

**Comment by mebigfatguy** [comment]
I attempted a fix by not reporting this issue when using fields that have runtime annotations attached to them. I have no idea whether this fixes your issue or not, but it would seem to make sense to me.

**Comment by jsotuyod** [comment]
Doing so would ignore fields with annotations such as @SuppressFbWarnings.
I'm not sure that is such a great fix...

Maybe looking deeper into why the results vary from one machine to the
other would  provide some insight.
On Apr 1, 2016 10:14 AM, "Dave Brosius" <notifications@github.com> wrote:

I attempted a fix by not reporting this issue when using fields that have
runtime annotations attached to them. I have no idea whether this fixes
your issue or not, but it would seem to make sense to me.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/mebigfatguy/fb-contrib/issues/109#issuecomment-204197587>

**Comment by mebigfatguy** [comment]
i can be more specific about what annotations to look for once i find out if this 'fix' even works.

**Comment by mebigfatguy** [comment]
so is this fixed? can it be closed?

**Comment by ThrawnCA** [comment]
This does fix the false positives, yes ☺. I'm not certain of the scope of its impact on false negatives...
