### ISSUE TITLE
NPE when running InefficientStringBuffering

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#110]
detail of exception (to reproduce spf4j project available at https://github.com/zolyfarkas/spf4j/): 

   [java] The following errors occurred during analysis:
     [java]   Exception analyzing org.spf4j.zel.vm.gen.ParseException using detector com.mebigfatguy.fbcontrib.detect.InefficientStringBuffering
     [java]     java.lang.NullPointerException
     [java]       At com.mebigfatguy.fbcontrib.detect.InefficientStringBuffering.sawInvokeVirtual(InefficientStringBuffering.java:189)
     [java]       At com.mebigfatguy.fbcontrib.detect.InefficientStringBuffering.sawOpcode(InefficientStringBuffering.java:105)
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:883)
     [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
     [java]       At com.mebigfatguy.fbcontrib.detect.InefficientStringBuffering.visitCode(InefficientStringBuffering.java:88)
     [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
     [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
     [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java]       At com.mebigfatguy.fbcontrib.detect.InefficientStringBuffering.visitClassContext(InefficientStringBuffering.java:71)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
Done FindBugs Analysis....

**Comment by mebigfatguy** [comment]
Thanks for the report. should be fixed in head, now.

**Comment by zolyfarkas** [comment]
you're welcome! I love fb-contrib! keep on!
