### ISSUE TITLE
False positives with EXS_EXCEPTION_SOFTENING_NO_CONSTRAINTS (I think)

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#111]
When I have code like :

>        doARunnable(() ->  {
>           try {
>               fut.get();
>             } catch (CancellationException ex) {
>             ....
>             } catch (ExecutionException ex) {
>            **   throw new RuntimeException(ex);**
>             } 
>           }
>         })

I get a EXS_EXCEPTION_SOFTENING_NO_CONSTRAINTS  at the highlighted line, unfortunately there is nothing I can do about it, Runnable forces me to handle checked exceptions.... and throwing a runtime exception is really acceptable...

Using jdk 1.8 u92 + fb-contrib 6.6.1

**Comment by mebigfatguy** [comment]
Thanks for the report, i believe the above will resolve your issue, and will make it into 6.6.2/6.8.0 eventually.
