### ISSUE TITLE
UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR does not take java.util.Objects into account

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#112]
``java.util.Objects`` is provided from JDK7 as a way to ensure that parameters are not null, but UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR does not recognise when values have been validated in this way.

**Comment by mebigfatguy** [comment]
Unless I'm misunderstanding you,  UWF is a FindBugs pattern not fb-contrib
