### ISSUE TITLE
BED_BOGUS_EXCEPTION_DECLARATION false positive with exception generics

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#115]
I am getting:

> Non derivable method org.spf4j.base.CallablesTest.testExecuteWithRetryTimeout() declares throwing an exception that isn't thrown [org.spf4j.base.CallablesTest] At CallablesTest.java:[line 153] BED_BOGUS_EXCEPTION_DECLARATION

here is the location:

https://github.com/zolyfarkas/spf4j/blob/master/spf4j-core/src/test/java/org/spf4j/base/CallablesTest.java#L153 

easily reproducible by building the latest MASTER

**Comment by mebigfatguy** [comment]
Thanks for the report. I was not aware you could templatize a throws clause... Nifty. thanks.

**Comment by mebigfatguy** [comment]
should be fixed on master. Again thanks for the report, always nice to learn something new.

**Comment by zolyfarkas** [comment]
Thanks!
