### ISSUE TITLE
Adding travis-ci for automate build

### ISSUE THREAD

**Issue by h3xstream** [mebigfatguy/fb-contrib#117]
It would be nice to active the hook for Travis-CI :
https://travis-ci.org/
https://docs.travis-ci.com/user/languages/java

The automate build would also integrate with the pull request and tell you if the changes are breaking the build.

**Comment by mebigfatguy** [comment]
want to add a pull request?

**Comment by h3xstream** [comment]
For code change, not yet.

**Comment by mebigfatguy** [comment]
applied thanks again

**Comment by h3xstream** [comment]
@mebigfatguy You need to allow Travis-CI to monitor commits. (By login with your GitHub account)

This page should show an history of the build once it is done: https://travis-ci.org/mebigfatguy/fb-contrib
This badge will also indicate the current status of your master branch : https://api.travis-ci.org/mebigfatguy/fb-contrib.svg?branch=master
