### ISSUE TITLE
LEST should not really complain about InvocationTargetException.getCause()

### ISSUE THREAD

**Issue by ksobolew** [mebigfatguy/fb-contrib#119]
This is a common pattern, at least in our application:

`
                try {
                    return method.invoke(target, args);
                } catch (InvocationTargetException e) {
                    throw e.getCause();
                }
`

But LEST complains that I'm throwing away valuable information. In this case I'm only throwing out information that does not bring anything new and useful :)

**Comment by ksobolew** [comment]
Oh, and it's usually The Right Thing To Do - code like this is inside proxy handlers, and proxy handlers should only throw exceptions that the actual method would throw. InvocationTargetException is rarely one of them.

**Comment by mebigfatguy** [comment]
seems reasonable, will fix

**Comment by mebigfatguy** [comment]
I was handling InvocationTargetException.getTargetException, but not getCause. will update

**Comment by mebigfatguy** [comment]
thanks for the report
