### ISSUE TITLE
Duplicate BugPattern type : CD_CIRCULAR_DEPENDENCY

### ISSUE THREAD

**Issue by h3xstream** [mebigfatguy/fb-contrib#120]
**Fb-contrib:**

```xml
<BugPattern type="CD_CIRCULAR_DEPENDENCY">
        <ShortDescription>Class has a circular dependency with other classes</ShortDescription>
        <LongDescription>Class {0} has a circular dependency with other classes</LongDescription>
        <Details>
```
https://github.com/mebigfatguy/fb-contrib/blob/master/etc/messages.xml#L4853

**FindBugs**

```xml
<BugPattern type="CD_CIRCULAR_DEPENDENCY">
        <ShortDescription>Class has a circular dependency with other classes</ShortDescription>
        <LongDescription>Class {0} has a circular dependency with other classes</LongDescription>
        <Details>
```
https://github.com/findbugsproject/findbugs/blob/master/findbugs/etc/messages.xml#L6948

I don't know if this is a port from either plugin. I suppose those IDs should be unique to avoid confusion when displaying the bug type description (plugin perspective).

**Comment by mebigfatguy** [comment]
The one in findbugs has seemingly been permanently disabled, so it shouldn't be an issue, i hope, altho i suppose i could rename them.

**Comment by mebigfatguy** [comment]
thanks
