### ISSUE TITLE
PRMC false positive when methods are called on instance field

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#121]
The PRMC detector fires when a method is called twice on a instance variable, with an instance method call on the current object in between. Since the intervening call might modify the instance field, these calls may not be redundant.

This occurs within fb-contrib, eg in BogusExceptionDeclaration (line 141):

    if (!declaredCheckedExceptions.isEmpty()) {
        super.visitCode(obj);
        if (!declaredCheckedExceptions.isEmpty()) {

**Comment by mebigfatguy** [comment]
yeah, probably should fix that. thanks

**Comment by mebigfatguy** [comment]
OK, attempted a fix. Likely this fix will be overly protected, and a bunch of False Negatives will pop up, but i suppose that's better than the alternative. More testing needed.
