### ISSUE TITLE
Ignore PRMC for java.util.stream.Collectors

### ISSUE THREAD

**Issue by commonquail** [mebigfatguy/fb-contrib#122]
Several static factory methods of `java.util.stream.Collectors` make no guarantees about mutability or thread-safety, e.g. `Collectors::toList`. We're getting some semantic false-positives caused by multiple streams ending in `collect(Collectors.toList())` inside the same method:

```java
List<String> xs = foos.stream()
		.map(Foo::getX)
		.collect(Collectors.toList());

List<String> ys = foos.stream()
		.map(Foo::getY)
		.collect(Collectors.toList());
```
It is correct that we *could* introduce a local accumulator and pass it to both `collect` invocations but `xs` and `ys` are completely independent and need to stay that way (at no point are they unified), so that would produce a wrong result.

Skimming through the method list of `Collectors` they all seem to be context-dependent, so PRMC would only apply to a few instances (in our case, 4 in 75 occurrances of `toList`). We're going to try and ignore `Collectors` locally but Java 8 is old enough that I think it appropriate for fb-contrib to at least take a stance on whether to ignore the class.

The type is reported as `Value toList()Ljava/util/stream/Collector;`. For purposes of disabling it would be helpful if the bug report included `className`, though I could see how that might cause information overload.

**Comment by mebigfatguy** [comment]
yeah, makes sense. i'll add Collectors to ignore

**Comment by mebigfatguy** [comment]
closing thanks again
