### ISSUE TITLE
Ignore PRMC for specific method

### ISSUE THREAD

**Issue by commonquail** [mebigfatguy/fb-contrib#123]
I can ignore PRMC for a specific class or a method name blacklist using [`isRiskyName`](https://github.com/mebigfatguy/fb-contrib/blob/ac0c8e2062336570d7fec5fa28e8c0a2c6612786/src/com/mebigfatguy/fbcontrib/detect/PossiblyRedundantMethodCalls.java#L421-L433). However, it looks like I can't ignore PRMC for a *specific* class and method combination.

We get a lot of results for `Integer::valueOf` and `Long::valueOf`. We would like to ignore these but not, for instance, `String::valueOf`. That means we can't use `fbcontrib.PRMC.riskynames=valueOf`. The alternative is suppressing `java/lang/Integer` (`Long`) but that then ignores all static methods, and that's really more than we would like. Would it be possible to look for something like `java/lang/Integer::valueOf`?

I appreciate that this request has really nothing to do with "riskiness".

**Comment by mebigfatguy** [comment]
makes sense. i'll add it

**Comment by commonquail** [comment]
Accidental ticket reference. Sorry.

**Comment by mebigfatguy** [comment]
hopefully this solves this issue, thanks for the report.
