### ISSUE TITLE
mvn install fails with single FCBL in CollectStatistics

### ISSUE THREAD

**Issue by commonquail** [mebigfatguy/fb-contrib#124]
Dogfeeding trigers an `FCBL_FIELD_COULD_BE_LOCAL` in `CollectStatistics` because of the `COMMON_METHOD_SIGS` field, failing the build.

> Class `com.mebigfatguy.fbcontrib.collect.CollectStatistics` defines fields that are used only as locals ["`com.mebigfatguy.fbcontrib.collect.CollectStatistics`"] At `CollectStatistics.java`:[lines 41-129]

This is a true-positive but it seems like it should just be ignored.

**Comment by mebigfatguy** [comment]
there will likely be a bunch of these :)

**Comment by mebigfatguy** [comment]
this is actually a copy of #121  so i'll close this one.
