### ISSUE TITLE
Possible cleanup: FloatingPointLoops and OpcodeUtils

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#127]
Should the logic in ``FloatingPointLoops.FloatForLoop`` make use of methods (specifically, ``isDStore`` and ``isFStore``) from ``OpcodeUtils``?

The conditional statements don't seem to be like-for-like replaceable, but someone who knows the logic better than I do might know whether it can be refactored...

**Comment by mebigfatguy** [comment]
thanks, done
