### ISSUE TITLE
CD_CIRCULAR_DEPENDENCY fires on member classes

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#130]
The CD_CIRCULAR_DEPENDENCY detector trips on classes like `BloatedAssignmentScope`, which reference and are referenced by their inner classes (`BloatedAssignmentScope$ScopeBlock`, in this case). This probably shouldn't be treated as a bug, since the inner class is a field of the outer class.

Also affects `DubiousListCollection` and `FloatingPointLoops`.

**Comment by zolyfarkas** [comment]
I just upgraded to 6.6.2 and started hitting this:

Class org.spf4j.base.asm.MethodInvocationClassVisitor has a circular dependency with other classes [org.spf4j.base.asm.MethodInvocationClassVisitor] At MethodInvocationClassVisitor.java:[lines 28-65] CD_CIRCULAR_DEPENDENCY

the class code is at:

https://github.com/zolyfarkas/spf4j/blob/d7b5d22c10da355f1a17a63888ab7a2ff49dff01/spf4j-asm/src/main/java/org/spf4j/base/asm/MethodInvocationClassVisitor.java

I could change the inner class and make it static to avoid this, but I am not sure that I gain anything out of it..

**Comment by zolyfarkas** [comment]
I believe this is due to CD_CIRCULAR_DEPENDENCY renamed to FCD_FIND_CIRCULAR_DEPENDENCY in 6.6.2? https://github.com/mebigfatguy/fb-contrib/issues/120 ?

**Comment by mebigfatguy** [comment]
If you have the chance could you run the trunk version here and see if the problem still exists?

**Comment by zolyfarkas** [comment]
Is there a build of latest trunk available in the maven central repo?

**Comment by mebigfatguy** [comment]
no, if you are able to clone and build this https://github.com/mebigfatguy/fb-contrib.git that would be helpful.

**Comment by ThrawnCA** [comment]
@zolyfarkas You should, at least, make the inner class static, which will avoid keeping an extra reference to the outer class copy of 'this', for each instance of the inner class.

**Comment by zolyfarkas** [comment]
@ThrawnCA  I understand that by making the inner class static will make this go away... but I am not sure what I get in return...this rule also seem to fire also when a inner static class inherits from the containing class.

For example:

https://github.com/zolyfarkas/spf4j/blob/b7909b13cad38d2d4af72cca8d98f7eaadb2c893/spf4j-core/src/main/java/org/spf4j/base/Either.java

fb complains with:

Class org.spf4j.base.Either has a circular dependency with other classes [org.spf4j.base.Either] At Either.java:[lines 24-121] CD_CIRCULAR_DEPENDENCY

will see if things are better in the latest trunk/master

**Comment by ThrawnCA** [comment]
I'm not sure that making the class static will help with the bug detector, but it will slightly reduce memory footprint.

Every instance of a non-static class retains a reference to the instance of the outer class in which it was created. Making the inner class static avoids this reference.

**Comment by mebigfatguy** [comment]
Can you tell me what the bug says? Does it say

Class has a circular dependency with other classes
or
Test for circular dependencies among classes

If it's the first it's in fb-contrib, if it's the second, it's in findbugs, altho the one in findbugs is supposed to be disabled.

**Comment by jsotuyod** [comment]
I'm seeing this too on 6.6.2. The one being triggered is the on from findbugs (category STYLE), and I'm even seeing it triggered side by side with the one from findbugs on the same report.

It seems that during the rename something was left out, which is enabling the findbugs one.

**Comment by mebigfatguy** [comment]
thanks for looking into it, do you see this with the trunk build?

**Comment by jsotuyod** [comment]
Can't build from master, I'm getting:

> BUILD FAILED
> fb-contrib/build.xml:122: taskdef class text.style.check.BugRankCheckStyleTask cannot be found
 using the classloader AntClassLoader[]

**Comment by jsotuyod** [comment]
Nevermind, my bad. I'm trying it right now.

**Comment by jsotuyod** [comment]
No, I'm not seeing it in trunk.

**Comment by mebigfatguy** [comment]
I believe the fix to #138 fixes this

**Comment by jsotuyod** [comment]
@mebigfatguy any chance to get a 6.6.3 release with this fix? I'd like to be able to trust on the detector being run every single time.

**Comment by mebigfatguy** [comment]
look for it at a maven repository near you.

**Comment by jsotuyod** [comment]
You are awesome! Thanks
