### ISSUE TITLE
Dogfooding: AFBR_ABNORMAL_FINALLY_BLOCK_RETURN fires on usage of `StopOpcodeParsingException

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#131]
The recent introduction of `StopOpcodeParsingException` has created situations in which an exception is thrown from a finally block, tripping `AFBR_ABNORMAL_FINALLY_BLOCK_RETURN`.

`OverlyConcreteParameter.sawOpcode`
`UnusedParameter.sawOpcode`

If this really is correct behavior, then perhaps they should be annotated to ignore the detector.

**Comment by mebigfatguy** [comment]
thanks, fixed
