### ISSUE TITLE
FCD_FIND_CIRCULAR_DEPENDENCY is flaky

### ISSUE THREAD

**Issue by jsotuyod** [mebigfatguy/fb-contrib#138]
Wrote a couple of classes with direct dependency from one another. Then asked findbugs to analyze just those 2 classes by specifying:

```xml
    <Jar>redacted/RateAppUtils.class</Jar>
    <Jar>redacted/RateDialogFragment.class</Jar>
```

No issues found. However, if I add a third class (even if not existing), either at the beginning or at the end:

```xml
    <Jar>redacted/RateAppUtils.class</Jar>
    <Jar>redacted/RateDialogFragment.class</Jar>
    <Jar>NonExisting.class</Jar>
```

I DO get a `FCD_FIND_CIRCULAR_DEPENDENCY`.

Now things get *really* weird. If the third class is in the middle:

```xml
    <Jar>redacted/RateDialogFragment.class</Jar>
    <Jar>NonExisting.class</Jar>
    <Jar>redacted/RateAppUtils.class</Jar>
```

Once again I get no reported `FCD_FIND_CIRCULAR_DEPENDENCY` issues whatsoever.

**Comment by mebigfatguy** [comment]
I can certainly believe the flakyness. I'm not 100% sure it's the order though. maybe it is... but i've seen it without order changes. Still looking into it.

**Comment by jsotuyod** [comment]
I've been debugging this, and after lots of swearing I finally made some interesting insights.

The detector is **sometimes** not created (added a `println` in the consutrctor of this and other detectors, the one on `FindCircularDependencies` was sometimes not called).

The issue seems to be rooted at how Findbugs creates detectors. It wraps each on a [`DetectorFactory`](https://github.com/findbugsproject/findbugs/blob/master/findbugs/src/java/edu/umd/cs/findbugs/DetectorFactory.java) which will create it on-demand through reflection, but before doing this. it will check if the detector is enabled. To do so, Findbugs performs the following:

```java
    public static boolean isDetectorEnabled(IFindBugsEngine findBugs, DetectorFactory factory, int rankThreshold) {

        if (!findBugs.getUserPreferences().isDetectorEnabled(factory)) {
            return false;
        }
```
[Source](https://github.com/findbugsproject/findbugs/blob/master/findbugs/src/java/edu/umd/cs/findbugs/FindBugs.java#L250-L252)

```java
    public boolean isDetectorEnabled(DetectorFactory factory) {
        String detectorName = factory.getShortName();
        Boolean enabled = detectorEnablementMap.get(detectorName);
        if (enabled == null) {
            // No explicit preference has been specified for this detector,
            // so use the default enablement specified by the
            // DetectorFactory.
            enabled = factory.isDefaultEnabled();
            detectorEnablementMap.put(detectorName, enabled);
        }
        return enabled;
    }
```
[Source](https://github.com/findbugsproject/findbugs/blob/master/findbugs/src/java/edu/umd/cs/findbugs/config/UserPreferences.java#L405-L416)

Where, as you can guess, `factory.getShortName()` is:

```java
    public String getShortName() {
        int endOfPkg = className.lastIndexOf('.');
        if (endOfPkg >= 0) {
            return className.substring(endOfPkg + 1);
        }
        return className;
    }
```
[Source](https://github.com/findbugsproject/findbugs/blob/master/findbugs/src/java/edu/umd/cs/findbugs/DetectorFactory.java#L403-L409)

So, `com.mebigfatguy.fbcontrib.detect.FindCircularDependencies` and `edu.umd.cs.findbugs.detect.FindCircularDependencies` collide in the map. Whichever gets loaded first, enables / disables both.

This will also explain #130!

As to why the order seems to be random, I'm not sure yet.

Changing the classname is a quick fix on fb-contrib's side (and one which probably justifies on it's own a 6.6.3 release). Findbugs should probably stop using simple classnames in favor of fully qualified class names.

**Comment by mebigfatguy** [comment]
Awesome. nice work by you.

**Comment by mebigfatguy** [comment]
thanks alot.really great catch.
