### ISSUE TITLE
fbcontrib.detect.BogusExceptionDeclaration -> java.lang.IllegalStateException: getClassConstantOperand called but value not available

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#139]
fb-contrib 6.6.2 exception when building https://github.com/zolyfarkas/spf4j/tree/master/spf4j-core

code is build with jdk 1.8 u102. 

Fork Value is true
     [java] The following errors occurred during analysis:
     [java]   Exception analyzing org.spf4j.concurrent.SequenceTest using detector com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration
     [java]     java.lang.IllegalStateException: getClassConstantOperand called but value not available
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.getClassConstantOperand(DismantleBytecode.java:331)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.sawOpcode(BogusExceptionDeclaration.java:226)
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:883)
     [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitCode(BogusExceptionDeclaration.java:144)
     [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
     [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
     [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitClassContext(BogusExceptionDeclaration.java:102)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
     [java]   Exception analyzing org.spf4j.concurrent.jdbc.JdbcHeartBeat using detector com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration
     [java]     java.lang.IllegalStateException: getClassConstantOperand called but value not available
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.getClassConstantOperand(DismantleBytecode.java:331)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.sawOpcode(BogusExceptionDeclaration.java:226)
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:883)
     [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitCode(BogusExceptionDeclaration.java:144)
     [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
     [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
     [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitClassContext(BogusExceptionDeclaration.java:102)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
     [java]   Exception analyzing org.spf4j.recyclable.impl.TestCallable using detector com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration
     [java]     java.lang.IllegalStateException: getClassConstantOperand called but value not available
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.getClassConstantOperand(DismantleBytecode.java:331)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.sawOpcode(BogusExceptionDeclaration.java:226)
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:883)
     [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitCode(BogusExceptionDeclaration.java:144)
     [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
     [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
     [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitClassContext(BogusExceptionDeclaration.java:102)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
     [java]   Exception analyzing org.spf4j.concurrent.jdbc.JdbcSemaphore using detector com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration
     [java]     java.lang.IllegalStateException: getClassConstantOperand called but value not available
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.getClassConstantOperand(DismantleBytecode.java:331)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.sawOpcode(BogusExceptionDeclaration.java:226)
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:883)
     [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitCode(BogusExceptionDeclaration.java:144)
     [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
     [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
     [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitClassContext(BogusExceptionDeclaration.java:102)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
     [java]   Exception analyzing org.spf4j.base.RuntimeTest using detector com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration
     [java]     java.lang.IllegalStateException: getClassConstantOperand called but value not available
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.getClassConstantOperand(DismantleBytecode.java:331)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.sawOpcode(BogusExceptionDeclaration.java:226)
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:883)
     [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitCode(BogusExceptionDeclaration.java:144)
     [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
     [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
     [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitClassContext(BogusExceptionDeclaration.java:102)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
     [java]   Exception analyzing org.spf4j.base.CallablesTest using detector com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration
     [java]     java.lang.IllegalStateException: getClassConstantOperand called but value not available
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.getClassConstantOperand(DismantleBytecode.java:331)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.sawOpcode(BogusExceptionDeclaration.java:226)
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:883)
     [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitCode(BogusExceptionDeclaration.java:144)
     [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
     [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
     [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitClassContext(BogusExceptionDeclaration.java:102)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
     [java]   Exception analyzing org.spf4j.concurrent.RetryExecutorTest using detector com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration
     [java]     java.lang.IllegalStateException: getClassConstantOperand called but value not available
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.getClassConstantOperand(DismantleBytecode.java:331)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.sawOpcode(BogusExceptionDeclaration.java:226)
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:883)
     [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitCode(BogusExceptionDeclaration.java:144)
     [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
     [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
     [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitClassContext(BogusExceptionDeclaration.java:102)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
     [java]   Exception analyzing org.spf4j.stackmonitor.SsdumpTest using detector com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration
     [java]     java.lang.IllegalStateException: getClassConstantOperand called but value not available
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.getClassConstantOperand(DismantleBytecode.java:331)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.sawOpcode(BogusExceptionDeclaration.java:226)
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:883)
     [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitCode(BogusExceptionDeclaration.java:144)
     [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
     [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
     [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitClassContext(BogusExceptionDeclaration.java:102)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
     [java]   Exception analyzing org.spf4j.recyclable.impl.ObjectPoolBuilderTest using detector com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration
     [java]     java.lang.IllegalStateException: getClassConstantOperand called but value not available
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.getClassConstantOperand(DismantleBytecode.java:331)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.sawOpcode(BogusExceptionDeclaration.java:226)
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:883)
     [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitCode(BogusExceptionDeclaration.java:144)
     [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
     [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
     [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitClassContext(BogusExceptionDeclaration.java:102)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
     [java]   Exception analyzing org.spf4j.recyclable.impl.ObjectPoolVsApache using detector com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration
     [java]     java.lang.IllegalStateException: getClassConstantOperand called but value not available
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.getClassConstantOperand(DismantleBytecode.java:331)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.sawOpcode(BogusExceptionDeclaration.java:226)
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:883)
     [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitCode(BogusExceptionDeclaration.java:144)
     [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
     [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
     [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitClassContext(BogusExceptionDeclaration.java:102)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
     [java]   Exception analyzing org.spf4j.stackmonitor.DemoTest using detector com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration
     [java]     java.lang.IllegalStateException: getClassConstantOperand called but value not available
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.getClassConstantOperand(DismantleBytecode.java:331)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.sawOpcode(BogusExceptionDeclaration.java:226)
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:883)
     [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitCode(BogusExceptionDeclaration.java:144)
     [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
     [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
     [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java]       At com.mebigfatguy.fbcontrib.detect.BogusExceptionDeclaration.visitClassContext(BogusExceptionDeclaration.java:102)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
Done FindBugs Analysis....

<<< findbugs-maven-plugin:3.0.4:check (default) < :findbugs @ spf4j-core <<<

--- findbugs-maven-plugin:3.0.4:check (default) @ spf4j-core ---
BugInstance size is 0
Error size is 11
No errors/warnings found

**Comment by zolyfarkas** [comment]
tried also with latest fb-contrib from repo and get the same errors.

**Comment by mebigfatguy** [comment]
thanks for the report. It appears to be a problem with INVOKEDYNAMIC. I see the same issue here
JdbcHeartBeat.java

  void createHeartbeatRow() throws InterruptedException {
    try {
      jdbc.transactOnConnection((final Connection conn, final long deadlineNanos) -> {

FindBugs doesn't appear to be processing the class name of the invokedynamic method call. Let me poke around some more tho.
