### ISSUE TITLE
LEST_LOST_EXCEPTION_STACK_TRACE when stack trace is not acctualy lost

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#140]
} catch (LoginException ex) {
      LoginException lex = new LoginException("My fancy new message");
      lex.addSuppressed(ex); // this is due to the fact that LoginException constructor that accepts a cause...
      throw lex;
    }

stack trace is not actually lost since it is available as a suppressed exception.

**Comment by mebigfatguy** [comment]
good catch, will fix shortly

**Comment by mebigfatguy** [comment]
thanks again!

**Comment by zolyfarkas** [comment]
You're welcome, and thank you for your work on this wonderful fb extension!
