### ISSUE TITLE
Best way to avoid ITC_INHERITANCE_TYPE_CHECKING?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#142]
Our application needs to apply security filtering to parameters contained in a Struts ``ActionContext`` (https://struts.apache.org/maven/struts2-core/apidocs/com/opensymphony/xwork2/ActionContext.html). Unfortunately, since ``ActionContext.getParameters`` only guarantees to return a ``Map<String, Object>``, that means that we pretty much have to pass an Object to a method that does ``instanceof`` checks and applies the appropriate sanitization code (for nulls, Strings, String arrays, etc). Which trips ITC_INHERITANCE_TYPE_CHECKING (and URV_UNRELATED_RETURN_VALUES, for that matter).

Is there a better way to differentiate these objects, or do we have to just ignore the detector(s)?

**Comment by mebigfatguy** [comment]
you can always use method overloading

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class Overloading {

    public static void main(String[] args) {
        Map<String, Object> m = new HashMap<>();

        m.put("a", new Date());
        m.put("b", "Hello");
        m.put("c", Long.valueOf(10));

        process(m, "a");
        process(m, "b");
        process(m, "c");

    }

    public static void process(Map<String, Object> m, String key) {

        Object o = m.get(key);

        process(o);
    }

    public static void process(Object o) {
        System.out.println("Object: " + o);
    }

    public static void process(String s) {
        System.out.println("String: " + s);
    }

    public static void process(Long l) {
        System.out.println("Long: " + l);
    }

}

**Comment by mebigfatguy** [comment]
can the value object implement an interface that you can cast to, then call a validate() method on that interface?

**Comment by ThrawnCA** [comment]
Sadly, not a chance. These are ultimately HTTP parameters, so they'll be `String` or `String[]`.

**Comment by mebigfatguy** [comment]
the only other option i can see is using reflection to call a type safe overloaded variant, which is no better.

**Comment by ThrawnCA** [comment]
OK, then. I'll just write an exclusion for that method. Thanks for the quick reply.
