### ISSUE TITLE
Possible FP when dogfooding BL_BURYING_LOGIC

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#144]
I'm attempting to resolve the UTWR_USE_TRY_WITH_RESOURCES alert on ``SuspiciousJDKVersionUse``. However, when I do, it starts tripping BL_BURYING_LOGIC, and I think it's a false positive.

My cleaned-up code looks like this:

    private boolean isValid(Map<String, Set<String>> validMethods, String clsName) throws IOException, ClassNotFoundException {
        Set<String> methodInfos = validMethods.get(clsName);
        if (methodInfos == null) {

            ZipEntry ze = jdkZip.getEntry(clsName + ".class");
            if (ze != null) {
                JavaClass calledClass = null;
                try (InputStream is = new BufferedInputStream(jdkZip.getInputStream(ze))) {
                    ClassParser parser = new ClassParser(is, clsName);
                    calledClass = parser.parse();
                }

                superNames.put(clsName, calledClass.getSuperclassName().replace('.', '/'));
                Method[] methods = calledClass.getMethods();

                methodInfos = new HashSet<String>(methods.length);
                validMethods.put(clsName, methodInfos);

                for (Method m : methods) {
                    methodInfos.add(m.getName() + m.getSignature());
                }
            } else if (clsName.startsWith("java/")) {
                bugReporter.reportBug(new BugInstance(this, BugType.SJVU_SUSPICIOUS_JDK_VERSION_USE.name(), HIGH_PRIORITY).addClass(this).addMethod(this)
                        .addSourceLine(this).addClass(clsName));
            }
        }

        if (methodInfos != null) {
            String wantedMethod = getNameConstantOperand() + getSigConstantOperand();
            if (methodInfos.contains(wantedMethod)) {
                return true;
            } else if (Values.SLASHED_JAVA_LANG_OBJECT.equals(clsName)) {
                return false;
            } else {
                return isValid(validMethods, superNames.get(clsName));
            }
        }

        return true;
    }

As you can see, the null check at the top of the method is not a true guard condition, because its body might populate the variable and thus affect the execution of the second block.

**Comment by mebigfatguy** [comment]
is it suggesting that the bottom if should be 
if (methodInfos == null) {
    return true;

....

**Comment by ThrawnCA** [comment]
That was it; thanks :). I've opened a pull request.
