### ISSUE TITLE
Suspicious logic in SuspiciousUninitializedArray.sawOpcode

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#147]
``SuspiciousUninitializedArray.sawOpcode`` appears to have an error in its handling of INVOKEDYNAMIC.

``userValue`` is set to the value of the opcode stack item, but then, a few lines later, it is unconditionally set to null.

**Comment by mebigfatguy** [comment]
yeah me being sloppy. fixed
