### ISSUE TITLE
Ignore PRMC for org.glassfish.jersey.client.ClientConfig.ClientConfig

### ISSUE THREAD

**Issue by mattnelson** [mebigfatguy/fb-contrib#150]
When constructing jersey2 clients there is a PRMC warning for the `property` method on the config class. The majority of the method calls on this class are intended to be chained together.

``` java
final ClientConfig config = new ClientConfig()
        .property(ClientProperties.CONNECT_TIMEOUT, 10_000)
        .property(ClientProperties.READ_TIMEOUT, 10_000)
        .property(ApacheClientProperties.REQUEST_CONFIG, requestConfig)
        .property(ApacheClientProperties.CONNECTION_MANAGER, connectionManager)
        .property(ApacheClientProperties.CONNECTION_MANAGER_SHARED, Boolean.TRUE)
        // Set the connector provider last to ensure that the ApacheClientProperties are honored
        .connectorProvider(new ApacheConnectorProvider());
```

**Comment by mebigfatguy** [comment]
Thanks I'll look at it when I get home.  actually I think that it's not the property calls but rather the boxing of the ten thousand to an integer. The detector should only look at methods that have no parameters or whose parameters are constants. And then constant parameters have to be the same. As a test if you could beforehand assign that 1000 to an integer object and pass the Integer object it will be interesting to see if that fixes it. I should probably ignore simple boxing methods and not report those. Thanks for the report.

**Comment by mattnelson** [comment]
Yep, you are right about the boxing. I changed it to 10000 and 10001 and the warning went away. Testing with a 10000 assigned before did not fix the issue.

**Comment by mebigfatguy** [comment]
this didn't squash the report?

Integer timeout = 10_000;
final ClientConfig config = new ClientConfig()
        .property(ClientProperties.CONNECT_TIMEOUT, timeout)
        .property(ClientProperties.READ_TIMEOUT, timeout)
        .property(ApacheClientProperties.REQUEST_CONFIG, requestConfig)
        .property(ApacheClientProperties.CONNECTION_MANAGER, connectionManager)
        .property(ApacheClientProperties.CONNECTION_MANAGER_SHARED, Boolean.TRUE)
        // Set the connector provider last to ensure that the ApacheClientProperties are honored
        .connectorProvider(new ApacheConnectorProvider());

**Comment by mattnelson** [comment]
Sorry, that does fix the issue. I used a primitive instead of the object type when assigning to the variable before the method call.
