### ISSUE TITLE
Section508Compliance signatures don't have return types?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#154]
Most of the ``displayTextMethods`` entries in ``Section508Compliance`` don't specify return types in their signatures. Is that because constructors are a special case? What about the ``setTitle`` entries?

And if constructors are indeed a special case, then why are they defined in ``CollectStatistics`` and``CharsetIssues`` with void return types?

**Comment by mebigfatguy** [comment]
no thats wrong, should be V
