### ISSUE TITLE
ArrayBasedCollections does not populate mapBugs or setBugs?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#158]
I'm looking at whether to combine the handling of maps and sets in ``ArrayBasedCollections``, but I can't find anywhere the ``mapBugs`` and ``setBugs`` lists are actually populated.

**Comment by mebigfatguy** [comment]
pretty weak on my part, but see bugList

**Comment by ThrawnCA** [comment]
But ``bugList`` is only assigned *from* those collections. Nothing (except an empty list) is ever assigned or added *to* them.

**Comment by mebigfatguy** [comment]
bugList acts as an alias to either mapBugs or setBugs depending on the if/else blocks.

Then at 167 bug list is added to (which therefore adds to mapBugs or setBugs)

                bugList.add(bi);

**Comment by ThrawnCA** [comment]
Argh! I can't un-see it.

OK, I'll see what I can do.
