### ISSUE TITLE
UnboundMethodTemplateParameter trims 'L' but not ';'?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#159]
``UnboundMethodTemplateParameter.TemplateItem`` constructor takes a substring of the input type, trimming off the leading 'L', but it doesn't attempt to trim a trailing ';'?

Looking briefly through the logic of the class, it seems that it only compares the result to others constructed in similar fashion, so it might still work. However, trimming the 'L' then seems pointless.

**Comment by mebigfatguy** [comment]
the regex 'TEMPLATE' -> \<?([^:]+):([^;]*);    doesn't include the semicolon in the group... which is why it isn't present. As you point out, probably makes sense to stuff the semi in the parens, and then strip it along with the L.
