### ISSUE TITLE
JXI_UNDEFINED_PARAMETER_SOURCE_IN_ENDPOINT is unaware of @BeanParam

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#167]
for 

  @GET
  @Path("/bpecho")
  @Produces({"application/json", "application/octet-stream", "application/json;fmt=avro"})
  public KeyValue bpecho(@BeanParam final KeyValue obj) {
    LOG.info("Received {}", obj);
    return obj;
  }

I get:

JAX-RS Method com.pimco.popcorn.camel.TestRestService.bpecho(KeyValue) defines a parameter that has no @*Param or @Context annotation, or @Consumes method annotation [com.pimco.popcorn.camel.TestRestService] At TestRestService.java:[lines 410-411] JXI_UNDEFINED_PARAMETER_SOURCE_IN_ENDPOINT

here is a description of @BeanParam:

https://dennis-xlc.gitbooks.io/restful-java-with-jax-rs-2-0-2rd-edition/content/en/part1/chapter5/bean_param.html

**Comment by mebigfatguy** [comment]
thanks,fixed
