### ISSUE TITLE
MethodReturnsConstant breaks global method list

### ISSUE THREAD

**Issue by rblasch** [mebigfatguy/fb-contrib#169]
`MethodReturnsConstant#collectOverloadedMethods` gets the method list by calling `JavaClass#getMethods`, and modifies the returned array. But this array is shared by everyone, so every detector following `MethodReturnsConstant` may see a bogus method list. `collectOverloadedMethods` should make a copy of the array, maybe by calling `clone`.

    Method[] methods = cls.getMethods().clone();

**Comment by mebigfatguy** [comment]
wow, what kind of meathead am i. good catch.

**Comment by mebigfatguy** [comment]
thanks tons.

**Comment by mebigfatguy** [comment]
6.8.2 released
