### ISSUE TITLE
BL_BURYING_LOGIC too aggressive?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#174]
BL_BURYING_LOGIC is firing in a situation where it's not *wrong*, but probably not desirable either.

I'm checking a URI to see whether it contains various strings, with different behavior on each one, and a fallback if it doesn't match any (it's a mock server, so it doesn't need to be elegant):

    if (uri.contains("string1")) {
        return <some logic>;
    } else if (uri.contains("string2")) {
        switch (someOtherVariable) {
            ...
        }
        return <some logic>;
    }
    return <fallback logic>;

The detector seems to think that I should change the last condition to `if (!uri.contains("string2"))`, so that I can move the `switch` to a higher indent level, but that's ugly. I think it probably shouldn't do depth checks like this beyond checking for simple guard clauses.

**Comment by mebigfatguy** [comment]
yeah probably right.

Problem is the code doesn't look like an else if based on byte code, given the return statement. I suppose i could look for successive if statements checking against the same variable, but what would that mean? as you show, it's not even .equals checks, could be anything.

**Comment by ThrawnCA** [comment]
Another situation where I *could* reverse the order of conditions, but it's really more readable if I don't:

    if (!status.isSuccess() || isBlank(redirectUrl)) {
        LOG.error("Unable to submit payment request (Error: {}, Redirect Url: {})", status.getError(), redirectUrl);
        addActionError(WEB_SERVICE_ERROR_MESSAGE);
        return INPUT;
    }
    return SUCCESS;

I'd rather have the method end with the success state, rather than ending with the failure state.

Maybe the detector should be less ambitious, and just focus on cases where the entire method body is wrapped in a condition.

**Comment by mebigfatguy** [comment]
thinking, thinking... churn churn... i will address this, sorry for the delay.

**Comment by mebigfatguy** [comment]
let me know what 6.8.4 does for you. Will close, but feel free to open if there are still issues.

**Comment by ThrawnCA** [comment]
Looks like the change has fixed one kind of false positive, but opened another. I'm having trouble isolating a sample, but it involves most of the method being wrapped in a condition that might or might not return early.

**Comment by ThrawnCA** [comment]
I can reproduce this consistently with one of our classes, but it's dependent on a whole lot of our other code, and as soon as I try to prune any of it away, the false positive stops.

Do you want `javap` output from our compiled class?

**Comment by mebigfatguy** [comment]
Sure!
