### ISSUE TITLE
Ignore PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS for guava default methods

### ISSUE THREAD

**Issue by afrin216** [mebigfatguy/fb-contrib#177]
Findbugs reports `PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS` for methods such as `Optional.empty()` and `ImmutableSet.of()` which should not be re used due to type inference based on usage. Also the common usage also throws up raw types warnings in IDEs and the java error prone compiler. 

These should be excluded.

**Comment by mebigfatguy** [comment]
so ignore methods that return java.lang.Object.... you are saying... seems right.

**Comment by afrin216** [comment]
Yep. Typed Param returning methods seems about right since they infer types. Just found that my issue happened with `java.util.Optional.empty()` , not guava, FYI !

**Comment by mebigfatguy** [comment]
thanks for the report, this should fix it, if you can pull HEAD and test that would be great.
