### ISSUE TITLE
DMC_DUBIOUS_MAP_COLLECTION false positive when map field *might* be used

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#180]
We have a class with two static constant map structures, and a private helper method that returns one or the other, after which an item will be retrieved (using `get`) from whichever map is returned.

Unfortunately, it appears that the `DMC_DUBIOUS_MAP_COLLECTION` detector loses track of the fields when they pass through this helper, so it never registers the fact that `get` might be called, and assumes that the fields could be converted to `List`.

    import java.util.ArrayList;
    import java.util.EnumMap;
    import java.util.List;
    import java.util.Map;

    public class ItemDetailTransformerService {
        private static Map<CustomerDetailType, CustomerDetailsRequestType> mandatoryCustomerDetails = new EnumMap<CustomerDetailType, CustomerDetailsRequestType>(CustomerDetailType.class);
        private static Map<CustomerDetailType, CustomerDetailsRequestType> optionalCustomerDetails = new EnumMap<CustomerDetailType, CustomerDetailsRequestType>(CustomerDetailType.class);

        static {
            mandatoryCustomerDetails.put(CustomerDetailType.CUSTOMER, CustomerDetailsRequestType.CUSTOMER_REQUIRED);
            mandatoryCustomerDetails.put(CustomerDetailType.EMAIL, CustomerDetailsRequestType.EMAIL_REQUIRED);
            mandatoryCustomerDetails.put(CustomerDetailType.POST, CustomerDetailsRequestType.POST_REQUIRED);
            mandatoryCustomerDetails.put(CustomerDetailType.PHONE, CustomerDetailsRequestType.PHONE_REQUIRED);
            mandatoryCustomerDetails.put(CustomerDetailType.FAX, CustomerDetailsRequestType.FAX_REQUIRED);

            optionalCustomerDetails.put(CustomerDetailType.CUSTOMER, CustomerDetailsRequestType.CUSTOMER_REQUESTED);
            optionalCustomerDetails.put(CustomerDetailType.EMAIL, CustomerDetailsRequestType.EMAIL_REQUESTED);
            optionalCustomerDetails.put(CustomerDetailType.POST, CustomerDetailsRequestType.POST_REQUESTED);
            optionalCustomerDetails.put(CustomerDetailType.PHONE, CustomerDetailsRequestType.PHONE_REQUESTED);
            optionalCustomerDetails.put(CustomerDetailType.FAX, CustomerDetailsRequestType.FAX_REQUESTED);
        }

        public List<CustomerDetailsRequestType> transformCustomerDetails(List<CustomerDetail> customerDetails) {
            ArrayList<CustomerDetailsRequestType> result = new ArrayList<CustomerDetailsRequestType>();

            for (CustomerDetail customerDetail : customerDetails) {
                result.add(getCustomerMap(customerDetail.isMandatory()).get(customerDetail.getType()));
            }

            return result;
        }

        private static Map<CustomerDetailType, CustomerDetailsRequestType> getCustomerMap(boolean mandatory) {
            return mandatory ? mandatoryCustomerDetails : optionalCustomerDetails;
        }

    }

**Comment by mebigfatguy** [comment]
thanks. this is really due to the fact the Findbugs is screwed up in the way it handles ternaries (at least from my point of view). I'll fix it

**Comment by mebigfatguy** [comment]
should be fixed, thanks again.

**Comment by ThrawnCA** [comment]
Should we raise a SpotBugs issue about this?

**Comment by mebigfatguy** [comment]
OpcodeStack throws out the front half of the ternary value. Ideally it would present an OpcodeStack.Itme that represented both items. That's not fun to do tho, probably.

**Comment by ThrawnCA** [comment]
So it would likely be a breaking change? That's probably acceptable if the version number is incremented properly.
