### ISSUE TITLE
False positive when checking for versions

### ISSUE THREAD

**Issue by martofeld** [mebigfatguy/fb-contrib#183]
The following snippet is reported as BL_BURYING_LOGIC cc @jsotuyod 

![image](https://cloud.githubusercontent.com/assets/5756343/23561917/1f31c064-001f-11e7-9153-2c6dd0fd18a6.png)

**Comment by mebigfatguy** [comment]
the detector is asking you to consider using

if (Build.Version.SDK_INT != Build.VERSION_CODES.LOLLIPOP) {
      return ViewGroup.LayoutParams.MATCH_PARENT;
}

WindowManager windowManager = (WindowManager) context.getSystemService(Context.WINDOW.SERVICE);
....
....
return size.y - getStatusBarHeight(context);

as it is easier to read.

**Comment by mebigfatguy** [comment]
so i believe this is correct. it's possible you disagree, and if so, just disable the detector, but it is working as expected. thanks for the report

**Comment by martofeld** [comment]
Hadn't seen it that way, thanks for the answer
