### ISSUE TITLE
False positive when returning a method parameter

### ISSUE THREAD

**Issue by martofeld** [mebigfatguy/fb-contrib#184]
This snippet throws CFS_CONFUSING_FUNCTION_SEMANTICS when the parameter is returned unmodified cc @jsotuyod 

![image](https://cloud.githubusercontent.com/assets/5756343/23562330/c9bb88a2-0020-11e7-8225-d508e3091d5a.png)

**Comment by mebigfatguy** [comment]
that's a reasonable suggestion, i'll see what i can do.

**Comment by mebigfatguy** [comment]
as i don't have your exact code, can't say for sure that i fixed your particular case, but a FP that i cooked up to look like yours is fixed, so hopefully yours is too.

thanks for the report.
