### ISSUE TITLE
Best way to use it from Maven

### ISSUE THREAD

**Issue by levonk** [mebigfatguy/fb-contrib#186]
Thanks for all the great additions. 

Could the documentation be updated to clarify how to add support to the http://gleclaire.github.io/findbugs-maven-plugin/ ?

**Comment by mebigfatguy** [comment]
Hi levonk, i don't have any affiliation with that site, that said, this page

http://gleclaire.github.io/findbugs-maven-plugin/usage.html

shows how to do it, specifically

Using Third party or your own detectors
The pluginList option specifies a comma-separated list of optional BugDetector Jar files to add.

<project>
  ...
  <reporting>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>findbugs-maven-plugin</artifactId>
        <version>3.0.5-SNAPSHOT</version>
        <configuration>
          <pluginList>myDetectors.jar, yourDetectors.jar</pluginList>
        </configuration>
      </plugin>
    </plugins>
  </reporting>
  ...
</project>

**Comment by ThrawnCA** [comment]
Actually, if I'm reading correctly, `pluginList` is to be used to reference local JARs.

For JARs that are on Maven Central (which `fb-contrib` is), use the `plugins` element instead, specifying the group and artifact ID(s).
