### ISSUE TITLE
False positives for SPP_SERIALVER_SHOULD_BE_PRIVATE for interface variables

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#188]
```java
public interface Test extends Serializable {
	long serialVersionUID = 1L;
}
```

This gives the `SPP_SERIALVER_SHOULD_BE_PRIVATE` warning, however this variable cannot be private as it is in an interface.

**Comment by mebigfatguy** [comment]
ok, makes sense, will fix. thanks for the report.

**Comment by ThrawnCA** [comment]
Does it even make sense to have a `serialVersionUID` on interfaces? Sounds like you want to implement `Serializable`, but don't want to take the time to actually make your objects serializable.

**Comment by boris-petrov** [comment]
Well, it's not something I made up. If I don't put `serialVersionUID` there (in the interface definition), javac with `-Xlint:all` gives me: `warning: [serial] serializable class Test has no definition of serialVersionUID`.

**Comment by ThrawnCA** [comment]
That's...interesting. As far as I'm aware, it makes no sense for `lint` to be doing that. You should probably raise it as a bug with the `javac` folks.

Yes, serializable classes should have a `serialVersionUID`, but that shouldn't be a matter of defining a constant in an interface and then forgetting about it. You may as well not bother defining the constant in that case.
