### ISSUE TITLE
False positive OPM_OVERLY_PERMISSIVE_METHOD w/ function references

### ISSUE THREAD

**Issue by efenderbosch** [mebigfatguy/fb-contrib#190]
I'm scheduling a task like this
``flushTask = Executors.newSingleThreadScheduledExecutor()
                .scheduleAtFixedRate(writer::flush, flushPeriod, flushPeriod, TimeUnit.SECONDS);``

fb-contrib throws ``OPM_OVERLY_PERMISSIVE_METHOD`` when analyzing the writer::flush method.

**Comment by mebigfatguy** [comment]
thanks for the report. i can certainly believe that. :) will fix.

**Comment by mebigfatguy** [comment]
thanks, should be fixed.  unfortunately bcel/findbugs has little support for invoke dynamic and method handles so if that support does come, this will have to be redone.

**Comment by jsotuyod** [comment]
@mebigfatguy are the current changes proposed for Spotbugs 3.1.0 enough for this or are you still missing anything?

**Comment by mebigfatguy** [comment]
@jsotuyod it's mostly a bcel issue, i think with the new one, it's fine. spotbugs could add a visitBootstrapMethod, but that probably isn't necessary
