### ISSUE TITLE
Prefer Instant.now() over new Date().toInstant()

### ISSUE THREAD

**Issue by ARentz07** [mebigfatguy/fb-contrib#191]
A common pattern I have seen (and sometimes used) is to construct a `new Date()` and then immediately convert it to an Instant. This is unnecessary and should be discouraged.

**Comment by mebigfatguy** [comment]
are you saying this pattern?

Instant i = new Date().toInstant(); 

?

**Comment by ARentz07** [comment]
Correct, that's the one.

**Comment by mebigfatguy** [comment]
thanks for the idea. hopefully head has it working. If you want to pull, build and test the master branch, that would be great.
