### ISSUE TITLE
False positive for UAC_UNNECESSARY_API_CONVERSION_FILE_TO_PATH

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#192]
```java
public static void getIndexPathDirectory(String indexPath) throws IOException {
	File indexPathDirectory = new File(indexPath);
	if (indexPathDirectory.isDirectory() || indexPathDirectory.mkdirs()) {
		foo(indexPathDirectory.toPath());
	} else {
		throw new Exception();
	}
}

public static foo(Path path) {
	...
}
```

I don't think this should give the `UAC_UNNECESSARY_API_CONVERSION_FILE_TO_PATH` warning for the `foo(indexPathDirectory.toPath());` line.
FindBugsContrib version 7.0.0.

**Comment by mebigfatguy** [comment]
if you are using paths, why not use Paths.get rather than new File, and Files.isDirectory, and Files.createDirectories, rather than having a mish mash of apis?

**Comment by boris-petrov** [comment]
Because I didn't know these APIs existed. :) Thanks, closing!

**Comment by mebigfatguy** [comment]
cheers!
