### ISSUE TITLE
Question about 7+ versions on JDK 7.

### ISSUE THREAD

**Issue by ksiczek** [mebigfatguy/fb-contrib#195]
Hi, 

is there any chance to have version 7+ compatible with jdk 7? 

Regards,

Karol.

**Comment by mebigfatguy** [comment]
yikes! completely unintentional. thanks for the report. i have no idea how that happened. will cut a 7.0.1 shortly.

**Comment by mebigfatguy** [comment]
7.0.1 pushed to maven central. Should show up in a few hours. Again, thanks for the report, and sorry for the trouble.

**Comment by ksiczek** [comment]
Looks good, thanks.
