### ISSUE TITLE
False positive PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS w/ autoboxing

### ISSUE THREAD

**Issue by efenderbosch** [mebigfatguy/fb-contrib#198]
A constructor signature like ``public SomeObject(Long param1, Long param2) { ... }`` will trigger PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS when invoked via  ``new SomeObject(1L, 1L)`` but not when invoked via ``new SomeObject(2L, 1L)``.  Guessing that fb-contrib is detecting the duplicate autoboxing.

Maybe this isn't a false positive, but should be a more specific error indicating the duplicate autoboxing?

**Comment by mebigfatguy** [comment]
yes it's the autoboxing. i probably should just ignore autoboxing duplicates.

**Comment by mebigfatguy** [comment]
thanks for the report.
