### ISSUE TITLE
Somewhat false positive for OI_OPTIONAL_ISSUES_USES_IMMEDIATE_EXECUTION

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#201]
This is not exactly a false-positive but it is something I'm going to suppress if you cannot fix as it is not actually an issue.

We use `RxJava` for asynchronous computations. I have a method that returns a `Single<Something>`. If you're unfamiliar with `RxJava`, this is like a promise. Inside this method I do something like:

```java
Single<Something> foo() {
	Optional<Other> other = getOther();
	Single<Something> perform = Single.create(emitter -> ...);
	return other
		.map(other -> other.toSomethingSingle())
		.orElse(perform);
}
```

The semantics of this is as follows - I'm getting an optional `Other` from which I can get a `Single`. If I can't (the `orElse` case) - I just return another `Single` which I create in place. In cases like this I don't care that this code executes immediately and it may be useless as this is actually a promise and nothing gets computed anyway if I don't force the promise which happens AFTER this method returns.

I'm not sure I explain this clearly enough. Strictly speaking the check is correct and this is not a false-positive. But semantically it is. I will understand if you don't want to "fix" this or don't even know how to - after all this is a really specific use-case. I just wanted to mention it. :)

Thanks for the support!

**Comment by ThrawnCA** [comment]
I'm not familiar with RxJava, no. However, I also don't understand how you're able to pass a value of type `Single` to the `orElse` method of an `Optional` with generic type `Other`. Can you clarify?

**Comment by boris-petrov** [comment]
Well, I call `other.toSomethingSingle()` (which returns a `Single<Something>` as the name specifies) inside `Optional.map`. Here is a complete program:

```java
import java.util.Optional;
import io.reactivex.Single;

class A {
	class Something {
	}

	class Other {
		Single<Something> toSomethingSingle() {
			return null;
		}
	}

	Optional<Other> getOther() {
		return Optional.empty();
	}

	Single<Something> foo() {
		Optional<Other> other = getOther();
		Single<Something> perform = Single.create(emitter -> {});
		return other
			.map(o -> o.toSomethingSingle())
			.orElse(perform);
	}
}
```

**Comment by mebigfatguy** [comment]
Thanks, i believe this covers your case, w/o hurting the target audience.
