### ISSUE TITLE
FCCD doesn't catch annotations

### ISSUE THREAD

**Issue by stephanenicolas** [mebigfatguy/fb-contrib#202]
But first of all, thx a lot for the fb-contrib plugin, we really appreciate to be able to find cycles using findbugs.

we have a case where another tool, namely classycle, reports a bug that FCCD can't find:
```java
@MyAnnotation(Bar.class)
class Foo {
}

class Bar{
 Foo foo;
}
```

FCCD doesn't seem to take annotations into account, and:
* yes, the annotation has runtime retention
* no, the classes ain't in the same package

**Comment by mebigfatguy** [comment]
nice! thanks for the idea....so, what annotations does one consider.. just class level annotations? or method ones, or ....?

**Comment by stephanenicolas** [comment]
I would consider all that have a runtime and class retention, not source.

**Comment by mebigfatguy** [comment]
thanks for the idea, hopefully this gets it.
