### ISSUE TITLE
OPM false positive

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#206]
The OPM_OVERLY_PERMISSIVE_METHOD detector is firing on some of our code that is, in fact, used outside its package.

The only place where it's used, though, is buried within a Mockito argument matcher, so perhaps it's being overlooked?

`RuleMatcher`, which is a custom Hamcrest matcher, has the following constructors:

    public RuleMatcher(RedirectionRule rule) {
        this(rule.getSource(), rule.getTarget(), rule.getPriority());
    }

    public RuleMatcher(String source, String target, int priority) {
        this.source = source;
        this.target = target;
        this.priority = priority;
    }

And then we use it in a test like so:

        when(service.createRuleBatch(eq(dryRunResults), argThat(new RuleMatcher(SOURCE, TARGET, RedirectionRule.REWRITE_PRIORITY)))).thenReturn(Boolean.TRUE);

The OPM detector apparently doesn't recognise the above usage, and complains that the `RuleMatcher(String, String, int)` constructor is not used outside its class and doesn't need to be public.

**Comment by mebigfatguy** [comment]
i'll ask the dumb question on my part, but you are including the junit classes in your scan as well, right?

**Comment by ThrawnCA** [comment]
Yes - also, `RuleMatcher` is in the test source tree, so if test classes were skipped, it wouldn't show up.

**Comment by ThrawnCA** [comment]
Version 7.2.0 fixed this.
