### ISSUE TITLE
Pick a build system

### ISSUE THREAD

**Issue by hazendaz** [mebigfatguy/fb-contrib#208]
Having both maven and ant to perform builds is pretty antipattern.  It would be best to delete ant and simply be a maven project.  There is no real benefit to using two different build systems.  It would simplify development as well.

**Comment by mebigfatguy** [comment]
heh. if i had to pick one, i'd choose ant. I know i will be able to fix any problems i have with it in the future. I'm not confident at all with maven.

**Comment by hazendaz** [comment]
I'll help get the build there.  It doesn't appear to pass all the checks with maven currently but did help me flush out spot bugs maven plugin issue i had and I had not previously heard of you library until someone noted the plugin break so I plan to spend some time checking it out.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ThrawnCA** [comment]
@hazendaz I use Maven, and will report issues with it (including dogfooding issues), but I'm a much more irregular committer. Feel free to open pull requests yourself, they get looked at pretty fast.

**Comment by mebigfatguy** [comment]
if someone wants to get travis ci working again, that would be cool

**Comment by hazendaz** [comment]
@mebigfatguy I have travis build fixed.  I'll submit a PR in a few minutes.  Two issues, one it fails PMD due to locale setting, simple fix on that.  Then second, it isn't handling generics correctly so I just added a todo for research but it will have travis back working.
