### ISSUE TITLE
Whitelist reflective equals for EQ_DOESNT_OVERRIDE_EQUALS

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#216]
The Apache `commons-lang` project provides reflection-based options for implementing `equals`, `hashCode`, and `toString`. Thus, it is legitimate to create an abstract superclass with these implementations, and not override them in subclasses.

Is it feasible to whitelist this approach, where the superclass implementation of `equals` includes a call to `EqualsBuilder.reflectionEquals`?

**Comment by mebigfatguy** [comment]
Likely you'd have to add this to a Splt pass detector to collect classes that do this, so that in later passes you could check when the sub class came about, you could ignore..  ... altho this is a SpotBugs issue :)
