### ISSUE TITLE
BED_BOGUS_EXCEPTION_DECLARATION ignores Optional.orElseThrow()

### ISSUE THREAD

**Issue by aaron-haskins** [mebigfatguy/fb-contrib#217]
BED_BOGUS_EXCEPTION_DECLARATION is wrongly reported in a method which uses [Optional.orElseThrow()](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#orElseThrow-java.util.function.Supplier-) method:
```java
private String getHashFromChecksum(Optional<String> checksum) throws IOException {
  return checksum
    .orElseThrow(() -> new IOException("Failed to get checksum..."));
}
```

**Comment by mebigfatguy** [comment]
thanks for the report. should be fixed in head
