### ISSUE TITLE
Feature request: Add a bug for use of AccessibleObject::setAccessible

### ISSUE THREAD

**Issue by efenderbosch** [mebigfatguy/fb-contrib#218]
We've got some folks new to Java that are using this and need to make sure they stop. Code reviews help, but failing builds will hopefully keep this from even getting to that stage.

**Comment by mebigfatguy** [comment]
thanks for the idea. That should take care of it.

**Comment by ThrawnCA** [comment]
Note that `fb-contrib` uses this itself in `ToString::generate`. Should it just be dropped?
