### ISSUE TITLE
SSCU_SUSPICIOUS_SHADED_CLASS_USE false positive

### ISSUE THREAD

**Issue by mattnelson** [mebigfatguy/fb-contrib#219]
When using sysout-over-slf4j[1] I am getting a false positive on `SSCU_SUSPICIOUS_SHADED_CLASS_USE` because the class is named `uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4J` which has `org` not at the root[2].

Is there any visibility to the class path to know if an alternative nonshaded version of the class is available before alerting?

[1] https://github.com/Mahoney/sysout-over-slf4j
[2] https://github.com/mebigfatguy/fb-contrib/blob/v7.0.2/src/main/java/com/mebigfatguy/fbcontrib/detect/SuspiciousShadedClassUse.java#L34-L40

**Comment by mebigfatguy** [comment]
thanks for the report, i think the best option is to just enumerate known exceptions... hopefully there aren't many. should be fixed in HEAD.
