### ISSUE TITLE
False positive PDP_POORLY_DEFINED_PARAMETER on lambda expressions

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#224]
We're hitting `PDP_POORLY_DEFINED_PARAMETER` when we cast a lambda parameter to a subclass, eg:

    httpSecurity.logout()
            .logoutRequestMatcher(new AntPathRequestMatcher("/logout"))
            .logoutSuccessHandler((request, response, authentication) -> {

    ->          UsernamePasswordAuthenticationToken authenticationToken = (UsernamePasswordAuthenticationToken) authentication;
                if (authenticationToken != null && authenticationToken.getPrincipal() != null) {

(This uses Spring Security with JavaConfig; I can probably provide more of the code if needed.)

**Comment by mebigfatguy** [comment]
one assumes that 'authenticationToken' is passed to the method that this code is in... and if so how is it defined? And why can't it be defined as UsernamePasswordAuthenticationToken? Hard to tell what's going on here.

**Comment by ThrawnCA** [comment]
It's Spring Security's `LogoutSuccessHandler`: https://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/web/authentication/logout/LogoutSuccessHandler.html

**Comment by mebigfatguy** [comment]
ok, i see, so the type of authentication is constrained by the LogoutSuccessHandler interface to be Authentication, and since you are not actually defining that parm, you can't change it.... got it now

**Comment by mebigfatguy** [comment]
Can you take a look at my sample and see why it is substantially different than yours? This doesn't show the FP, but i'd think it would. just look at the bottom of the file the final method.

**Comment by mebigfatguy** [comment]
Ah never mind i got it.

**Comment by mebigfatguy** [comment]
thanks!

**Comment by ThrawnCA** [comment]
This fixes it :). Thanks.
