### ISSUE TITLE
False positive COM Method merely delegates to its superclass's version

### ISSUE THREAD

**Issue by archmageirvine** [mebigfatguy/fb-contrib#225]
The following code results in a false-positive "COM Method merely delegates to its superclass's version" with the implication that the overridden method in class `ASync` can be removed.  However, the synchronization on the overridden method in class `ASync` means it cannot be removed without modifying the behavior of the code.  We encountered a real situation in our code where this distinction is important.

```
class A {
  public int method() {
    // do something complicated
    return 42;
  }
}

class ASync extends A {
  public synchronized int method() {
    return super.method();
  }
}
```

**Comment by mebigfatguy** [comment]
ah! thanks for the report.

**Comment by mebigfatguy** [comment]
should be fixed in head. thanks!
