### ISSUE TITLE
LII false positive

### ISSUE THREAD

**Issue by archmageirvine** [mebigfatguy/fb-contrib#228]
I'm impressed with your speed at fixing previous false-positives.  Here's another one, this time for LII.  Granted there is probably other ways of writing this code (and I've taken out some other code to check the lists have the same size etc.), but this seems to be a case where using a single variable to index both the lists seems reasonable.  Possibly the checker is getting confused by reference to same field in different objects?

```
A.java:9:9 LII: Method A.compare(A) uses integer based for loops to iterate over a List (M) 
```

```
import java.util.List;
import java.util.ArrayList;

class A {

  private final List<String> a = new ArrayList<>();

  int compare(final A b) {
    for (int k = 0; k < a.size(); ++k) {
      final int c = a.get(k).compareTo(b.a.get(k));
      if (c != 0) {
        return c;
      }
    }
    return 0;
  }
}
```

**Comment by mebigfatguy** [comment]
Thanks for the report, i'm going to guess it thinks a and b.a are the same thing, erroneously.

**Comment by mebigfatguy** [comment]
thanks for the report, should be fixed in HEAD
