### ISSUE TITLE
Maven build fails on Spotbugs branch

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#230]
The `spotbugs` branch presumably builds with Ant, but fails with Maven (it's still unpacking FindBugs core instead of Spotbugs, and has PMD issues).

Will submit pull request(s) soon.

**Comment by mebigfatguy** [comment]
thanks accepted patch

**Comment by ThrawnCA** [comment]
Still need to sort out what to do about #218 before the Maven build will work.
