### ISSUE TITLE
NPE in OptionalIssues.sawOpcode

### ISSUE THREAD

**Issue by pmayweg** [mebigfatguy/fb-contrib#233]
Hi,
I get an NPE when analyzing an Optional.orElseGet(null). The stacktrace is:
 java.lang.NullPointerException
   At com.mebigfatguy.fbcontrib.detect.OptionalIssues.sawOpcode(OptionalIssues.java:209)
   At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:882)
   At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
   At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:241)
   At com.mebigfatguy.fbcontrib.detect.OptionalIssues.visitCode(OptionalIssues.java:135)
   At org.apache.bcel.classfile.Code.accept(Code.java:132)
   At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:313)
   At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:401)
   At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
   At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
   At com.mebigfatguy.fbcontrib.detect.OptionalIssues.visitClassContext(OptionalIssues.java:116)
   At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
   At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1083)
   At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:280)
The Opcode is ACONST_NULL and the ActiveStackOp.method is null.
Do you need a sample class for testing?

**Comment by mebigfatguy** [comment]
I've added the above test but it doesn't seem to cause the problem you are reporting. What version of fb-contrib are you using? and can you suggest changes that would show the problem?  Thanks for the report!

**Comment by pmayweg** [comment]
It is not orElse but orElseGet. I know that does make much sense. I am just a build manager and this is in one of our test classes.

**Comment by pmayweg** [comment]
I am using HEAD of master of the spotbugs branch.

**Comment by mebigfatguy** [comment]
ah sloppy reading on my part. should be fixed in HEAD. Thanks, again, for the report!

**Comment by pmayweg** [comment]
Thank you for the fast fix, May I ask, when you plan to roll the next release?

**Comment by pmayweg** [comment]
I can confirm, that it is fixed in HEAD.

**Comment by mebigfatguy** [comment]
7.0.5 has been released to maven
