### ISSUE TITLE
Add a new check - SLF4J logger being used with String.toString

### ISSUE THREAD

**Issue by aaron-haskins** [mebigfatguy/fb-contrib#235]
[SLF4J logger](https://www.slf4j.org/faq.html#string_contents) will invoke _complexObject.toString()_ method only after it has ascertained that the log statement was enabled:

    logger.debug("{}", complexObject);

But this code invokes _toString()_ regardless of the logger level set:

    logger.debug("{}", complexObject.toString());

fb-contrib should have a check if a method attempts to use an SLF4J logger with _toString()_.

**Example:**

    public void doSomething() {
        Object complexObject = new Bar();
        logger.debug("{}", complexObject.toString());  // toString() should be detected by fb-contrib
    }

    private class Bar {
        private String value = "abc";

        @Override
        public String toString() {
            System.out.println("toString() invoked");
            return value;
        }
    }

If the logger level is set to INFO, the _toString()_ is still being invoked, but nothing is being logged.

**Comment by mebigfatguy** [comment]
Thanks for the idea! should be easily doable.

**Comment by mebigfatguy** [comment]
Thanks again for the idea. should be available in HEAD

**Comment by aaron-haskins** [comment]
I can confirm it works now

`[INFO] Method com.example.Foo.doSomething() explicitly calls toString90 on a logger parameter [com.example.Foo] At Foo.java:[line 12] LO_TOSTRING_PARAMETER`

I noticed there is a typo "toString90", can you have a look at it?
_etc/messages.xml_ line 4122

Thank you.
