### ISSUE TITLE
UCPM_USE_CHARACTER_PARAMETERIZED_METHOD false positive

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#236]
```java
public static final String SOME_CONSTANT = "a";

...

builder.append(SOME_CONSTANT);
```

I don't think this should output that warning.

**Comment by mebigfatguy** [comment]
Are you saying it's because it's a static field? Yeah, that is a 'problem' with java byte code, that shows up in other places in findbugs. the issue is, when you look at the byte code for the method, you don't see at all that it is referencing that field. Because that field is static final, javac doesn't actually inject a GETSTATIC call into the bytecode but merely a LDC. So you have no idea that that string you just loaded came from a field.

**Comment by mebigfatguy** [comment]
i suppose i could collect all the values of all the static fields in the class, and when a LDC is called, look to see if that value loaded is present in a static field. that has two short comings:
1) you might be loading a value that is completely unrelated to the static field, and won't be reported
2) it won't find static fields loaded from other classes.

**Comment by ThrawnCA** [comment]
Theoretically, the warning of "all is not optimal" is correct. Given that you know the constant value is a single character, it would be possible to store a second (private?) constant of type `char`. It's just that the miniscule performance gain is not typically worth it.

**Comment by mebigfatguy** [comment]
Hmm, after a bit more digging, there isn't even a field present, nor static initializer to initialize that field, so it seems i'm out of luck. Can't fix. sorry.

**Comment by mebigfatguy** [comment]
Not that you want to hear this, but if you change your code to

    public static final String SOME_CONSTANT;

    static {
        SOME_CONSTANT = "a";
    }

the problem will go away.

**Comment by ThrawnCA** [comment]
Perhaps this could be submitted to Oracle as a compiler optimisation: when a constant string is being passed to a StringBuilder or StringBuffer, instead of replacing it with a literal string, use a literal `char`.

**Comment by boris-petrov** [comment]
Thank you both for the explanations! I think this:

```java
public static final String SOME_CONSTANT;

static {
    SOME_CONSTANT = "a";
}
```

is uglier than what I did and then you suggested: a `public static final char SOME_CONSTANT_CHARACTER = 'a';`. I guess I'll go with this. Thanks for the support! And have fun with Java 9. :)
