### ISSUE TITLE
LO_APPENDED_STRING_IN_FORMAT_STRING for Log4J?

### ISSUE THREAD

**Issue by adamzovits** [mebigfatguy/fb-contrib#237]
Hi! Is there a reason why LO_APPENDED_STRING_IN_FORMAT_STRING only checks SLF4J method calls and not Log4J log methods? We have a lot of those and it would be nice to have them checked. Or am I missing something? Thank you!

**Comment by mebigfatguy** [comment]
oversite. will add.

**Comment by mebigfatguy** [comment]
hopefully log4j2 support is up to the level of slf4j now. Thanks for the report.

**Comment by adamzovits** [comment]
Wow, that was fast! Thanks a lot!
