### ISSUE TITLE
SPP_USE_ISEMPTY false-positives

### ISSUE THREAD

**Issue by archmageirvine** [mebigfatguy/fb-contrib#238]
I'm seeing several examples of what I consider to be `SPP_USE_ISEMPTY` false-positives (although perhaps a matter of opinion).  These are situations where something needs to be done differently depending on whether or not a list or collection is empty, but one of the calculations involves the size of the list.  An example appears below.  While it is possible to rewrite these to use `isEmpty()` and `size()` that requires two method calls on the list rather than 1, so I think it is worse.

```
import java.util.List;

class A {

  void complicated(final int s) {
    assert s > 0;
    // do something complicated
  }

  int count(final List<List<Integer>> cycleStructure) {
    int total = 0;
    for (final List<Integer> cycle : cycleStructure) {
      final int size = cycle.size();
      if (size != 0) {
        complicated(size);
        total += size;
      }
    }
    return total;
  }
}
```

gives

```
A.java:13:13 SPP: Method A.count(List) checks the size of a collection against zero rather than using isEmpty() (M) 
```

I think there needs to be some kind of distinction between this type of use and the situation where the size is used purely for an `isEmpty()` check and nothing else.

**Comment by mebigfatguy** [comment]
Thanks for the report. I agree. -- should be fairly straightforward.

**Comment by mebigfatguy** [comment]
thanks again. i believe that should fix it for you.

**Comment by benjamingouit** [comment]
I disagree. The method isEmpty() has a complexity of O(1) when size() could have one of O(n). It is better to check before with isEmpty() and call size() only if it is really required.
