### ISSUE TITLE
DMC_DUBIOUS_MAP_COLLECTION reports False Positive when iterate by entry set

### ISSUE THREAD

**Issue by agabrys** [mebigfatguy/fb-contrib#239]
FB-contrib 7.0.5.sb reports False Positive when iterate map by entry set:

![sonarqube-falsepositive](https://user-images.githubusercontent.com/10604335/31316823-7e5d41d6-ac35-11e7-92e9-d4a27aaeb9f8.png)

    public class DefaultValueToStringConverter extends AbstractValueToStringConverter {
        private final Map<Class<?>, ValueToStringConverter> converters;
        private final ValueToStringConverter fallback;

        public DefaultValueToStringConverter() {
            converters = new ConcurrentHashMap<Class<?>, ValueToStringConverter>();
            converters.put(Object[].class, new ArrayToStringConverter());
            converters.put(Collection.class, new CollectionToStringConverter());
            fallback = new ObjectToStringConverter();
        }

        /* ... */

        @Override
        public String convert2(final Object value) {
            for (final Map.Entry<Class<?>, ValueToStringConverter> entry : converters.entrySet()) {
                if (entry.getKey().isInstance(value)) {
                    return entry.getValue().convert(value);
                }
            }
            return fallback.convert(value);
        }
    }

I use SonarQube 6.5 with [Findbugs plugin 3.6.0](https://github.com/SonarQubeCommunity/sonar-findbugs) to execute analysis.

Class:
https://github.com/gabrysbiz/maven-plugin-utils/blob/develop/src/main/java/biz/gabrys/maven/plugin/util/parameter/converter/DefaultValueToStringConverter.java

Project:
https://github.com/gabrysbiz/maven-plugin-utils/

Build:
mvn clean package

**Comment by mebigfatguy** [comment]
What this detector is suspecting is that your code doesn't actually use any lookups, and so your data structure really could be simpler as some sort of List. Altho, that is complicated by the fact that you are using a **Concurrent**HashMap, which is probably a bug on the part of the detector, so will look into that.

**Comment by mebigfatguy** [comment]
actually, upon further review. Why is **converters** Concurrent? At least what's shown there is no need for that.

**Comment by agabrys** [comment]
I used `ConcurrentHashMap` class, because I like it 😉 It disallows to put `null` to the map instance and in my situation non-concurrent vs concurrent costs are very similar. I can use `HashMap` instead of `ConcurrentHashMap`, but I'm not sure if it is a correct way to fix false positives 😉

**Comment by mebigfatguy** [comment]
Well, really what the detector is saying is that you are using this like a `List<SomeBeanWithTwoFields>` or even` List<Pair<Class<?>, ValueToStringConverter>>` which is much simpler than a Map. If your case is simple, then by all means, ignore.

**Comment by agabrys** [comment]
Yes, you are right! I didn't see before that I can use a list with `Pair` objects. Thank you for help 👍
