### ISSUE TITLE
HES_EXECUTOR_NEVER_SHUTDOWN false positive

### ISSUE THREAD

**Issue by massfords** [mebigfatguy/fb-contrib#240]
The following snippet is triggering this rule:

```java
    private ExecutorService executorService;

    @Inject
    public MyClass(ExecutorService executorService) {
        this.executorService = executorService;
    }
```

This code is running within a CDI environment and is relying on the container to find and inject the ExecutorService needed here. Given that this code (MyClass) doesn't instantiate or start the ExecutorService, it shouldn't be responsible for stopping it on shutdown. FWIW, the owner of this ExecutorService has a PreDestroy annotation that handles the shutdown properly.

I can work around the false positive by changing the declaration to my own interface that extends ExecutorService since the rule is looking for exact class names.

**Comment by mebigfatguy** [comment]
Thanks for the report. i'll see what i can do

**Comment by mebigfatguy** [comment]
Thanks, should be fixed. i think the fact that it was @Injected is relatively unimportant. if the executor comes by way of a constructor parm, it's not this class's job to shut it down, it's the job of who ever created it.
