### ISSUE TITLE
COM_COPIED_OVERRIDDEN_METHOD false positive

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#241]
I have something like:

```java
class Foo {
  private static final String[] STRINGS = new String[] { "" };
  protected String[] getStrings() {
    return STRINGS;
  }
}

class Bar extends Foo {
  private static final String[] STRINGS = new String[] { "Bar's string" };
  @Override
  protected String[] getStrings() {
    return STRINGS;
  }
}
```

Which gives a `COM_COPIED_OVERRIDDEN_METHOD` which is wrong.

**Comment by mebigfatguy** [comment]
Thanks for the report. i've added example classes as seen above, but unfortunately i'm not seeing the problem with those, and wondering what i've done wrong.

**Comment by boris-petrov** [comment]
Hm, that's funny, I get the error on that exact example. I just put it in a file named `Foo.java` and it blows up. I'm using `SpotBugs 3.1.0` and `fb-contrib 7.0.5.sb`. The exact error is:

```
Method Bar.getStrings() is implemented with an exact copy of its superclass's method

Bug type COM_COPIED_OVERRIDDEN_METHOD (click for details)
In class Bar
In method Bar.getStrings()
At Foo.java:[line 14]
```

**Comment by mebigfatguy** [comment]
Ah... checking back, i think it's already fixed on HEAD, just hasn't been released yet. I'll do some more testing around this though.

**Comment by mebigfatguy** [comment]
ok, should be fixed in head, the right way. thanks for the report
