### ISSUE TITLE
New detector - Methods returning null should be annotated @Nullable

### ISSUE THREAD

**Issue by jiri-pejchal** [mebigfatguy/fb-contrib#242]
This is an idea for a new detector:
methods returning null should be annotated with an annotation named @Nullable.

Invalid code:
```
Date created;
    // failure: missing @Nullable
   public Date getCreated() {
        if (created == null) {
            return null;
        } else {
            return (Date) created.clone();
        }
    }
```
Valid code:
```
Date created;
   @Nullable
   public Date getCreated() {
        if (created == null) {
            return null;
        } else {
            return (Date) created.clone();
        }
    }
```

**Comment by mebigfatguy** [comment]
Hi george-007,

thanks for the idea.

the problems are

1) Which Nullable annotation? For instance jsr305 hasn't been approved, nor does it seem it ever will be.

2) For some people this will be useful, for a massive number of people this will be a be a big annoyance as there will likely to be 1000's of violations per code base.


Perhaps if there was a specific context where returning null is highly unexpected and it could be limited to those cases, that might be useful. say clone()? toString()? for example?

**Comment by jiri-pejchal** [comment]
1. Annotation with simple class name ``Nullable``

For exmaple spring uses
https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/lang/Nullable.java

or Spotbugs uses
https://github.com/spotbugs/spotbugs/blob/master/spotbugs-annotations/src/main/java/edu/umd/cs/findbugs/annotations/Nullable.java

2. Not everybody uses ``@Nullable``. But sometimes even bigger projects can start using it, e.g. spring: https://jira.spring.io/browse/SPR-15540 and it's not hard to disable the detector. Also the detector could have lower priority so people with default settings would not be affected.

The actual bug I'm trying to prevent was this:

method returned ``null``
```java
public String getCodeForNew(String code) {
  if (condition(code)) {
    // code
  } else return null;
}
```

and somebody used it like
```
int length = getCodeForNew(code).lenght();
```
and got the ``NullPointerException``.

If the method was annotated with ``@Nullable``, intellij idea code inspection would warn him that there could be  ``NullPointerException``.  Ideally static analysis tool like findbugs would prevent it during the ci build.

**Comment by jiri-pejchal** [comment]
Intellij idea understands several ``Nullable`` annotations, most of them are called ``Nullable``
![image](https://user-images.githubusercontent.com/1450087/33220730-c84cd696-d14a-11e7-8767-460894fcb273.png)

But ideally the ``@Nullable`` annotation would be than checked by finbugs/spotbugs.

**Comment by jiri-pejchal** [comment]
The ''@Nullable'' would also be useful for tools like Uber Nullaway https://github.com/uber/NullAway

**Comment by mebigfatguy** [comment]
well, it's a pretty trivial detector to write, so, i guess i can give it a try.

**Comment by jsotuyod** [comment]
You can always use `TypeQualifierApplications.getEffectiveTypeQualifierAnnotation` which uses the findbugs / spotbugs internal knowledge of nullness annotations, which supports Eclipse's, IntelliJ's and JSR-305. Spotbugs also supports Android's annotations AFAIK.

This is similar to what I did at https://github.com/Monits/findbugs-plugin/blob/master/src/main/java/jp/co/worksap/oss/findbugs/jsr305/nullness/UnknownNullnessDetector.java

In that scenario however, I reported on everything not explicitly documented, but doing so for nulls (and therefore assuming non-null by default) should be very easy.

Also of note... Assuming Java 8+, do we really want nullable values? Why not report such usages to favor `Optional` and related classes?

**Comment by mebigfatguy** [comment]
ok, an initial stab at it is in the repository. There are other things that can be done, like calling methods thru interfaces, etc. Going to close for now. feel free to reopen, if you find things wanting.

**Comment by ThrawnCA** [comment]
Can the new `CollectNullableMethodStatus` be folded into `AnnotationIssues`? Most of it is copy-pasted from there.

**Comment by ThrawnCA** [comment]
Also, can this detector ignore any methods annotated with `Override`? They are likely to be used in accordance with a superclass contract, so annotating them makes less sense.

**Comment by mebigfatguy** [comment]
The problem is they need to be run in different passes, and the first pass requires the detector to implement NonReportingDetector. Probably could inherit one from another, but not a big fan of that for visitors.

**Comment by mebigfatguy** [comment]
as for @Override, unfortunately that is only a source level annotation

**Comment by jiri-pejchal** [comment]
Is it useful to report missing ``@Nullable`` for lambda? I suggest ignoring return statements in lambda expressions. 

e.g.:
```java
        getModelProviderRegistry().register(
                "availabilityDateOverride", () -> {
                    if (globalConfiguration.getRuntimeMode() != RuntimeMode.PRODUCTION) {
                        return dataConfiguration.getDateForTimeChecksOverride();
                    }
                    return null;
                }
        );
```

This would be anonymous class version:
```java
        getModelProviderRegistry().register(
                "availabilityDateOverride", new ModelProvider() {
                    @Override
                    public Object provide() {
                        if (globalConfiguration.getRuntimeMode() != RuntimeMode.PRODUCTION) {
                            return dataConfiguration.getDateForTimeChecksOverride();
                        }
                        return null;
                    }
                }
        );
```

**Comment by jiri-pejchal** [comment]
Can ``org.springframework.lang.Nullable`` also be added to the list of Nullable annotations?
