### ISSUE TITLE
DMC_DUBIOUS_MAP_COLLECTION false positive when using equals and entrySet

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#243]
We use a custom Hamcrest matcher that takes and stores a Map argument. It uses `equals` to compare the map to one of the fields of the object being matched (so it has to be the actual map object), and it uses `entrySet` as part of outputting the matcher description (so it has to be declared as `Map` type). However, the DMC_DUBIOUS_MAP_COLLECTION thinks it could be replaced with a List.

    class UserArtifactsMatcher extends BaseMatcher<UserArtifacts> {
        private final String username;
        private final Map<String, List<String>> attributes;

        UserArtifactsMatcher(final String username, final Map<String, List<String>> attributes) {
            this.username = username;
            this.attributes = attributes;
        }

        @Override
        public boolean matches(Object o) {
            UserArtifacts artifacts = (UserArtifacts) o;
            return username.equals(artifacts.getUsername()) && attributes.equals(artifacts.getAttributes());
        }

        @Override
        public void describeTo(Description description) {
            description.appendText("username=").appendValue(username)
                .appendText("attributes=").appendValueList("[", ",", "]", attributes.entrySet());
        }
    }

**Comment by mebigfatguy** [comment]
thanks for the report, should be fixed.

**Comment by ThrawnCA** [comment]
Looks fixed, thanks :).
