### ISSUE TITLE
False positive on presizing collections when sourcing from Enumeration

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#247]
The PSC_PRESIZE_COLLECTIONS detector is firing when we create an ArrayList from an Enumeration:

    import java.util.ArrayList;
    import java.util.Collections;
    import java.util.Enumeration;
    import java.util.List;
    import javax.servlet.http.HttpServletRequest;

    public class TestPresizeWithEnumeration {

        public Enumeration<String> getHeaders(HttpServletRequest request, String name) {
            Enumeration<String> input = request.getHeaders(name);
            List<String> cleanValues = new ArrayList<String>();
            while (input.hasMoreElements()) {
                // our real code does complex filtering here
                cleanValues.add(input.nextElement());
            }

            return Collections.enumeration(cleanValues);
        }

    }

Since `Enumeration` doesn't have any method to determine the total number of elements, pre-sizing isn't actually possible here.

**Comment by mebigfatguy** [comment]
thanks for the report, hopefully that fixes it for you.

**Comment by ThrawnCA** [comment]
Can this also ignore lists assembled from `java.util.regex.Matcher` `find()` and `group()`?

**Comment by ThrawnCA** [comment]
Still hitting `PSC_PRESIZE_COLLECTIONS` on the following code:

    private static final Pattern REGEX_TXN = Pattern.compile("(<Txn>(.*?)</Txn>)");

    public List<String> getTransactions(String xml) {
        List<String> transactions = new ArrayList<String>();
        Matcher matcher = REGEX_TXN.matcher(xml.replaceAll("\n", ""));
        while (matcher.find()) {
            transactions.add(matcher.group());
        }
        return transactions;
    }

**Comment by mebigfatguy** [comment]
thanks for the report, i'm surprised this is firing as it should know about Pattern.find being difficult. i'll take a look
