### ISSUE TITLE
SEO_SUBOPTIMAL_EXPRESSION_ORDER false positive

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#248]
```java
if (a.b() != null && a.b().c) {
}
```

This gives a `SEO_SUBOPTIMAL_EXPRESSION_ORDER` warning while it shouldn't.

**Comment by mebigfatguy** [comment]
Thanks for the report!, should be fixed in HEAD

**Comment by boris-petrov** [comment]
Thanks for the quick response! You have a billion issues fixed since 7.0.5, it would be nice to have a new release soon. :)
