### ISSUE TITLE
SPP_NON_USEFUL_TOSTRING false positive (maybe)

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#250]
FB Contrib version `7.2.0.sb`.

```java
public class A {
	public static class B extends A {
		private final A left;
		private final A right;

		@Override
		public String toString() {
			return '(' + left.toString() + ") and (" + right + ')';
		}
	}
}
```

Something like this gives a `SPP_NON_USEFUL_TOSTRING`. Technically it is correct, as `left` and `right` could be of type `A` and not have a useful `toString`, however most likely the user's intention was that they are of type `B` (as is my case - I also have `C`, `D`, etc which extend `A`). I'll leave you to decide what to do but I think it might be considered as a false-positive.

**Comment by mebigfatguy** [comment]
If class A were abstract, I definitely would agree, and could easily fix it. (haven't tried that scenario, tho, maybe it doesn't report if A is abstract). 

Probably easiest is just to add a return "" toString for A

**Comment by boris-petrov** [comment]
Yes, I actually tried making `A` abstract in our case, however we're also using it so I couldn't make it compile. Yes, a `toString` for `A` would work and I guess that's the best solution for now. I'll leave you to close the issue if you decide you're not going to invest time in it.

**Comment by mebigfatguy** [comment]
I will leave this open to try the abstract case. That should definitely not report, but i haven't tried it yet. As for your case, i don't think i can do anything about it.

**Comment by mebigfatguy** [comment]
seems to work correctly. am closing
