### ISSUE TITLE
AFBR_ABNORMAL_FINALLY_BLOCK_RETURN false positive

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#251]
Something like:

```java
private void do(String tempDir) throws IOException {
	Path temporaryDirectory = Files.createTempDirectory("name");

	try {
		// do stuff
	} finally {
		recursivelyDeleteDirectory(temporaryDirectory);
	}
}

private void recursivelyDeleteDirectory(Path path) throws IOException {
	Files.walk(path)
		.map(Path::toFile)
		.sorted(Comparator.reverseOrder())
		.forEach(File::delete);
}
```

Gives a `AFBR_ABNORMAL_FINALLY_BLOCK_RETURN`. I think it is wrong. FB Contrib version `7.2.0.sb`.

**Comment by mebigfatguy** [comment]
so you are saying that //do stuff can not throw an IOException? The point here is that really what the method expects is to validate what the try code is doing. If it were to throw an exception, by throwing in finally, you will obfuscate the problem of the try part.

Even if the main try code throws some RuntimeException, you'd want to really know that over what happens in the finally.

**Comment by boris-petrov** [comment]
Ah, I understand now. I've misunderstood what this warning does. Sorry about the confusion, all is fine here!
