### ISSUE TITLE
MapRef register field has inconsistent expectations

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#252]
Dogfooding on `MapUsageIssues` reports that the `MapRef.register` field is repeatedly checked for being >= 0 (in `hashCode` and `isValid`), but the `MapRef` constructor never actually allows it to be set to a negative value.

Should it be possible for this field to be negative?

**Comment by mebigfatguy** [comment]
Thanks, good catch. fixed
