### ISSUE TITLE
MUP_CONTAINSKEY_BEFORE_GET is questionable

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#253]
The `MUP_CONTAINSKEY_BEFORE_GET` is an inherently questionable check, since the documentation for Map explicitly allows using `containsKey` to distinguish between "key doesn't exist in the Map" vs "key is explicitly mapped to `null`".

fb-contrib itself uses this, in `MethodReturnsConstant.sawOpcode`, and follows a similar pattern in `PossibleMemoryBloat`  (though it *might* be able to use just `get` in the latter case).

**Comment by mebigfatguy** [comment]
Yes, altho as the bug info states, one should really use a sentinel value, and not null to disambiquate that case. I'll fix the fb-contrib usages.

**Comment by ThrawnCA** [comment]
Looks like that fixes it :)
