### ISSUE TITLE
UAC_UNNECESSARY_API_CONVERSION_FILE_TO_PATH it must be Paths not Path

### ISSUE THREAD

**Issue by ChristianLutz** [mebigfatguy/fb-contrib#256]
Hello,

I just saw a small typo for the UAC_UNNECESSARY_API_CONVERSION_FILE_TO_PATH details.

Currently it says `... {@code Path.get(String...)}.`  but correct is `...{@code Paths.get(String...)}.`.

**Comment by mebigfatguy** [comment]
Thanks for the report! fixed.
