### ISSUE TITLE
Optional.empty should not trigger RMC_POSSIBLY_REDUNDANT_METHOD_CALLS 

### ISSUE THREAD

**Issue by efenderbosch** [mebigfatguy/fb-contrib#259]
```java
if (foo == null) return Optional.empty();

Optional<Something> maybeSomething = doSomeWork();
if (!maybeSomething.isPresent()) return Optional.empty();
// continue doing other stuff
```

The 2nd Optional.empty is triggering RMC_POSSIBLY_REDUNDANT_METHOD_CALLS

fb-contrib version 7.2.0 w/ findbugs-maven-plugin version 3.5.0 running maven 3.5.2

I recently installed Java 9, so maybe that's the problem? I don't think we had the issue w/ Java 8.

**Comment by efenderbosch** [comment]
Ok, I uninstalled Java 9 and installed Java 8 and this went away.

Close if you want, but there might be more Java 9 issues.

**Comment by mebigfatguy** [comment]
i have no clue why java 9 would be different than 8. one thing i did realize is that i should clear out the list of called methods across returns statements, which may fix your problem, but if not i guess i'll have to install java 9, and give it a go.

**Comment by mebigfatguy** [comment]
if you get the chance, give that a go, reopen if need be, thanks!
