### ISSUE TITLE
UTAO_JUNIT_ASSERTION_ODDITIES_NO_ASSERT should work with custom assertion methods?

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#261]
I am getting:

JUnit test method org.spf4j.test.log.TestLoggerFactoryTest.testLogging33() appears to have no assertions [org.spf4j.test.log.TestLoggerFactoryTest] At TestLoggerFactoryTest.java:[lines 112-115] UTAO_JUNIT_ASSERTION_ODDITIES_NO_ASSERT

The unit test invokes a method where the name contains the word "assert" which should be supported based on the code at https://github.com/mebigfatguy/fb-contrib/blob/d3e90116c387d90c793c67f0c18d62a264dad110/src/main/java/com/mebigfatguy/fbcontrib/detect/UnitTestAssertionOddities.java#L380...

Here is my code that triggers this:

`  @Test
  public void testLogging33() {
    LogAssert expect = TestLoggers.config().expect("org.spf4j.test", Level.ERROR,
            Matchers.hasProperty("format", Matchers.equalTo("Booo")));
    expect.assertNotSeen();
  }`

**Comment by mebigfatguy** [comment]
i'm guessing expect.assertNotSeen() is defined by an interface.

**Comment by mebigfatguy** [comment]
thanks for the report
