### ISSUE TITLE
OC_OVERZEALOUS_CASTING false positive

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#262]
```java
public final class Reference<T> {
	public T value;

	public Reference(T value) {
		this.value = value;
	}
}

...

public Object getObject() {
	return "string";
}

Reference<String> test = new Reference<>(null);
test.value = (String) getObject();
```

The `test.value = ...` line gives a `OC_OVERZEALOUS_CASTING` warning which is wrong - the cast cannot be removed.

**Comment by mebigfatguy** [comment]
Thanks for the report! should be fixed in HEAD.

**Comment by boris-petrov** [comment]
Thanks for the quick support! A new release would be nice, it has been a long time since the last one. :)
