### ISSUE TITLE
AI_ANNOTATION_ISSUES_NEEDS_NULLABLE improvement...

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#264]
I am getting AI_ANNOTATION_ISSUES_NEEDS_NULLABLE for a method that returns Void like:

   @Override
    public Void handle(....) throws IOException {
   ....
    return null;
   }

is this really necessary? I find the type Void enough ....

**Comment by mebigfatguy** [comment]
Wow, i've literally never seen that before. :) Yes i can fix that.

**Comment by mebigfatguy** [comment]
(from Zoltan) Here is the method:

https://github.com/zolyfarkas/spf4j/blob/master/spf4j-core/src/main/java/org/spf4j/failsafe/DefaultRetryPredicate.java#L51

**Comment by mebigfatguy** [comment]
thanks for the report, should  be fixed in HEAD (7.2.2)
