### ISSUE TITLE
False positive: OCP_OVERLY_CONCRETE_PARAMETER overlooks overloading

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#270]
The `OCP_OVERLY_CONCRETE_PARAMETER` detector is firing in a situation where we have two overloaded constructors, whose arguments have a common superclass.

    public PaymentView(Order order) {
    ...
    public PaymentView(Statement statement) {
    ...

where `Order` and `Statement` both extend `Receiptable`.

The behavior of the two constructors is substantially different, so replacing them with a single constructor would not result in simpler code.

**Comment by mebigfatguy** [comment]
thanks for the report, yeah, that's  a bug on my part.

**Comment by mebigfatguy** [comment]
should be fixed.
