### ISSUE TITLE
MRC_METHOD_RETURNS_CONSTANT false positive when alternate code path is exception

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#271]
We're hitting `MRC_METHOD_RETURNS_CONSTANT` on a method that has only one return statement, but might instead throw an `UnsupportedOperationException` depending on the input.

    private String doPost() throws Exception {
        String response = wsClient.dispatch(credential, paymentData);
        CheckOutStatus status = CheckOutStatus.fromXml(response);

        if (status.isSuccess()) {
            redirectUrl = status.getRedirectUrl();
            return SUCCESS;
        }

        throw new UnsupportedOperationException(status.getError());
    }

This isn't exactly *elegant*, but it's not pointless either.

**Comment by mebigfatguy** [comment]
it's pretty silly to return any value here. i'm guessing the caller doesn't look at the return value. ... but ok, i'll ignore.

**Comment by ThrawnCA** [comment]
Eh, it's mostly for consistency with similar classes.
