### ISSUE TITLE
PMB_POSSIBLE_MEMORY_BLOAT does not consider iterators

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#276]
We have a map that is periodically cleaned up by iterating through its `entrySet` and calling `Iterator.remove` upon finding expired entries. According to the `Map` documentation, this is a correct approach to using `entrySet`. However, it seems that PMB_POSSIBLE_MEMORY_BLOAT only considers method calls on the map itself, not on derived iterators, so it still fires.

**Comment by mebigfatguy** [comment]
thanks, i'll take a look

**Comment by mebigfatguy** [comment]
thanks for the report, hopefully that should fix it.
