### ISSUE TITLE
MapUsageIssues.MapRef and SetUsageIssues.SetRef are duplicates

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#278]
While testing #276, I encountered the Copy-Paste Detector complaining of duplicate code in MapUsageIssues and SetUsageIssues. The implementations of MapRef and SetRef differ only in their class names, and they are static classes, so it seems likely that they could be extracted to a single class, perhaps named CollectionRef or similar.

**Comment by ThrawnCA** [comment]
`SetUsageIssues.Contains` and `MapUsageIssues.Get` are also very similar, with Contains being apparently a superset of Get, and `MapUsageIssues.ContainsKey` has a lot of similarities too. Perhaps there could be a common superclass for these?

**Comment by mebigfatguy** [comment]
i don't think the added complexity is worth the reduction in class count. If these classes take on a larger roll at some point, it's probably a good idea. As it stands now, they are tiny little inconsequential beasties that no one will care about.
