### ISSUE TITLE
False positive for  AI_ANNOTATION_ISSUES_NEEDS_NULLABLE 

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#284]
[INFO] Method x(Class clasz) that can return null, is missing a @Nullable annotation [C] At C.java:[lines 335-340] AI_ANNOTATION_ISSUES_NEEDS_NULLABLE

the code in questions is like:

    try {
      return clasz.newInstance();
    } catch (InstantiationException | IllegalAccessException e) {
      throw new RuntimeException(e);
    }

I believe this comes from the implementation of JDK Class.newInstance:

        // Run constructor
        try {
            return tmpConstructor.newInstance((Object[])null);
        } catch (InvocationTargetException e) {
            Unsafe.getUnsafe().throwException(e.getTargetException());
            // Not reached
            return null;
        }

which is a pretty bad implementation and should probably be:

        // Run constructor
        try {
            return tmpConstructor.newInstance((Object[])null);
        } catch (InvocationTargetException e) {
            Unsafe.getUnsafe().throwException(e.getTargetException());
            throw new IllegalStateException();
        }

probably worthwhile bringing this up to the JDK comunity if not already.

**Comment by mebigfatguy** [comment]
Thanks, should be fixed
