### ISSUE TITLE
A checker that for unnecessary @SuppressFBWarnings ?

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#285]
It would be nice to have a checker for unnecessary SuppressFBWarnings  annotation uses.

the annotation is used mostly to work around false positives, but as those false positives get fixed in upcoming versions of FB, the code remains littered with useless suppression... wold be nice to eliminate them...

Additionally it would be nice to have a check for allowing only explicit use of @SuppressFBWarnings("CHECK...")... to force the devs to explicitly specify which check to ignore...

**Comment by mebigfatguy** [comment]
this probably should go to spotbugs issue tracker.   https://github.com/spotbugs/spotbugs/issues

**Comment by zolyfarkas** [comment]
done: https://github.com/spotbugs/spotbugs/issues/641
