### ISSUE TITLE
FII_USE_FUNCTION_IDENTITY false positive?

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#286]
I have this check firing up at:

  @Override
  public void put(final K key, final V value) {
    map.put(key, () -> value);
  }

where map is a ConcurrentMap<K, Callable<? extends V>> map;

I am not sure how can I use a identity function here since () -> value is not a identity function...

**Comment by mebigfatguy** [comment]
It's a false positive that I believe has already been  reported and fixed. Sorry for the confusion.

**Comment by mebigfatguy** [comment]
https://github.com/mebigfatguy/fb-contrib/issues/283

**Comment by mebigfatguy** [comment]
does 7.4.1 resolve this issue?

**Comment by nickantzoulis** [comment]
Yes, 7.4.1 resolves this issue.
