### ISSUE TITLE
FII_USE_METHOD_REFERENCE false positive?

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#287]
I have FII_USE_METHOD_REFERENCE firing for:

  static <T> TimedSupplier<T> fromSupplier(Supplier<T> supplier) {
       return (s, e) -> supplier.get();
  }

TimedSupplier is:

@FunctionalInterface
public interface TimedSupplier<T> {

  T get(long startTimeNanos, long deadlineNanos);

}

I am not sure how I can use method reference here.. supplier::get is not compat with T get(long startTimeNanos, long deadlineNanos) ... or there is a lambda feature that I am not aware of?...

**Comment by mebigfatguy** [comment]
i believe this is also fixed via https://github.com/mebigfatguy/fb-contrib/issues/282

i'll add your repository to the list of ones i test with, for future releases

**Comment by mebigfatguy** [comment]
does 7.4.1 resolve this issue?

**Comment by nickantzoulis** [comment]
Yes, 7.4.1 resolves this issue.
