### ISSUE TITLE
CE_CLASS_ENVY false positive?

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#288]
Method org.spf4j.jmx.ExportedValuesMBean.createAttributeInfo(ExportedValue) excessively uses methods of another class [org.spf4j.jmx.ExportedValuesMBean] At ExportedValuesMBean.java:[lines 301-316] CE_CLASS_ENVY

this does not make sense to me...

code is at: https://github.com/zolyfarkas/spf4j/blob/6e7c110a3f96426f70862401945d40e1a564df75/spf4j-core/src/main/java/org/spf4j/jmx/ExportedValuesMBean.java#L300

**Comment by mebigfatguy** [comment]
it's basically saying that the logic in the method createAttributeInfo has very little to do with the class ExportedValuesMBean, and much more to do with class ExportedValue. Basically ExportedValue has no control over what it's representation is as an MBean, do you want this, or should createAttributeInfo be part of ExportedValue.

whether or not you consider that to be accurate, is up to you.

**Comment by zolyfarkas** [comment]
Thanks, can something be done about the message? For me the message was very confusing...
Shouldn't it have been:

Method org.spf4j.jmx.ExportedValuesMBean.createAttributeInfo(ExportedValue) excessively uses methods of another class [org.spf4j.jmx.ExportedValue] At ExportedValuesMBean.java:[lines 301-316] CE_CLASS_ENVY

currently the message says the some method from class X uses excessively methods from the same class X...

**Comment by mebigfatguy** [comment]
unfortunately findbugs/spotbugs doesn't allow you to parameterized the message beyond 'this' class/method etc.
