### ISSUE TITLE
False positives in 7.4.1: AI_ANNOTATION_ISSUES_NEEDS_NULLABLE

### ISSUE THREAD

**Issue by davidburstromspotify** [mebigfatguy/fb-contrib#291]
```
import edu.umd.cs.findbugs.annotations.Nullable;

class MyWeirdClass {

    @Nullable
    private static Object create() {
        return Math.random() >= 0.5 ? new Object() : null;
    }

    // FALSE POSITIVE: AI_ANNOTATION_ISSUES_NEEDS_NULLABLE
    public Object create1() {
        Object t = create();
        if (t != null) {
            return t;
        } else {
            throw new RuntimeException();
        }
    }

    public Object create2() {
        Object t = create();
        if (t == null) {
            throw new RuntimeException();
        } else {
            return t;
        }
    }

    // FALSE POSITIVE: AI_ANNOTATION_ISSUES_NEEDS_NULLABLE
    public Object create1b() {
        Object t = create();
        if (t != null) {
            return t;
        } else {
            return new Object();
        }
    }

    // FALSE POSITIVE: AI_ANNOTATION_ISSUES_NEEDS_NULLABLE
    public Object create2b() {
        Object t = create();
        if (t == null) {
            return new Object();
        } else {
            return t;
        }
    }
}
```

**Comment by mebigfatguy** [comment]
i'm not sure i follow what you are trying to report. why did you put @Nullable on create?

**Comment by davidburstromspotify** [comment]
I've updated the example to make more sense. It appears as if `AnnotationIssues` does not correctly follow the execution path to determine if the object returned by `create()` is indeed nullable. In all of the false positives, the methods cannot return a null value, but are marked as such.

**Comment by mebigfatguy** [comment]
Thanks for the report, i believe these should be fixed in HEAD, for 7.4.2

**Comment by ThrawnCA** [comment]
@davidburstromspotify Why are you annotating with `@Nullable`, which is the equivalent of having no annotation at all, instead of `@CheckForNull`?

**Comment by davidburstromspotify** [comment]
@ThrawnCA `@Nullable` is not equivalent to no annotation. No annotation at all means that it's not stated whether or not the API should be able to return `null`, and @Nullable is explicitly stating that it is designed to return `null`.

**Comment by ThrawnCA** [comment]
@davidburstromspotify No, that is incorrect for `edu.umd.cs.findbugs.annotations.Nullable` at least, which is what your code sample uses. It may be true for `org.jetbrains.annotations.Nullable`.

See http://findbugs.sourceforge.net/manual/annotations.html for details of the FindBugs annotations. I quote,

    FindBugs will treat the annotated items as though they had no annotation.

    In practice this annotation is useful only for overriding an overarching NonNull annotation.

**Comment by davidburstromspotify** [comment]
Ah, that brings me back 5 years. We actually do not use the FB one for that very reason in our codebase but one derived from javax.annotation, which is correctly detected and used by FB. For the point of fb-contrib and the error I reported, it correctly detects any of the Nullable if present.
