### ISSUE TITLE
ACEM_ABSTRACT_CLASS_EMPTY_METHODS false positive?

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#293]
I have a AbstractRunnable class defined as:

 public abstract class AbstractRunnable implements Runnable {

with a static field:

  public static final Runnable NOP = () -> { };

I am getting:

Empty method org.spf4j.base.AbstractRunnable.lambda$static$0() could be declared abstract [org.spf4j.base.AbstractRunnable] At AbstractRunnable.java:[line 48] ACEM_ABSTRACT_CLASS_EMPTY_METHODS

which does not make much sense to me...

**Comment by mebigfatguy** [comment]
Thanks for the report, fixed by now skipping synthetic methods for ACEM.  target for 7.4.2
