### ISSUE TITLE
AI_ANNOTATION_ISSUES_NEEDS_NULLABLE is reported even when @Nullable added using`android.support.annotation.Nullable` 

### ISSUE THREAD

**Issue by superbgv** [mebigfatguy/fb-contrib#299]
Hello,
I am using  `findbugsPlugins 'com.mebigfatguy.fb-contrib:fb-contrib:7.4.2'`.
And getting lot of `AI_ANNOTATION_ISSUES_NEEDS_NULLABLE` in my Android code even when i added `@Nullable` using`android.support.annotation.Nullable`.

**Comment by mebigfatguy** [comment]
Thanks, merged.
