### ISSUE TITLE
Inaccurate documentation for LUI_USE_SINGLETON_LIST

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#303]
The documentation for LUI_USE_SINGLETON_LIST states that both `Collections.singletonList` and `Arrays.asList` produce immutable lists. However, this isn't actually the case. The result of `Arrays.asList` can be changed using the `set` method - you just can't change its size.

This semi-mutable behavior isn't something you should normally use, so the detector is quite right to recommend `singletonList` instead, but the docs should probably be updated.

**Comment by mebigfatguy** [comment]
Thanks for the report. Of course you are correct, and i have embellished the doc. As an aside, i don't think i've ever seen anyone use the set method (outside of homebrew sort algorithms typically in homework assignments).  And in that case, sorting a 1 element list won't have set called.
Aside over, thanks, updated!
