### ISSUE TITLE
[Feature request] Detector for large numbers not separated by _

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#304]
Java allows numbers like `1000000` to be written like `1_000_000` which is much more readable. A detector that warns about numbers that have more than 3 digits not separated by `_` would be nice.

**Comment by mebigfatguy** [comment]
I agree, however as findbugs runs on bytecode, I can't detect that. That could be done in PMD.

**Comment by boris-petrov** [comment]
Thanks, I opened a request with them. Thank you!
