### ISSUE TITLE
Enhancement: Ignore PRMC in the "if x not null then use x" pattern

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#305]
It's common to see code similar to:

    if (obj.getValue() != null) {
        return obj.getValue().toString();
    }

which triggers PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS. In this simple case, the value could be easily refactored into a local variable, but there can easily be more complicated cases that quickly become not worth it if `getValue` is cheap. Eg:

    if (successFlag && obj.getValue() != null) {

would have to become:

    if (successFlag) {
        SomeClass value = obj.getValue();
        if (value != null) {

Is it possible for fb-contrib to detect when the repeated method is a simple accessor? Or perhaps when the first call is a null check?

**Comment by mebigfatguy** [comment]
Thanks, bumped up the low bug criteria a little  bit to avoid simple getters, and added a configurable settings as with normal and high settings.
