### ISSUE TITLE
False positives/negatives: PCOA_PARTIALLY_CONSTRUCTED_OBJECT_ACCESS on private methods

### ISSUE THREAD

**Issue by davidburstromspotify** [mebigfatguy/fb-contrib#306]
Release 7.4.3:

There are unexpected PCOA_PARTIALLY_CONSTRUCTED_OBJECT_ACCESS false positives and negatives related to private final/non-final methods. See comments in the code snippet:

```
class Test1 {

    public Test1() {
        init(); // false positive, private methods cannot be overridden
    }

    private void init() {
        innerInit(); // true positive
    }

    protected void innerInit() {
    }
}

class Test2 {

    public Test2() {
        init(); // true negative, for the wrong reason
    }

    private final void init() {
        innerInit(); // false negative, misses overridable innerInit
    }

    protected void innerInit() {
    }
}

class Test3 {

    public Test3() {
        init(); // true positive
    }

    public void init() {
        innerInit(); // false negative, misses overridable innerInit
    }

    protected void innerInit() {
    }
}

class Test4 {

    public Test4() {
        init(); // true negative, for the right reason
    }

    public final void init() {
        innerInit(); // false negative, misses overridable innerInit
    }

    protected void innerInit() {
    }
}
```

**Comment by mebigfatguy** [comment]
Thanks for the report!

Ok, so running this class file i get a Bug fired on Test1's constructor with detail:

    Constructor new Test1() makes call to non-final method
    At Test1.java: (line 4)
    In method new Test1()
    At Test1.java (line 8)

that seems to be correct

and, a bug on Test3's constructor with detail:

    Constructor new Test3() makes call to non-final method
    At Test1.java: (line 32)
    In method new Test3()

which also seems right


I agree Test2, and Test4 are missed.

Am i understanding your bug report?

**Comment by mebigfatguy** [comment]
patched to find the problems in the chain from Test2 and Test4

give  head a shot, and see if this resolves the issues. Thanks!

**Comment by davidburstromspotify** [comment]
Thanks Dave, HEAD does indeed work properly!
