### ISSUE TITLE
New detector: Lambdas where method refs work

### ISSUE THREAD

**Issue by llogiq** [mebigfatguy/fb-contrib#310]
For example, say we want to add an IntStream to a BitSet:

```java
myBitset = new BitSet();
// detect this:
ints.forEach(i -> myBitSet.set(i));
// because it's easier written as:
ints.forEach(myBitSet::set);
```

**Comment by mebigfatguy** [comment]
yeah when i added this for calling no arg methods on the parm itself, i ignored this case.  i should add this. do you think it should be a different bug pattern from FII_USE_METHOD_REFERENCE ?

**Comment by llogiq** [comment]
No, FII_USE_METHOD_REFERENCE will do fine (I should add that I just noticed the missing case because we lint this in [rust-clippy](https://github.com/rust-lang-nursery/rust-clippy)).

**Comment by mebigfatguy** [comment]
let me know if that works for you
