### ISSUE TITLE
Hamcrest used with insufficient matchers

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#312]
Just tripped over a testing situation that perplexed me for a bit, until I realised what I was doing wrong.

The Hamcrest `Matchers.hasEntry` method has two forms, one of which takes two literals, and the other takes two `Matcher`s. However, it is entirely possible to call it with a literal and a matcher, eg `hasEntry("key", containsString("val")`, in which case it will use the literal version, look for the map to contain an actual `Matcher` object, and never match. What I should have done is turn them both into matchers: `hasEntry(is("key"), containsString("val")`.

From what I've seen of the existing detectors, it's probably quite straightforward to check for the `hasEntry` method being called with one Matcher and one non-Matcher?

**Comment by mebigfatguy** [comment]
likely so, i'll take a look

**Comment by mebigfatguy** [comment]
Would i make a separate detector for just hamcrest issues? of would i jam it into UnitTestAsssertionOddities? or?

**Comment by ThrawnCA** [comment]
*Technically* Hamcrest is not a testing library, it's a matching library. I haven't actually seen it used in any other context, but it could happen. So, it should probably be separate. In practice, though, it probably works quite similarly to patterns like UTAO_JUNIT_ASSERTION_ODDITIES_ACTUAL_CONSTANT, so it might make sense to detect it in the same class.

Are there other detectors that just say, "It looks like you're passing arguments incorrectly"?

(I suppose creating a separate detector would be an opportunity to use "HMO" as an acronym for Hamcrest Matcher Oddities ;) )

**Comment by mebigfatguy** [comment]
give that a try, let me know

**Comment by ThrawnCA** [comment]
Tried to test it, but couldn't build the latest fb-contrib version, because the OCP_OVERLY_CONCRETE_PARAMETER detector is giving false positives when dogfooding. Doesn't happen in 7.4.3.sb. I think maybe it's getting confused when a parameter has a parameterised type? For example, it complains that `ArrayBasedCollections::hasComparator` should use a List parameter, but it already *is* a List.

**Comment by mebigfatguy** [comment]
good catch. hopefully i've addressed the OCP...   I unfortunately had to do some history rewriting, so you may need to do another

git reset --hard HEAD~6
git pull
