### ISSUE TITLE
Use separate artifactId for spotbugs version

### ISSUE THREAD

**Issue by kemitix** [mebigfatguy/fb-contrib#313]
Dependency management tools regard `7.4.3` to be an upgrade from `7.4.3.sb`.

Given that the findbugs and spotbugs 'versions' of fb-contrib are essentially targetting different APIs, they should really have different `artifactId`s. This would also better align versioning with Semantic Versioning.

**Comment by mebigfatguy** [comment]
yeah you're right. i had assumed i'd just drop the findbugs versions after awhile, but then never could figure out when a good time was.

**Comment by mebigfatguy** [comment]
if you could review these changes to make sure i didn't fubar something, would be appreciated.

**Comment by mebigfatguy** [comment]
(i will have to update README.md and the the other docs once a split release goes out)

**Comment by ThrawnCA** [comment]
On that note, the README refers to an obsolete version of SpotBugs Maven Plugin.
