### ISSUE TITLE
UTAO_JUNIT_ASSERTION_ODDITIES_NO_ASSERT does not recognise MeanBean testing

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#314]
The MeanBean project (http://meanbean.sourceforge.net/) provides standard JavaBean testing, ensuring that getters/setters/equals/etc work properly. However, the UTAO_JUNIT_ASSERTION_ODDITIES_NO_ASSERT detector doesn't recognise `new org.meanbean.test.BeanTester().testBean(MyBean.class)` as a valid assertion for the purpose of unit testing.

**Comment by mebigfatguy** [comment]
ok, will see what i can do

**Comment by mebigfatguy** [comment]
thanks for the report. see if that solves it.
