### ISSUE TITLE
ITU_INAPPROPRIATE_TOSTRING_USE false-positive

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#316]
```java
import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.container.ContainerRequestFilter;
import javax.ws.rs.core.MediaType;

public class LoggingFilter implements ContainerRequestFilter {
	@Override
	public void filter(ContainerRequestContext requestContext) {
		if (requestContext.getMediaType().toString().startsWith(MediaType.APPLICATION_JSON)) {
		}
	}
}
```

This gives an `ITU_INAPPROPRIATE_TOSTRING_USE` warning which is wrong. The media type could be `application/json;charset=utf-8` so I *have* to check as a substring of the original media type and there is no other way to get it as a string except `toString`.

**Comment by ThrawnCA** [comment]
Yeah, I believe there's already an exception in the code for `java.util.UUID`, which similarly depends on `toString`.

**Comment by ThrawnCA** [comment]
Just took a look at https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/MediaType.html, and I can see it has `getType` and `getSubtype`. Aren't those enough?

    if (MediaType.APPLICATION_JSON_TYPE.getType().equals(requestContext.getMediaType().getType())
        && MediaType.APPLICATION_JSON_TYPE.getSubtype().equals(requestContext.getMediaType().getSubtype()) {

**Comment by boris-petrov** [comment]
Well, yes, I could do a `(mediaType.getType() + '/' + mediaType.getSubtype()).startsWith...` but... why? :)

**Comment by ThrawnCA** [comment]
Why use `startsWith` at all? If you just extract the components you want, then you can use `equals`.

The simplistic answer is probably "because you don't have to write an fb-contrib exception", with a slightly longer one being "because parsing the `toString` output isn't really the elegant way of doing it", and then there's "What if, someday, someone creates a MIME type of 'application/json2'?"

**Comment by boris-petrov** [comment]
OK, fair enough, I agree with you. Thank you for the discussion!
