### ISSUE TITLE
Detector suggestion: Inflater / Deflater without call to end()

### ISSUE THREAD

**Issue by Lonzak** [mebigfatguy/fb-contrib#318]
We had a huge memory leak in a third party lib we are using. It started with Java 8 (probably due to the change of the garbage collector). But also before it required a lot of memory. The reason was that the end() method of a zip deflater / inflater wasn't called. (or was only called when garbage collected) E.g.

Before version: 
```
Deflater compresser = new Deflater();
compresser.setInput(b);
compresser.finish();
compresser.deflate(output);
if (... && compresser.finished()) {
...
}
```

Fixed version:
```
 java.util.zip.Deflater compresser=null;
try {
	compresser = new Deflater(Deflater.BEST_COMPRESSION);
	compresser.setInput(b);
	compresser.finish();
	compresser.deflate(output);
	if (... && compresser.finished()) {
		...
	}
	else {...}
 }
finally {
	if(compresser!=null) {
	compresser.end();
	compresser=null;
}
```

The same goes for the Inflater...

**Comment by mebigfatguy** [comment]
interesting. i've never used the non stream variants. i'll see what i can do.

**Comment by Lonzak** [comment]
Yeah the stream variant is correct - in the close method `end()` is called. 

>  i'll see what i can do.

Highly appreciated! I would have done it myself but currently don't have the time. But lets keep this issue as a place holder and lets see who has time first...
