### ISSUE TITLE
False positive for OVERLY_CONCRETE_TYPE for package-local interface

### ISSUE THREAD

**Issue by ghost** [mebigfatguy/fb-contrib#321]
With FB-Contrib version 7.4.3.sb, I'm seeing:

```java
package com.semi_confidential

/*package-local*/
interface IFoo {
    void doIt();
}
```

```java
package com.semi_confidential

public class Foo implements IFoo {
    @Override
    public void doIt() {}
}
```

```java
package com.world

import com.semi_confidential.Foo;

public class Thing {
    public void someWork(Foo foo) { // <-- OVERLY_CONCRETE_TYPE?
        foo.doIt();
    }
}
```

trigger what looks like a false positive OVERLY_CONCRETE_TYPE for `Thing.someWork`, where the report suggests `Foo foo` can be replaced with `IFoo`:

> OCP | 1st parameter 'foo' could be declared as com.semi_confidential.IFoo instead
>
> Bug type OCP_OVERLY_CONCRETE_PARAMETER (click for details) In class com.world.ThingIn method com.world.Thing.someWork(Foo)At Thing.java:[line 7]Value 1st parameter 'foo' could be declared as com.semi_confidential.IFoo instead

![screenshot 2018-12-13 at 14 51 18](https://user-images.githubusercontent.com/291757/49946307-a3de7b00-fee6-11e8-8664-4aebd6128d87.png)

However `IFoo` doesn't have enough visibility to oblige this.

**Comment by ThrawnCA** [comment]
Why are you making an interface less visible than the class implementing it? Especially when you're actually accessing the class via the interface method.

It's true that the parameter couldn't be changed to `IFoo` in this case, but it seems to me like that only arises because the code is doing things that should not be done, so the detector isn't fundamentally wrong to flag it.

**Comment by mebigfatguy** [comment]
Thanks for the report! While i agree with ThrawnCA that it seems kind of dubious to do this, there's no harm in ignoring such cases,

**Comment by ThrawnCA** [comment]
This actually highlights another potential detector: calling a method that is defined by an interface, where the interface would not be visible to the caller.
