### ISSUE TITLE
PCOA false positive when compiling with JDK 11

### ISSUE THREAD

**Issue by rubenlop88** [mebigfatguy/fb-contrib#325]
Fb-contrib version: 7.4.3.sb

Steps to reproduce:

Create a maven project with the following configuration:

```
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.0</version>
        <configuration>
          <!--<source>8</source> This works -->
          <!--<target>8</target> This works -->
          <release>11</release><!-- This doesn't work -->
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.github.spotbugs</groupId>
        <artifactId>spotbugs-maven-plugin</artifactId>
        <version>3.1.9</version>
        <configuration>
          <plugins>
            <plugin>
              <groupId>com.mebigfatguy.fb-contrib</groupId>
              <artifactId>fb-contrib</artifactId>
              <version>7.4.3.sb</version>
            </plugin>
          </plugins>
        </configuration>
        <executions>
          <execution>
            <phase>compile</phase>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```
Create a class:

```
public class Test {
  public Test() {
    init();
  }
  private void init() {
  }
}
```
Running `mvn compile` results in the error:

`[ERROR] Constructor new Test() makes call to non-final method [Test] At Test.java:[line 4] PCOA_PARTIALLY_CONSTRUCTED_OBJECT_ACCESS`

Which is not correct because `init()` is `private`

If I change the configuration to:

```
        <configuration>
          <source>8</source>
          <target>8</target>
          <!--<release>11</release> This doesn't work -->
        </configuration>
```

Everything works as expected.

**Comment by mebigfatguy** [comment]
can you please run

javap -v -private Test

in jdk11 and post the output here?

**Comment by boris-petrov** [comment]
@mebigfatguy 

```
Classfile /home/boris/Test.class
  Last modified Jan 10, 2019; size 250 bytes
  MD5 checksum ee6cb99b2c506492bae68759de40ab4f
  Compiled from "Test.java"
public class Test
  minor version: 0
  major version: 55
  flags: (0x0021) ACC_PUBLIC, ACC_SUPER
  this_class: #3                          // Test
  super_class: #4                         // java/lang/Object
  interfaces: 0, fields: 0, methods: 2, attributes: 1
Constant pool:
   #1 = Methodref          #4.#12         // java/lang/Object."<init>":()V
   #2 = Methodref          #3.#13         // Test.init:()V
   #3 = Class              #14            // Test
   #4 = Class              #15            // java/lang/Object
   #5 = Utf8               <init>
   #6 = Utf8               ()V
   #7 = Utf8               Code
   #8 = Utf8               LineNumberTable
   #9 = Utf8               init
  #10 = Utf8               SourceFile
  #11 = Utf8               Test.java
  #12 = NameAndType        #5:#6          // "<init>":()V
  #13 = NameAndType        #9:#6          // init:()V
  #14 = Utf8               Test
  #15 = Utf8               java/lang/Object
{
  public Test();
    descriptor: ()V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: aload_0
         5: invokevirtual #2                  // Method init:()V
         8: return
      LineNumberTable:
        line 2: 0
        line 3: 4
        line 4: 8

  private void init();
    descriptor: ()V
    flags: (0x0002) ACC_PRIVATE
    Code:
      stack=0, locals=1, args_size=1
         0: return
      LineNumberTable:
        line 6: 0
}
SourceFile: "Test.java"
```

I didn't test if the same file gives a warning on my side but I [opened an issue with many more problems on Java 11, one of which is the same as this one, so I guess it's also broken](https://github.com/mebigfatguy/fb-contrib/issues/330).

**Comment by mebigfatguy** [comment]
i don't see anything different between this and java 8 output, other than of course the major version. Odd. not sure what's the difference, then. I assume you are running SpotBugs in jdk11 too?

**Comment by boris-petrov** [comment]
Yep, JDK 11 is used for everything. OpenJDK specifically.

You can't reproduce it locally?

**Comment by lars-sh** [comment]
Same here:
* Unexpectedly receiving PCOA_PARTIALLY_CONSTRUCTED_OBJECT_ACCESS when having "validate();" call inside constructor. The method "validate" is private.
* Latest Maven release
* Running SpotBugs via Maven plugin
* I guess this does not really matter, but as previous commenters thought it might be: Maven is configured to compile Java 8 compatible

Tell me if you need more information.

**Comment by mebigfatguy** [comment]
finally see the diff, jdk uses
5: invokevirtual #2                  // Method init:()V
whereas jdk8 uses
5: invokespecial #2                  // Method init:()V

hopefully this fixes it.

**Comment by boris-petrov** [comment]
@mebigfatguy - do you mind releasing a new version soon? There seem to be a bunch of good stuff which is not released, especially this one here.

**Comment by mebigfatguy** [comment]
yeah, one change i've made is how findbugs/spotbugs support is done, there are new coordinates for spotbugs, rather than just a version number. I haven't really tested this  all that well, so i still need to do that. If you have time to test the spotbugs plugin and give see if you see any issues, would be appreciated.

**Comment by boris-petrov** [comment]
@mebigfatguy - sure, no problem, just point me to a maven repository with the new release/snapshot version and I'll try it out on our codebase.
