### ISSUE TITLE
Please drop dual releases (findbugs vs spotbugs)

### ISSUE THREAD

**Issue by hazendaz** [mebigfatguy/fb-contrib#328]
I think it is time to drop support for the original findbugs.  Some toolings such as dependabot are getting confused with dual versions being released.  Is the only real difference here jdk 8 vs earlier versions?  With jdk 11 out and 12 in March, baseline of anything really should be jdk 8 now.

**Comment by ThrawnCA** [comment]
The artifact IDs are splitting soon, not just version numbers; will that fix dependabot?

**Comment by hazendaz** [comment]
Yes that will also solve it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mebigfatguy** [comment]
as an FYI, downloads for the findbugs plugin dwarfs that of the spotbugs plugin at present. not sure why, but it is what it is.

**Comment by hazendaz** [comment]
@mebigfatguy I would expect that until everyone figures out the naming change.  It took quite some time for the spotbugs maven plugin to finally start to pick up.  It was averaging around 20k to 60k until this last month where it went to 140k.  Most of the major players are now picking up on the directional change.  I think that will probably take some level of time as well on the name change here given the prior naming also works since underlying it all is the same code.  I suspose more often than not the version string is all that is paid attention to and since the old one keeps incrementing, there will be a subset out there that never figures that out unless they run into issues and come directly to github and see.

**Comment by pzygielo** [comment]
Was https://maven.apache.org/pom.html#Relocation considered?
