### ISSUE TITLE
PMB_POSSIBLE_MEMORY_BLOAT shouldn't be reported for instances of WeakHashMap

### ISSUE THREAD

**Issue by jsotuyod** [mebigfatguy/fb-contrib#33]
Even if the collection is never explicitly being pruned of elements, they are getting removed when they can; and therefore won't cause a memory bloat.

It would be nice to filter this false positive.

**Comment by mebigfatguy** [comment]
agreed.. will attempt to fix.

**Comment by mebigfatguy** [comment]
hopefully 79a1c31.. fixes this

**Comment by jsotuyod** [comment]
Awesome work! Thanks for the quick response! Really appreciate this plugin.
