### ISSUE TITLE
Detector suggestion: JAXBContext.newInstance() without singleton

### ISSUE THREAD

**Issue by Lonzak** [mebigfatguy/fb-contrib#332]
We had a 2nd huge memory leak recently it it is about the usage of JAXB. The JAXB guys write it on their page, but we (and obviously lots of others) didn't read it.
https://javaee.github.io/jaxb-v2/doc/user-guide/ch03.html#other-miscellaneous-topics-performance-and-thread-safety

What's the problem? If you instantiate the JAXBContext without wrapping it into a singleton then there will be a memory leak. Emulate it:

while ( true ){
      JAXBContext jc = JAXBContext.newInstance( X.class );
      Unmarshaller unmarshaller = jc.createUnmarshaller();
      X object = (X) unmarshaller.unmarshal( new ByteArrayInputStream( XML.getBytes() ) );
      System.out.println( object.test );
}

Fix:
1.) Make it singleton if there is only one class
2.) Use a ConcurrentHashMap: http://www.scorgar.be/blog/lessons-learned-memory-leak-in-webservices-with-jaxb/

There are lots of threads about it:
https://stackoverflow.com/questions/7400422/jaxb-creating-context-and-marshallers-cost
https://stackoverflow.com/questions/33255578/old-jaxb-and-jdk8-metaspace-outofmemory-issue
https://stackoverflow.com/questions/3259291/do-i-have-a-jaxb-classloader-leak
https://stackoverflow.com/questions/33255578/old-jaxb-and-jdk8-metaspace-outofmemory-issue/42512885

**Comment by mebigfatguy** [comment]
quite interesting. I'm not sure i follow your your suggested fix. You're saying that this map would be class->Context?

Also i take it there's no 'close' operation for JAXBContext? The point is not to just create one-offs?
I guess an obvious take is if you grab a newInstance and store it in a local, that's a tip-off that there's a problem.

**Comment by mebigfatguy** [comment]
this finds the issue at least in a simple case. can embellish as needed. thanks for the suggestion.

**Comment by mebigfatguy** [comment]
(part of PMB)

**Comment by Lonzak** [comment]
*thumbs up* Sounds great - gonna test it later...
