### ISSUE TITLE
Some patterns could not be detected

### ISSUE THREAD

**Issue by ohryu** [mebigfatguy/fb-contrib#334]
Hi,
I'm using Findbugs 3.0.1 and fb-contrib-7.4.3. In Eclipse some patterns could not be detected such as 
ISB_INEFFICIENT_STRING_BUFFERING, SIL_SQL_IN_LOOP.
Ex: 
    StringBuilder str = new StringBuilder();
    str.append(str1 + str2);

The InefficientStringBuffering bug should be seen at the second line but it's not.

**Comment by mebigfatguy** [comment]
is str1 and str2 constants? If so the compiler is probably combining for you. If you could paste the javap -v output for that method that would be great.

**Comment by ohryu** [comment]
Here is javap output: 
[text.txt](https://github.com/mebigfatguy/fb-contrib/files/2853954/text.txt)

str1 and str2 are arguments of the method.

public String concatString(String str1, String str2) {
     StringBuilder str = new StringBuilder();
     str.append("Result: "+str1 + str2);
     return str.toString();
}

I also tried passing constants in append method but still not work.

**Comment by mebigfatguy** [comment]
thanks, ok, i would think that should fire. i'll take alook

**Comment by mebigfatguy** [comment]
Thanks for the report! Not sure why this stopped reporting, but hopefully is working now.
