### ISSUE TITLE
UVA_USE_VAR_ARGS is creating a false-positive with an anonymous class

### ISSUE THREAD

**Issue by nlongton-zz** [mebigfatguy/fb-contrib#338]
I have this code in a method - and i get 

package com.foo.java.core.security;
public class CoreSecurityManagerTest extends FooBase {

  @Test
  public void testCallbacks()  {
    final String[] callbacks = new String[]{"No", "No"};
    Function<Supplier<LoginContext>, Void> cb1 = new Function<Supplier<LoginContext>, Void>() {
      @Override
      @SuppressFBWarnings("CLI_CONSTANT_LIST_INDEX")
      public Void apply(final Supplier<LoginContext> loginContextSupplier) {
        callbacks[0] = "Yes";
        return null;
      }
    };

Method new com.foo.java.core.security.Foo1$1(CoreSecurityManagerTest, String[]) defines parameter list with array as last argument, rather than vararg [com.foo.java.core.security.CoreSecurityManagerTest$1] At CoreSecurityManagerTest.java:[line 45] UVA_USE_VAR_ARGS

Line 45 is 'Function<Supplier ...

I would have used a lambda but the CLI_CONSTANT_LIST_INDEX kicked in ...

Have i missed a trick here?
Using version 7.4.3.sb

Thanks
Nigel

**Comment by mebigfatguy** [comment]
the problem is it's complaining about the constructor which is
ex/UVA_Sample$1."<init>":(Lex/UVA_Sample;[Ljava/lang/String;)V

which of course is not under your control, so a false positive. I'm not sure why it's picking to use a String array to begin with, but i'll look into squashing that.

**Comment by mebigfatguy** [comment]
should be fixed... thanks for the report!

**Comment by nlongton-zz** [comment]
Dave
Thank you very much.
I’d like to use a lambda function in my example but I can’t set the suppress annotation close enough for comfort. Are there any alternate ways to suppress? Checkstyle allows for comments to do this as well

Cheers
Nigel

**Comment by mebigfatguy** [comment]
that would be a feature request for findbugs/spotbugs, i don't control that.

**Comment by nlongton-zz** [comment]
Understood.

Is it possible to get a release of fb-contrib with this fix in?

Thanks
Nigel
