### ISSUE TITLE
PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS  false positives with Instant.now()

### ISSUE THREAD

**Issue by zolyfarkas** [mebigfatguy/fb-contrib#339]
using Instant.now() in a method will trigger PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS

Instant.now()
....
Instant.now()

**Comment by nlongton-zz** [comment]
Other cases of this are static methods that return new objects eg:
   Foo f1 = Foo.newBuilder().setX(1).build();
   Foo f2 = Foo.newBuilder().setX(2).build();
This is in code we dont control too.

**Comment by ThrawnCA** [comment]
If it's in code you don't control, I wouldn't expect Spotbugs to be scanning it. How are you running it?

The Instant.now call should be whitelisted, though; thanks for identifying it.
