### ISSUE TITLE
Circular Depenency detector Falsely reporting builder pattern

### ISSUE THREAD

**Issue by christopherpicard** [mebigfatguy/fb-contrib#34]
Findbugs is falsely reporting a CD_CIRCULAR_DEPENDENCY when a class implements the Builder pattern.

Here is a sample class that gets flagged as having a circular dependency between the User class and the Builder class.

```
import java.io.Serializable;
import java.util.UUID;
import jdk.nashorn.internal.ir.annotations.Immutable;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/*
* A user represents any user of the system. This object is for tracking which user is tied to a specific object and is not
* intended to provide login validation.
*
* @author Chris Picard, chris.s.picard@gmail.com
* @version 1.0.0
/
@Immutable
public final class User implements Serializable {
private static final long serialVersionUID = 1L;
private final UUID userId;
private final String firstName;
private final String lastName;

@SuppressWarnings("synthetic-access")
private User(final Builder builder) {
this.userId = builder.userId;
this.firstName = builder.firstName;
this.lastName = builder.lastName;
}

public UUID getUserId() {
return userId;
}

public String getFirstName() {
return firstName;
}

public String getLastName() {
return lastName;
}

@Override
public int hashCode() {
final HashCodeBuilder builder = new HashCodeBuilder();
builder.append(userId);
builder.append(firstName);
builder.append(lastName);
return builder.toHashCode();
}

@Override
public boolean equals(final Object obj) {
if (this == obj) {
return true;
}
if (obj == null) {
return false;
}
if (getClass() != obj.getClass()) {
return false;
}
final User other = (User) obj;
final EqualsBuilder builder = new EqualsBuilder();
builder.append(this.userId, other.userId);
builder.append(this.firstName, other.firstName);
builder.append(this.lastName, other.lastName);
return builder.isEquals();
}

@Override
public String toString() {
return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
}

/*
* Implementation of the builder pattern.
*
* @author Chris Picard, chris.s.picard@gmail.com
* @version 1.0.0

/
public static final class Builder {
private UUID userId;
private String firstName;
private String lastName;

  public Builder setValues(final User user) {
     this.userId = user.getUserId();
     this.firstName = user.getFirstName();
     this.lastName = user.getLastName();
     return this;
  }

  public Builder setUserId(final UUID userId) {
     this.userId = userId;
     return this;
  }

  public Builder setFirstName(final String firstName) {
     this.firstName = firstName;
     return this;
  }

  public Builder setLastName(final String lastName) {
     this.lastName = lastName;
     return this;
  }

  @SuppressWarnings("synthetic-access")
  public User build() {
     if (userId == null) {
        userId = UUID.randomUUID();
     }
     if (StringUtils.isEmpty(firstName)) {
        throw new IllegalStateException("First name is not set");
     }
     return new User(this);
  }
}
}

**Comment by ThrawnCA** [comment]
That's not how the Builder pattern is supposed to work. User isn't supposed to know about Builder. User should have a constructor that accepts the individual parameters (userId, firstName, lastName), instead of accepting a Builder.

The way you have things set up, it's impossible to construct a User directly; you *have* to create a Builder first. That shouldn't be the case.

(By the way, the parameter validation should happen inside User, too).

**Comment by mebigfatguy** [comment]
Or builder should have a build () method that constructs a user and sets fields on it

**Comment by jsotuyod** [comment]
Actually, that implementation is perfect. Read Effective Java, 2nd edition, item 2

http://www.google.co.th/url?sa=t&rct=j&q=effective+java&source=web&cd=8&cad=rja&uact=8&ved=0CFQQFjAH&url=http%3A%2F%2Fuet.vnu.edu.vn%2F~chauttm%2Fe-books%2Fjava%2FEffective.Java.2nd.Edition.May.2008.3000th.Release.pdf&ei=V2xmVcWoMsK7uATbmYLwDw&usg=AFQjCNHaTVJ7cBfChZStN4QTEuewWLo98Q

**Comment by jsotuyod** [comment]
Probably, the best would be to ignore CD when it concerns inner classes (either static or not). After all, being an inner class, they are already tightly coupled and the CD report adds little value.

**Comment by christopherpicard** [comment]
I agree with Jsotuyod that this check should not apply to inner classes. I am sure there are other cases other than the builder pattern that this check falsely reports.

As far as the other comments about the builder pattern, the whole point of the pattern is to ensure that you always have a fully populated object. It is used a lot when creating immutable objects like this one rather than requiring large number of constructor arguments which is bad practice in both Clean Code and Effective Java.

**Comment by mebigfatguy** [comment]
anon classes are already not reported. I will extend to all inner -that's fine.

Point of nore tho, imo, User shouldn't know about the builder class.

**Comment by ThrawnCA** [comment]
Well, it's correct that the Builder pattern as implemented matches Effective Java. That's not the same thing as being "perfect". I would still put it to you that it would be better for the constructor to accept individual arguments, and have the Builder provide them all.

But I also agree that it makes sense to drop the CD check for all inner classes.

**Comment by jsotuyod** [comment]
What is the status of this? Need any help?

**Comment by mebigfatguy** [comment]
sorry, kind of forgot about this. I thought i had fixed this, and running this class, seems like it is not reported now, so... still broken for you?

**Comment by jsotuyod** [comment]
Truth be told, I haven't checked. I'm preparing for next week's "week of linting" at the office, trying to come up with a nice colection of things to do on tools such as FindBugs, fb-contrib, PMD, Checkstyle, and our [findbugs-plugin](https://github.com/Monits/findbugs-plugin) and came accross this issue still being open and thought it might be a good fit.

I just checked it and it seems to be gone, so this one could be closed.

If you have anything you think may be interesting for us to help you on, feel free to contact me directly. Thanks!
