### ISSUE TITLE
FII_USE_METHOD_REFERENCE false-positive

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#342]
```java
	public static void foo(Consumer<Void> consumer) {
	}

	public static void bar(Runnable runnable) {
		foo(_unused -> runnable.run());
	}
```

This code gives a `FII_USE_METHOD_REFERENCE` warning which is wrong as the call to `foo` in `foo(_unused -> runnable.run());` cannot be written as `foo(runnable::run);`

**Comment by ThrawnCA** [comment]
Why would you have a Consumer for Void?

**Comment by mebigfatguy** [comment]
I believe that should fix your issue. thanks for the report.

**Comment by boris-petrov** [comment]
@ThrawnCA - it's just an example, of course, not sensible code. :)

@mebigfatguy - thanks for fixing it so quickly!

**Comment by boris-petrov** [comment]
@mebigfatguy - I just tried this and as far as I can tell from the code, this is fixed only for `Void`. But, as I mentioned above, this was just an example. This should work for *any* type. In my case, the `Consumer` is of type `Throwable`. So again, this rule should handle any type.

Please reopen or just straight fix it. :) Thanks!

**Comment by boris-petrov** [comment]
@mebigfatguy - ping. :)
