### ISSUE TITLE
OCP_OVERLY_CONCRETE_PARAMETER Enum java 12 False positive?

### ISSUE THREAD

**Issue by dellgreen** [mebigfatguy/fb-contrib#344]
In spotbugs 7.43.sb and above spotbugs complians about OCP_OVERLY_CONCRETE_PARAMETER when passing an Enum as a parameter to a method.
In Java12 Constable interface was added to Enums. Not sure if this is desired behaviour.

**Comment by mebigfatguy** [comment]
thanks for the report.. it's odd because enum parms shouldn't be checked, currently, but anyway i've added Constable as a interface not to track.

**Comment by dellgreen** [comment]
awesome, thanks :)
