### ISSUE TITLE
Release 7.4.5.sb missing from maven central

### ISSUE THREAD

**Issue by zman0900** [mebigfatguy/fb-contrib#346]
7.4.5.sb is listed on the releases page, but only the plain 7.4.5 version is in maven central.

**Comment by ThrawnCA** [comment]
That's because the coordinates for the SpotBugs-compatible version have changed to `com.mebigfatguy.sb-contrib:sb-contrib`.

https://mvnrepository.com/artifact/com.mebigfatguy.sb-contrib/sb-contrib
