### ISSUE TITLE
Enforcing collections be non-null

### ISSUE THREAD

**Issue by efenderbosch** [mebigfatguy/fb-contrib#349]
I'd like to enforce that collections in our domain objects be non-null.

```
public class Order {
    // if this isn't initialized, flag it
    private List<LineItem> lineItems = new ArrayList<>();

    // if this isn't tagged w/ @Nonnull, flag it
    @Nonnull
    public List<LineItem> getLineItems() {
       return lineItems;
    }

    // if this isn't tagged w/ @Nonnull, flag it
   public void setLineItems(@Nonnull List<LineItems> lineItems) {
        this.lineItems = lineItems;
    }
}
```

Is this something that would make a good fb-contrib check? Or be more appropriate for checkstyle?

I'm willing to do the work to write the detector, but not sure if this is something that either project would like contributed, or would be more appropriate for our internal checks.

**Comment by ThrawnCA** [comment]
Maybe a PMD rule, actually.

**Comment by efenderbosch** [comment]
I didn't realize there was another tool for this.

https://pmd.github.io/pmd-6.15.0/pmd_rules_java.html

I don't see one there for this condition, though.

**Comment by ThrawnCA** [comment]
No, there's no PMD rule for this that I know of, but PMD might be the better tool for writing a custom rule.

**Comment by efenderbosch** [comment]
Custom PMD rule implemented. Thanks for the heads up.

**Comment by efenderbosch** [comment]
One issue I found w/ the PMD implementation. I can't inspect the parent Interface to see if it is tagged w/ @Nonnull, so each implementing method also needs the annotation.
