### ISSUE TITLE
Is ISB_EMPTY_STRING_APPENDING really slower?

### ISSUE THREAD

**Issue by amaembo** [mebigfatguy/fb-contrib#35]
~~~~
This method concatenates an empty string with a literal value,
in order to convert the literal value into a string. It is more efficient
to use String.valueOf() to do the same thing as you do not incur
the cost of creating a StringBuffer/Builder and calling methods
on it to accomplish this.
~~~~

I profiled the String.valueOf(x), new Integer(x).toString(), Integer.toString(x) and ""+x on Java 1.8.0.31. First three methods produce the same speed which was expected as Hotspot C2 JIT compiler is smart enough to get rid of extra Integer object and inline these calls. However it was complete surprise for me to discover that (""+x) is about 1.5x faster! You may probably want to test by yourself.

**Comment by amaembo** [comment]
For your reference here's quite lame benchmark test:

~~~~java
public class ToStringTest {
	public static String toString1(int i) {
		return String.valueOf(i);
	}

	public static String toString2(int i) {
		return new Integer(i).toString();
	}

	public static String toString3(int i) {
		return Integer.toString(i);
	}

	public static String toString4(int i) {
		return ""+i;
	}
	
	public static void main(String... args) {
		{
			long res = 0;
			long sum = 0;
			for(int i=0; i<100; i++) {
				long t = System.nanoTime();
				for(int j=0; j<1000000; j++) {
					res+=toString4(j).length();
				}
				long t2 = System.nanoTime();
				sum+=(t2-t);
			}
			System.out.printf("\"\"+i: %.2f ms\n", sum/100.0/1000000);
		}
		{
			long res = 0;
			long sum = 0;
			for(int i=0; i<100; i++) {
				long t = System.nanoTime();
				for(int j=0; j<1000000; j++) {
					res+=toString1(j).length();
				}
				long t2 = System.nanoTime();
				sum+=(t2-t);
			}
			System.out.printf("String.valueOf(i): %.2f ms\n", sum/100.0/1000000);
		}
		{
			long res = 0;
			long sum = 0;
			for(int i=0; i<100; i++) {
				long t = System.nanoTime();
				for(int j=0; j<1000000; j++) {
					res+=toString2(j).length();
				}
				long t2 = System.nanoTime();
				sum+=(t2-t);
			}
			System.out.printf("new Integer(i).toString(): %.2f ms\n", sum/100.0/1000000);
		}
		{
			long res = 0;
			long sum = 0;
			for(int i=0; i<100; i++) {
				long t = System.nanoTime();
				for(int j=0; j<1000000; j++) {
					res+=toString3(j).length();
				}
				long t2 = System.nanoTime();
				sum+=(t2-t);
			}
			System.out.printf("Integer.toString(i): %.2f ms\n", sum/100.0/1000000);
		}
	}
}
~~~~

The typical output I oberve is the following:

~~~~
""+i: 20,09 ms
String.valueOf(i): 33,54 ms
new Integer(i).toString(): 33,89 ms
Integer.toString(i): 34,23 ms
~~~~

**Comment by mebigfatguy** [comment]
Here's a class

public class IntToString {	
	public String toString1(int x) {
		return String.valueOf(x);
	}	
	public String toString2(int x) {
		return x + "";
	}
}

and here's the javap for the two methods

 public java.lang.String toString1(int);
    descriptor: (I)Ljava/lang/String;
    flags: ACC_PUBLIC
    Code:
      stack=1, locals=2, args_size=2
         0: iload_1
         1: invokestatic  #16                 // Method java/lang/String.valueOf:(I)Ljava/lang/String;
         4: areturn
      LineNumberTable:
        line 6: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   LIntToString;
            0       5     1     x   I

  public java.lang.String toString2(int);
    descriptor: (I)Ljava/lang/String;
    flags: ACC_PUBLIC
    Code:
      stack=3, locals=2, args_size=2
         0: new           #24                 // class java/lang/StringBuilder
         3: dup
         4: iload_1
         5: invokestatic  #16                 // Method java/lang/String.valueOf:(I)Ljava/lang/String;
         8: invokespecial #26                 // Method java/lang/StringBuilder."<init>":(Ljava/lang/String;)V
        11: invokevirtual #29                 // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
        14: areturn
      LineNumberTable:
        line 10: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      15     0  this   LIntToString;
            0      15     1     x   I


Notice that the second method is a complete superset of the first method. (They both call String.valueOf, the second just creates and plays with a StringBuilder.)

**Comment by amaembo** [comment]
Hah, sure, I know. I can run javap by myself. But what is actually executed on CPU may differ very much from Java bytecode. Seems that here JIT compiler is smart enough to remove StringBuilder completely. You cannot measure performance just by looking into the bytecode.

Well probably this warning is relevant for low-quality virtual machines like ones which appear on some smartphones, but not for Hotspot. You may close this issue, I just wanted to point your attention to the fact that real performance may differ significantly from what you can guess simply looking on the bytecode.

**Comment by mebigfatguy** [comment]
Yes, but you are suggesting the JIT takes code that has instructions A, B and C and makes it faster then code that only has instruction B. Given that both methods have instruction B how does that happen.

**Comment by amaembo** [comment]
Well, I can copy-paste assembler dumps of JIT-generated methods, but I'm not a low-level programming professional to explain this in detail. Sometimes even executing more CPU instructions is faster than executing less. For example, there are cases described in literature (read Agner Fog) when adding a couple of NOPs or completely useless jump to the next instruction makes the loop faster by 10 CPU cycles or so (just because branch prediction works better thanks to useless instructions). Here not only CPU, but JIT compiler is present which makes the behavior even less predictable. So the only way to determine the speed of the code is to profile it.

**Comment by mebigfatguy** [comment]
ok

public class Timer {

	public static void main(String[] args) {
		
		for (int i = 0; i < 10; i++) {
			valueOf();
			plus();
		}
	}
	
	public static void valueOf() {
		long start = System.nanoTime();
		for (int i = 0; i < 100000; i++) {
			String s = String.valueOf(i);
		}
		long end = System.nanoTime();
		System.out.println("valueOf " + (end - start));
	}
	
	public static void plus() {
		long start = System.nanoTime();
		for (int i = 0; i < 100000; i++) {
			String s = i + "";
		}
		long end = System.nanoTime();
		System.out.println("plus " + (end - start));
	}
}

valueOf 21056695
plus 48199465
valueOf 8610603
plus 51321884
valueOf 13184604
plus 25367741
valueOf 8505391
plus 34649462
valueOf 9981034
plus 36909821
valueOf 9687642
plus 43377317
valueOf 8835356
plus 27819122
valueOf 8340685
plus 22491052
valueOf 10319665
plus 46064280
valueOf 7487330
plus 26858210


java version "1.8.0_31"

**Comment by amaembo** [comment]
Interesting. My results on two PCs:

Core-i5 3.10GHz (x64)
~~~~
valueOf 9091490
plus 16259137
valueOf 4936903
plus 6452207
valueOf 3158731
plus 1531526
valueOf 2950819
plus 1439489
valueOf 2930955
plus 1448096
valueOf 2478052
plus 1420949
valueOf 2464810
plus 2228758
valueOf 2488647
plus 1468291
valueOf 2736949
plus 1421942
valueOf 2491295
plus 1446441
~~~~

Core i5 2.3GHz (x64)
~~~~
valueOf 44067088
plus 41918127
valueOf 8600306
plus 3947199
valueOf 3857510
plus 2327446
valueOf 3341242
plus 2505485
valueOf 4982412
plus 2398840
valueOf 3553639
plus 2305582
valueOf 3308222
plus 3788794
valueOf 3280557
plus 2377422
valueOf 3284573
plus 2335478
valueOf 3275202
plus 3370691
~~~~

I also installed 32bit Java (1.8.0.31) it shows the results similar to yours:

~~~~
valueOf 5462013
plus 11812953
valueOf 3330577
plus 7867908
valueOf 2981297
plus 6585668
valueOf 2754844
plus 6207917
valueOf 2867739
plus 6699888
valueOf 2489656
plus 5855988
valueOf 2545607
plus 5525578
valueOf 2473765
plus 5537828
valueOf 2458866
plus 5447447
valueOf 2470453
plus 5567625
~~~~

Are you using 32bit or 64bit?

**Comment by amaembo** [comment]
By the way I've found some clarification on this question in the following presentation from Oracle engineer:
https://youtu.be/YgGAUGC9ksk?t=10m00s

**Comment by mebigfatguy** [comment]
yes 32 bit, i have a crap azzed machine. You probably have a point, altho it's also probably transient.
