### ISSUE TITLE
DeletingWhileIterating produces false-negative

### ISSUE THREAD

**Issue by minshi123** [mebigfatguy/fb-contrib#352]
`void concurrentModificaitonExceptionTest(){
        ArrayList<Integer> list = new ArrayList<Integer>();
        list.add(2);
        Iterator<Integer> iterator = list.iterator();
        while(iterator.hasNext()){
            Integer integer = iterator.next();
                list.remove(integer);
        }
     }`

This detector(DeletingWhileIterating) has any examples(test-cases)?

**Comment by mebigfatguy** [comment]
Thanks for the report, should be fixed.

The issue was your variable 

    ArrayList<Integer> list

was defined as a class (ArrayList) vs an interface (List), which was something i wasn't accounting for here.
