### ISSUE TITLE
Incorrect cyclomatic complexity for string switches

### ISSUE THREAD

**Issue by joankaradimov** [mebigfatguy/fb-contrib#353]
I get a violation of the `CC_CYCLOMATIC_COMPLEXITY` rule with switch statements on strings. I have 21 cases with 4 fallthroughs (quite a bit, I know), but the cyclomatic complexity is reported as 79 (far more than it should be). All cases have simple `return` statements in them.

The same code written with if-else's does not violate the rule.

The bytecode that the compiler produces for string switches is horrible. So the detection is understandable. But the source code is very simple and at runtime it is faster than if-else statements. I'd argue that it makes sense to detect `hashCode` invocations on strings followed by `lookupswitch` and `tableswitch` and handle those differently. Maybe ignore the `lookupswitch` altogether and only consider what is in the `tableswitch`.

After all the cyclomatic complexity is supposed to consider only the independent paths. And the `lookupswitch` and `tableswitch` are highly dependent on each other. The number reported does not seem to reflect this.

**Comment by mebigfatguy** [comment]
thanks for the report, can you cook up a sample that you think  shows this problem?

**Comment by mebigfatguy** [comment]
I made a change to how switches are handled, if you are able to build the plugin from src and test, that would be helpful. thanks, either way!

**Comment by joankaradimov** [comment]
I don't believe it is fixed. The cyclomatic complexity is still the same.

Here are the things I did:
1. Clone the repo
1. Check for commit 2bbb07eb08e6214e961fa8dd794119a25804df47 (it was there)
1. Run `mvn package`
1. Replace `spotbugsPlugins 'com.mebigfatguy.sb-contrib:sb-contrib:7.4.6'` with `spotbugsPlugins files('......./fb-contrib/target/sb-contrib-7.4.7-SNAPSHOT.jar')` in `build.gradle`
1. Run `gradle check` in my project

... and it still failed.

Here's a stripped down version of the production code in question: [MimeTypeDetector.zip](https://github.com/mebigfatguy/fb-contrib/files/3349364/MimeTypeDetector.zip)

**Comment by joankaradimov** [comment]
@mebigfatguy, ping

**Comment by kstarsinic** [comment]
I just encountered this bug today (sb-contrib 7.4.4, spotbugs 3.1.12):
```java
boolean switch1(final String name) { // Complexity 7
  switch (name) {
    case "1":
      return false;
    default:
      return true;
  }
}
boolean switch2(final String name) { // Complexity 10
  switch (name) {
    case "1": case "2":
      return false;
    default:
      return true;
  }
}
boolean switch3(final String name) { // Complexity 13
  switch (name) {
    case "1": case "2": case "3":
      return false;
    default:
      return true;
  }
}
```
My actual method was a switch with 17 String cases and one default, and it reported with a Cyclomatic Complexity of 55 (it's adding 3 basis paths for each case). Glancing at the code, this could be a spotbugs error if those cases are not tagged as FALL_THROUGH_EDGE.

**Comment by ThrawnCA** [comment]
This is probably because of all the hash code checks generated by the compiler for string switches.

**Comment by kstarsinic** [comment]
@mebigfatguy, this issue is Closed, but your fix didn't actually do the trick.
