### ISSUE TITLE
COM_COPIED_OVERRIDDEN_METHOD false positive

### ISSUE THREAD

**Issue by nmatt** [mebigfatguy/fb-contrib#357]
COM_COPIED_OVERRIDDEN_METHOD is reported on a `close()` method on a subclass of `java.io.OutputStream`, where the method implementation is empty but the method removes the `throws` declaration for `IOException` (i.e. like what `java.io.ByteArrayOutputStream` should be doing, but for some reason doesn't).

I would suggest to not report COM_COPIED_OVERRIDDEN_METHOD on methods that relax the `throws` declaration of the overridden method. Obviously, having a relaxed `throws` declaration means that removing the overriding method can break client code. The same would hold for methods that narrow the method's return type (I haven't checked whether COM_COPIED_OVERRIDDEN_METHOD is reported in that case).

**Comment by mebigfatguy** [comment]
Thanks for the report, should be fixed.
