### ISSUE TITLE
IMC_IMMATURE_CLASS_NO_EQUALS reported for float/double instance fields

### ISSUE THREAD

**Issue by nmatt** [mebigfatguy/fb-contrib#359]
I'd like to suggest to not report IMC_IMMATURE_CLASS_NO_EQUALS on classes that have instance fields of type float or double, as equality comparison is inherently problematic for those types (due to NaN, and due to inexact nature of rounded values). See also [FE_FLOATING_POINT_EQUALITY](http://findbugs.sourceforge.net/bugDescriptions.html#FE_FLOATING_POINT_EQUALITY). Advising implementing `equals()` on such a class could cause more harm than benefit.

**Comment by mebigfatguy** [comment]
Thanks, I definitely don't have the heuristic right about what a class needs to look like to want an equals, and i'm not sure your rational is always true, but it will limit the applicability, and it might be true in some cases, so i'll go with it and see how it does.
