### ISSUE TITLE
PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS is inappropriate for factory methods

### ISSUE THREAD

**Issue by nmatt** [mebigfatguy/fb-contrib#362]
I get a lot of false positives for PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS on factory methods. One example are static factory methods invoked from a JDialog implementation to create instances of form fields with certain default settings. So for example there is a method `MySwingUtils.newTextField()` which is called multiple times from the form initialization code.

My suggestion would be to not report that bug pattern for methods with prefixes _create_ or _new_ (e.g., `createFoo()`, `newFoo()`). I tried to exclude the bug pattern using a regex match on the method name (via a FindBugs filter file), but unfortunately the matching is applied to the calling methods, not to the called methods.

**Comment by mebigfatguy** [comment]
at present you can ignore these by lauching findbugs/spotbugs with

-Dfbcontrib.PRMC.riskyclasses=com.nmatt.MySwingUtils

**Comment by mebigfatguy** [comment]
Actually i would think createFoo would already be allowed. I can add newFoo

**Comment by nmatt** [comment]
Thanks! I actually didn't test createFoo(), so you may be right.

**Comment by nmatt** [comment]
I tried specifying the system property via [jvmArgs](https://spotbugs.github.io/spotbugs-maven-plugin/check-mojo.html#jvmArgs) in the spotbugs-maven-plugin configuration, and the Maven debug output correctly shows "Adding JVM Arg => -Dfbcontrib.PRMC.riskyclasses=com.nmatt.MySwingUtils" (and fork is true), however PRMC is still reported for the callers. Any ideas what might be wrong?

**Comment by mebigfatguy** [comment]
sorry, it's 

-Dfbcontrib.PRMC.riskyclasses=com/nmatt/MySwingUtils

btw, that property is a comma separated list


i'll fix it in later versions so that you can use the normal "." as well as "/"

**Comment by mebigfatguy** [comment]
thanks for the report, should be fixed.
