### ISSUE TITLE
NAB_NEEDLESS_BOOLEAN_CONSTANT_CONVERSION false negative

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#365]
This code produces the `NAB_NEEDLESS_BOOLEAN_CONSTANT_CONVERSION` warning:

```java
System.err.println(List.<Object> of("", false));
```

This one doesn't:

```java
System.err.println(List.<Object> of(Math.random() > 0.5 ? "" : "1", false));
```

The problem is with the ternary operator as the first argument - the `Math.random` stuff is not important.

**Comment by mebigfatguy** [comment]
isn't this the same as

Object[] o = { "hello", false };

?

**Comment by boris-petrov** [comment]
@mebigfatguy - not sure what you mean, but yes, your example should also produce the same warning. I don't know if the implementation should treat these two cases as the same thing, that's up to you. :)

**Comment by mebigfatguy** [comment]
ah actually i think it's because List.of has a of(E e1, E e2) signature

**Comment by mebigfatguy** [comment]
thanks for the report. should be fixed.
