### ISSUE TITLE
BAS_BLOATED_ASSIGNMENT_SCOPE false positive

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#366]
We're seeing `BAS_BLOATED_ASSIGNMENT_SCOPE` firing on code that doesn't have any inner scopes. It's just assembling booleans from complex conditions.

Source:

    package au.gov.qld.ssq.strategy;

    import au.gov.qld.ssq.domain.ServiceOrderRequest;

    public class OwnedByStrategy {

        public boolean isOwnedByRequestor(ServiceOrderRequest existing, ServiceOrderRequest other) {
            boolean isCorrectOnlineService = existing.getOnlineService().getCode().equalsIgnoreCase(other.getOnlineService().getCode());
            boolean isCorrectOnlineServiceRefId = other.getOnlineServiceRefId() != null && existing.getOnlineServiceRefId() != null && existing.getOnlineServiceRefId().equals(other.getOnlineServiceRefId());
            boolean isBothOnlineServiceRefIdNull = existing.getOnlineServiceRefId() == null && other.getOnlineServiceRefId() == null;

            return isCorrectOnlineService && (isCorrectOnlineServiceRefId || isBothOnlineServiceRefIdNull);
        }
    }

Bytecode:

    Classfile target/classes/au/gov/qld/ssq/strategy/OwnedByStrategy.class
      Last modified 09/08/2019; size 1195 bytes
      MD5 checksum 9b7361048f820ff4f6a2d46d0b217fe4
      Compiled from "OwnedByStrategy.java"
    public class au.gov.qld.ssq.strategy.OwnedByStrategy
      minor version: 0
      major version: 52
      flags: ACC_PUBLIC, ACC_SUPER
    Constant pool:
       #1 = Methodref          #8.#28         // java/lang/Object."<init>":()V
       #2 = Methodref          #29.#30        // au/gov/qld/ssq/domain/ServiceOrderRequest.getOnlineService:()Lau/gov/qld/ssq/domain/OnlineService;
       #3 = Methodref          #31.#32        // au/gov/qld/ssq/domain/OnlineService.getCode:()Ljava/lang/String;
       #4 = Methodref          #33.#34        // java/lang/String.equalsIgnoreCase:(Ljava/lang/String;)Z
       #5 = Methodref          #29.#35        // au/gov/qld/ssq/domain/ServiceOrderRequest.getOnlineServiceRefId:()Ljava/lang/String;
       #6 = Methodref          #33.#36        // java/lang/String.equals:(Ljava/lang/Object;)Z
       #7 = Class              #37            // au/gov/qld/ssq/strategy/OwnedByStrategy
       #8 = Class              #38            // java/lang/Object
       #9 = Utf8               <init>
      #10 = Utf8               ()V
      #11 = Utf8               Code
      #12 = Utf8               LineNumberTable
      #13 = Utf8               LocalVariableTable
      #14 = Utf8               this
      #15 = Utf8               Lau/gov/qld/ssq/strategy/OwnedByStrategy;
      #16 = Utf8               isOwnedByRequestor
      #17 = Utf8               (Lau/gov/qld/ssq/domain/ServiceOrderRequest;Lau/gov/qld/ssq/domain/ServiceOrderRequest;)Z
      #18 = Utf8               existing
      #19 = Utf8               Lau/gov/qld/ssq/domain/ServiceOrderRequest;
      #20 = Utf8               other
      #21 = Utf8               isCorrectOnlineService
      #22 = Utf8               Z
      #23 = Utf8               isCorrectOnlineServiceRefId
      #24 = Utf8               isBothOnlineServiceRefIdNull
      #25 = Utf8               StackMapTable
      #26 = Utf8               SourceFile
      #27 = Utf8               OwnedByStrategy.java
      #28 = NameAndType        #9:#10         // "<init>":()V
      #29 = Class              #39            // au/gov/qld/ssq/domain/ServiceOrderRequest
      #30 = NameAndType        #40:#41        // getOnlineService:()Lau/gov/qld/ssq/domain/OnlineService;
      #31 = Class              #42            // au/gov/qld/ssq/domain/OnlineService
      #32 = NameAndType        #43:#44        // getCode:()Ljava/lang/String;
      #33 = Class              #45            // java/lang/String
      #34 = NameAndType        #46:#47        // equalsIgnoreCase:(Ljava/lang/String;)Z
      #35 = NameAndType        #48:#44        // getOnlineServiceRefId:()Ljava/lang/String;
      #36 = NameAndType        #49:#50        // equals:(Ljava/lang/Object;)Z
      #37 = Utf8               au/gov/qld/ssq/strategy/OwnedByStrategy
      #38 = Utf8               java/lang/Object
      #39 = Utf8               au/gov/qld/ssq/domain/ServiceOrderRequest
      #40 = Utf8               getOnlineService
      #41 = Utf8               ()Lau/gov/qld/ssq/domain/OnlineService;
      #42 = Utf8               au/gov/qld/ssq/domain/OnlineService
      #43 = Utf8               getCode
      #44 = Utf8               ()Ljava/lang/String;
      #45 = Utf8               java/lang/String
      #46 = Utf8               equalsIgnoreCase
      #47 = Utf8               (Ljava/lang/String;)Z
      #48 = Utf8               getOnlineServiceRefId
      #49 = Utf8               equals
      #50 = Utf8               (Ljava/lang/Object;)Z
    {
      public au.gov.qld.ssq.strategy.OwnedByStrategy();
        descriptor: ()V
        flags: ACC_PUBLIC
        Code:
          stack=1, locals=1, args_size=1
             0: aload_0
             1: invokespecial #1                  // Method java/lang/Object."<init>":()V
             4: return
          LineNumberTable:
            line 5: 0
          LocalVariableTable:
            Start  Length  Slot  Name   Signature
                0       5     0  this   Lau/gov/qld/ssq/strategy/OwnedByStrategy;

      public boolean isOwnedByRequestor(au.gov.qld.ssq.domain.ServiceOrderRequest, au.gov.qld.ssq.domain.ServiceOrderRequest);
        descriptor: (Lau/gov/qld/ssq/domain/ServiceOrderRequest;Lau/gov/qld/ssq/domain/ServiceOrderRequest;)Z
        flags: ACC_PUBLIC
        Code:
          stack=2, locals=6, args_size=3
             0: aload_1
             1: invokevirtual #2                  // Method au/gov/qld/ssq/domain/ServiceOrderRequest.getOnlineService:()Lau/gov/qld/ssq/domain/OnlineService;
             4: invokevirtual #3                  // Method au/gov/qld/ssq/domain/OnlineService.getCode:()Ljava/lang/String;
             7: aload_2
             8: invokevirtual #2                  // Method au/gov/qld/ssq/domain/ServiceOrderRequest.getOnlineService:()Lau/gov/qld/ssq/domain/OnlineService;
            11: invokevirtual #3                  // Method au/gov/qld/ssq/domain/OnlineService.getCode:()Ljava/lang/String;
            14: invokevirtual #4                  // Method java/lang/String.equalsIgnoreCase:(Ljava/lang/String;)Z
            17: istore_3
            18: aload_2
            19: invokevirtual #5                  // Method au/gov/qld/ssq/domain/ServiceOrderRequest.getOnlineServiceRefId:()Ljava/lang/String;
            22: ifnull        50
            25: aload_1
            26: invokevirtual #5                  // Method au/gov/qld/ssq/domain/ServiceOrderRequest.getOnlineServiceRefId:()Ljava/lang/String;
            29: ifnull        50
            32: aload_1
            33: invokevirtual #5                  // Method au/gov/qld/ssq/domain/ServiceOrderRequest.getOnlineServiceRefId:()Ljava/lang/String;
            36: aload_2
            37: invokevirtual #5                  // Method au/gov/qld/ssq/domain/ServiceOrderRequest.getOnlineServiceRefId:()Ljava/lang/String;
            40: invokevirtual #6                  // Method java/lang/String.equals:(Ljava/lang/Object;)Z
            43: ifeq          50
            46: iconst_1
            47: goto          51
            50: iconst_0
            51: istore        4
            53: aload_1
            54: invokevirtual #5                  // Method au/gov/qld/ssq/domain/ServiceOrderRequest.getOnlineServiceRefId:()Ljava/lang/String;
            57: ifnonnull     71
            60: aload_2
            61: invokevirtual #5                  // Method au/gov/qld/ssq/domain/ServiceOrderRequest.getOnlineServiceRefId:()Ljava/lang/String;
            64: ifnonnull     71
            67: iconst_1
            68: goto          72
            71: iconst_0
            72: istore        5
            74: iload_3
            75: ifeq          92
            78: iload         4
            80: ifne          88
            83: iload         5
            85: ifeq          92
            88: iconst_1
            89: goto          93
            92: iconst_0
            93: ireturn
          LineNumberTable:
            line 8: 0
            line 9: 18
            line 10: 53
            line 12: 74
          LocalVariableTable:
            Start  Length  Slot  Name   Signature
                0      94     0  this   Lau/gov/qld/ssq/strategy/OwnedByStrategy;
                0      94     1 existing   Lau/gov/qld/ssq/domain/ServiceOrderRequest;
                0      94     2 other   Lau/gov/qld/ssq/domain/ServiceOrderRequest;
               18      76     3 isCorrectOnlineService   Z
               53      41     4 isCorrectOnlineServiceRefId   Z
               74      20     5 isBothOnlineServiceRefIdNull   Z
          StackMapTable: number_of_entries = 7
            frame_type = 252 /* append */
              offset_delta = 50
              locals = [ int ]
            frame_type = 64 /* same_locals_1_stack_item */
              stack = [ int ]
            frame_type = 252 /* append */
              offset_delta = 19
              locals = [ int ]
            frame_type = 64 /* same_locals_1_stack_item */
              stack = [ int ]
            frame_type = 252 /* append */
              offset_delta = 15
              locals = [ int ]
            frame_type = 3 /* same */
            frame_type = 64 /* same_locals_1_stack_item */
              stack = [ int ]
    }
    SourceFile: "OwnedByStrategy.java"

**Comment by mebigfatguy** [comment]
It's correct but trivial. Which means it's difficult to differentiate from 'real' cases.

**Comment by mebigfatguy** [comment]
the solution i suppose is to look at method statistics to see what methods are trivial, and to ignore them for this.

**Comment by ThrawnCA** [comment]
So...the detector wants us not to calculate `isBothOnlineServiceRefIdNull` ahead of time, since it might be skipped by the short-circuit?

That's doable. Actually, this code was written before `Objects.equals` existed, and that method should allow us to greatly simplify it.
