### ISSUE TITLE
OCP_OVERLY_CONCRETE_PARAMETER false positive on ternary

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#367]
I've noticed `OCP_OVERLY_CONCRETE_PARAMETER` firing in a situation where we assign a list to a field using a ternary expression, like so:

    package ex;

    import java.util.ArrayList;
    import java.util.List;

    public class OCPIterableSample {

        private List<Object> resources;

        public OCPIterableSample(List<Object> resources) {
            this.resources = (resources == null) ? new ArrayList<>() : resources;
        }

    }

The detector is claiming that the parameter could be an `Iterable`, which is clearly false. Using Maven SpotBugs plugin 3.1.12 with `sb-contrib` 7.4.6.

There are certainly better ways to write this expression, but since it suggests a problem with the detector logic, I thought it was worth raising this.

**Comment by mebigfatguy** [comment]
Thanks, ternaries are a pain in the neck. I'll take a look.

Btw, I bet I'd you invert the ternary it will work.

⁣Get BlueMail for Android ​

**Comment by ThrawnCA** [comment]
If I changed it to `(resources != null) ? resources : new ArrayList<>()` then PMD would complain about the "if not...else" double negative.

**Comment by mebigfatguy** [comment]
yeah, i wasn't suggesting that as a solution. just imagining that the ternary is kicking my ascots.

**Comment by mebigfatguy** [comment]
i think it should be fixed. thanks for the report

**Comment by ThrawnCA** [comment]
Sorry, doesn't seem to be working. I've built the latest `sb-contrib` and the detector is still firing on the pattern I referenced above.
