### ISSUE TITLE
Proposal: Unnecessary Collection Nesting Detector

### ISSUE THREAD

**Issue by tpounds** [mebigfatguy/fb-contrib#37]
I noticed the following anti-pattern in some service code the other day. Arrays.asList(...) already creates a copy of the original array so nesting it inside an additional ArrayList is unnecessary.

```java
final List<...> valueList = new ArrayList<...>(Arrays.<...>asList(valueArray));
```

I'll take a crack at adding new detector for this bug but wanted to report it in case anyone wanted to get to it beforehand.

**Comment by kjlubick** [comment]
I say go for it!

**Comment by mebigfatguy** [comment]
I would suspect the reason they are doing this is because the List
returned from Arrays.asList is immutable, and they want to be able to
add or remove items or such. (unless you are saying you can determine
that the code will do no such thing, then that's another story. 

---
<br type="_moz" />

On 2015-03-24 16:00, Trevor Pounds wrote: 

> I noticed the following anti-pattern in some service code the other day. Arrays.asList(...) already creates a copy of the original array so nesting it inside an additional ArrayList is unnecessary. 
> 
> final List<...> valueList = new ArrayList<...>(Arrays.<...>asList(valueArray));
> 
> I'll take a crack at adding new detector for this bug but wanted to report it in case anyone wanted to get to it beforehand. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/mebigfatguy/fb-contrib/issues/37

**Comment by tpounds** [comment]
@mebigfatguy Looks like you are correct. I noticed after posting the issue that we were removing elements from the newly constructed list elsewhere. I think this idea still has some merit in the scenario where it is being constructed as above but never being mutated. However, the detector would require some additional escape and usage analysis on the object. Thoughts?

**Comment by mebigfatguy** [comment]
@tpounds One easy thing would be to see if Guava, (or perhaps some other collections library) was on the class path, and if so, recommend using 

List<?> valueList = Lists.newArrayList(valueArray);

instead.

I'd think determining if an ArrayList is used mutably would be kind of rough to do. As it's highly likely that that collection is going to be passed as a parameter somewhere. I suppose you could look for local-only use of the collection and report against that.

**Comment by ThrawnCA** [comment]
ArrayList really should have a constructor that accepts an array. But that's for Oracle to fix...

**Comment by mebigfatguy** [comment]
Guava is useful here.
