### ISSUE TITLE
[Feature request] indexOf instead of contains

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#370]
Similar to the `UCPM_USE_CHARACTER_PARAMETERIZED_METHOD` check.

Using `string.contains("-")` with single-character strings is probably slower than calling `string.indexOf('-') >= 0` (the character-accepting overload) so a check like that would be nice. Or am I wrong about that?

**Comment by mebigfatguy** [comment]
You are likely correct, although in this case, "contains" more accurately depicts what you are trying to do, over indexOf. So the question is how much does it help performance-wise... probably not much. So is it worth recommending something that is less readable, for dubious performance gains.??

**Comment by ThrawnCA** [comment]
[`StringUtils.contains`](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#contains-java.lang.CharSequence-int-) is probably the best of both worlds here.
