### ISSUE TITLE
false-positive SCII_SPOILED_CHILD_INTERFACE_IMPLEMENTOR with enums

### ISSUE THREAD

**Issue by marekjagielski** [mebigfatguy/fb-contrib#374]
Hi,
I get the issue SCII_SPOILED_CHILD_INTERFACE_IMPLEMENTOR on java enum which implements an interface. The interface defines some methods that each enum should implement:
```
public interface ImageDescriptor {

  String name();

  String path();

  Class<?> clazz();
}
```
Additionally it defines the 'name' method that is implicit in enums.

**Comment by mebigfatguy** [comment]
Ah ok, so name() is being implemented by java.lang.Enum. I assume the other two methods are not an issue.

**Comment by mebigfatguy** [comment]
ok, should be fixed if name() is the only problem.

**Comment by marekjagielski** [comment]
Yes, Exactly - it is the name() method. Thanks!
