### ISSUE TITLE
Check commit a56d716b for validation

### ISSUE THREAD

**Issue by hazendaz** [mebigfatguy/fb-contrib#378]
@mebigfatguy I might have the logic on a56d716b incorrect.  Can you take a closer look at the intent there?  I think it was saying if it doesn't contain item fall into processing.  With the NOT there on add, that would mean it only falls in if it fails to add (ie already contains).  I think that is counter to what was expected and needs corrected.  I think the ! needs removed.

**Comment by hazendaz** [comment]
If you don't have time, I can get back to this later tonight but wanted to make sure this didn't get missed :)  Sorry about that.

**Comment by mebigfatguy** [comment]
thanks.
