### ISSUE TITLE
false positive with Java 8 lambdas (OCP_OVERLY_CONCRETE_PARAMETER)

### ISSUE THREAD

**Issue by pabad** [mebigfatguy/fb-contrib#38]
When running findbugs on code that uses lambdas, we are seeing several false positives reported as parameters overly concrete.

I've veen able to reproduce the problem with this simple code snippet:

```java
import java.util.Arrays;
import java.util.Properties;


public class Test {
	public void test() {
		final Properties properties = new Properties();
		
		Arrays.stream(new String[] { "a", "b" })
			.forEach(prop -> properties.put(prop, "ok"));
	}
}
```

This is reporting:
```
 Method Test.lambda$test$3(Properties, String) needlessly defines parameter with concrete classes
```

Which is probably due to the way the compiler infers the types when creating the class for the lambda expression.

**Comment by mebigfatguy** [comment]
Thanks for the report!, committed a fix here 2dd7a7959f1738768f2fc85517089f50a4dbb1fe, to not report in synthetic methods.
