### ISSUE TITLE
false-positive in OI_OPTIONAL_ISSUES_USES_ORELSEGET_WITH_NULL

### ISSUE THREAD

**Issue by Vampire** [mebigfatguy/fb-contrib#384]
The rule complains about this method:

```java
@Override
public <R extends V> R get(String parameterName, Supplier<R> defaultValueSupplier) {
    return this
            .<R>get(parameterName)
            .orElseGet(defaultValueSupplier);
}
```

which clearly is not giving `null` to the method (except it actually comes in, but I don't think that's the point of the rule).

**Comment by mebigfatguy** [comment]
Thanks for the report, should be fixed.

**Comment by mattnelson** [comment]
@mebigfatguy When is it planned for a release that contains this FP fix?
