### ISSUE TITLE
OI_OPTIONAL_ISSUES_PRIMITIVE_VARIANT_PREFERRED reported from interface methods

### ISSUE THREAD

**Issue by lasselindqvist** [mebigfatguy/fb-contrib#386]
If you implement a method with return value _Optional<T>_ from an interface, with Double, Integer or Long type, OI_OPTIONAL_ISSUES_PRIMITIVE_VARIANT_PREFERRED is reported.
This however cannot be fixed with the suggestion the warning gives.
It seems to me that the warning should not be raised when such an interface method is implemented.

See https://github.com/mebigfatguy/fb-contrib/blob/992a2279d583bbe8df23849912bbe20e7b9d8556/src/main/java/com/mebigfatguy/fbcontrib/detect/OptionalIssues.java#L204

**Comment by mebigfatguy** [comment]
I assume you mean that you don't own the interface.

**Comment by lasselindqvist** [comment]
It could be, but in this case I do own it, it is just defined to have a method `Optional<T> getValue` which then causes the problem when it is also implemented for the primitive wrapper classes.
