### ISSUE TITLE
SpotBugs plugin - com.mebigfaguy.fb-contrib throwing java.lang error

### ISSUE THREAD

**Issue by jaydubb12** [mebigfatguy/fb-contrib#387]
**Triage Notes**

- There are SpotBugs defined versions of the plug-in that are noted to have resolved the issues

- Remediation through version change - UNSUCCESSFUL - Attempted the the latest version of the plug in, specific for Spotbugs as this was suggested by the repo owner to fix this, but it does not 7.4.3.sb, which can be referenced / found here= https://mvnrepository.com/artifact/com.mebigfatguy.fb-contrib/fb-contrib

**Alternative remediation**
Option 1 - RECOMMENDED: Remediate the issues through future releases

Option 2 - Remediate through custom code by downloading the public repositories, modifying the code and deploying a custom dependency(ies)

**Issue** - Maven Console log is displaying a variety of  errors when SpotBugs scan is running

**Error:** 
Exception analyzing...using detector com.mebigfatguy.fbcontrib.detect.OverlyPermissiveMethod
     [java]     java.lang.RuntimeException: Incompatible bcel version, apparently bcel has been upgraded to not use 'Unknown' for 'BootstrapMethods', but uses: BootstrapMethods
     [java]       At com.mebigfatguy.fbcontrib.detect.OverlyPermissiveMethod.getBootstrapMethod(OverlyPermissiveMethod.java:451)
     [java]       At com.mebigfatguy.fbcontrib.detect.OverlyPermissiveMethod.sawOpcode(OverlyPermissiveMethod.java:174)
     [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:882)
     [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:243)
     [java]       At com.mebigfatguy.fbcontrib.detect.OverlyPermissiveMethod.visitCode(OverlyPermissiveMethod.java:121)
     [java]       At org.apache.bcel.classfile.Code.accept(Code.java:132)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:315)
     [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:403)
     [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
     [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
     [java]       At com.mebigfatguy.fbcontrib.detect.OverlyPermissiveMethod.visitClassContext(OverlyPermissiveMethod.java:99)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:401)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1185)

com.whirlpoolcorp.digitalplatform.aem.core.models.content.navigation.StickyNavModel using detector com.mebigfatguy.fbcontrib.detect.OverlyPermissiveMethod

 java.lang.RuntimeException: Incompatible bcel version, apparently bcel has been upgraded to not use 'Unknown' for 'BootstrapMethods', but uses: BootstrapMethods

**Comment by mebigfatguy** [comment]
You get that message if you are using the findbugs version of fb-contrib in SpotBugs. In order to work with spotbugs, use the sb-contrib

https://mvnrepository.com/artifact/com.mebigfatguy.sb-contrib/sb-contrib

Are you saying you are using that, and you get that message?
