### ISSUE TITLE
OPM_OVERLY_PERMISSIVE_METHOD does not consider methods starting with `is` to be getters

### ISSUE THREAD

**Issue by sabberworm** [mebigfatguy/fb-contrib#390]
The convention for getters of booleans is to start with `is`, not `get`. See http://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/, section 8.3.2:

> 8.3.2
> Boolean properties
> In addition, for boolean properties, we allow a getter method to match the pattern:
> ```
> public boolean is<PropertyName>();
> ```
> This “is<PropertyName>” method may be provided instead of a “get<PropertyName>” method, or it may be provided in addition to a “get<PropertyName>” method.
> In either case, if the “is<PropertyName>” method is present for a boolean property then we will use the “is<PropertyName>” method to read the property value.
> An example boolean property might be:
> ```
> public boolean isMarsupial();
> public void setMarsupial(boolean m);
> ```

Also, the current implementation of `isGetterSetter` does not check if the character after `get` and `set` is upper-cased, which means methods like `gettyImages()` or `settopBox()` will be considered bean accessors…

Related code:

https://github.com/mebigfatguy/fb-contrib/blob/12b0fccda03139a635db99bf56c05ae7ef6898c9/src/main/java/com/mebigfatguy/fbcontrib/detect/OverlyPermissiveMethod.java#L218

**Comment by mebigfatguy** [comment]
thanks for the report, should be fixed in HEAD
