### ISSUE TITLE
PRMC false positive on Arrays.asList

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#40]
The Possibly-Redundant Method Calls detector is giving warnings when Arrays.asList is called multiple times with different parameters. Perhaps it is too aggressive about matching array contents?

The following class trips the detector:

    package example;

    import java.util.Arrays;

    public class FindBugsSample {
        public void run() {
            System.out.println(Arrays.asList("foo"));
            System.out.println(Arrays.asList("bar"));
        }
    }

**Comment by mebigfatguy** [comment]
Thanks for the report. I'm not able to reproduce so far. Can you tell me fb-contrib version, compiler version (oracle, openjdk,eclipse)? Also could you post output of Java -v.    

?

**Comment by ThrawnCA** [comment]
I'm running fb-contrib 6.0.1, using the FindBugs Maven plugin version 3.0.1.

Compiler plugin configuration:

    <plugin>
        <artifactId>maven-compiler-plugin</artifactId><version>3.3</version>
        <configuration>
            <source>1.7</source>
            <target>1.7</target>
            <optimize>true</optimize>
            <debug>true</debug>
            <compilerArgument>-Xlint</compilerArgument>
        </configuration>
    </plugin>

Java version:

    java version "1.7.0_79"
    OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
    OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

I'm also setting the ``-XX:-UseSplitVerifier`` flag, and ``-javaagent:spring-instrument.jar``.

**Comment by mebigfatguy** [comment]
Sorry had a typo in my last message. Could you post output of Javap -v

**Comment by ThrawnCA** [comment]
Ah, OK then.

``javap -v -cp target/classes example.FindBugsSample``

    Classfile target/classes/example/FindBugsSample.class
      Last modified 19/05/2015; size 642 bytes
      MD5 checksum 3722b0f514271dd74be66fd64dfe3529
      Compiled from "FindBugsSample.java"
    public class example.FindBugsSample
      SourceFile: "FindBugsSample.java"
      minor version: 0
      major version: 51
      flags: ACC_PUBLIC, ACC_SUPER
    Constant pool:
       #1 = Methodref          #9.#20         //  java/lang/Object."<init>":()V
       #2 = Fieldref           #21.#22        //  java/lang/System.out:Ljava/io/PrintStream;
       #3 = Class              #23            //  java/lang/String
       #4 = String             #24            //  foo
       #5 = Methodref          #25.#26        //  java/util/Arrays.asList:([Ljava/lang/Object;)Ljava/util/List;
       #6 = Methodref          #27.#28        //  java/io/PrintStream.println:(Ljava/lang/Object;)V
       #7 = String             #29            //  bar
       #8 = Class              #30            //  example/FindBugsSample
       #9 = Class              #31            //  java/lang/Object
      #10 = Utf8               <init>
      #11 = Utf8               ()V
      #12 = Utf8               Code
      #13 = Utf8               LineNumberTable
      #14 = Utf8               LocalVariableTable
      #15 = Utf8               this
      #16 = Utf8               Lexample/FindBugsSample;
      #17 = Utf8               run
      #18 = Utf8               SourceFile
      #19 = Utf8               FindBugsSample.java
      #20 = NameAndType        #10:#11        //  "<init>":()V
      #21 = Class              #32            //  java/lang/System
      #22 = NameAndType        #33:#34        //  out:Ljava/io/PrintStream;
      #23 = Utf8               java/lang/String
      #24 = Utf8               foo
      #25 = Class              #35            //  java/util/Arrays
      #26 = NameAndType        #36:#37        //  asList:([Ljava/lang/Object;)Ljava/util/List;
      #27 = Class              #38            //  java/io/PrintStream
      #28 = NameAndType        #39:#40        //  println:(Ljava/lang/Object;)V
      #29 = Utf8               bar
      #30 = Utf8               example/FindBugsSample
      #31 = Utf8               java/lang/Object
      #32 = Utf8               java/lang/System
      #33 = Utf8               out
      #34 = Utf8               Ljava/io/PrintStream;
      #35 = Utf8               java/util/Arrays
      #36 = Utf8               asList
      #37 = Utf8               ([Ljava/lang/Object;)Ljava/util/List;
      #38 = Utf8               java/io/PrintStream
      #39 = Utf8               println
      #40 = Utf8               (Ljava/lang/Object;)V
    {
      public example.FindBugsSample();
        flags: ACC_PUBLIC
        Code:
          stack=1, locals=1, args_size=1
             0: aload_0       
             1: invokespecial #1                  // Method java/lang/Object."<init>":()V
             4: return        
          LineNumberTable:
            line 5: 0
          LocalVariableTable:
            Start  Length  Slot  Name   Signature
                   0       5     0  this   Lexample/FindBugsSample;
    
      public void run();
        flags: ACC_PUBLIC
        Code:
          stack=5, locals=1, args_size=1
             0: getstatic     #2                  // Field java/lang/System.out:Ljava/io/PrintStream;
             3: iconst_1      
             4: anewarray     #3                  // class java/lang/String
             7: dup           
             8: iconst_0      
             9: ldc           #4                  // String foo
            11: aastore       
            12: invokestatic  #5                  // Method java/util/Arrays.asList:([Ljava/lang/Object;)Ljava/util/List;
            15: invokevirtual #6                  // Method java/io/PrintStream.println:(Ljava/lang/Object;)V
            18: getstatic     #2                  // Field java/lang/System.out:Ljava/io/PrintStream;
            21: iconst_1      
            22: anewarray     #3                  // class java/lang/String
            25: dup           
            26: iconst_0      
            27: ldc           #7                  // String bar
            29: aastore       
            30: invokestatic  #5                  // Method java/util/Arrays.asList:([Ljava/lang/Object;)Ljava/util/List;
            33: invokevirtual #6                  // Method java/io/PrintStream.println:(Ljava/lang/Object;)V
            36: return        
          LineNumberTable:
            line 7: 0
            line 8: 18
            line 9: 36
          LocalVariableTable:
            Start  Length  Slot  Name   Signature
                   0      37     0  this   Lexample/FindBugsSample;
    }

**Comment by ThrawnCA** [comment]
I've seen similar behavior with String.format, so I think it's related to arrays/varargs.

**Comment by mebigfatguy** [comment]
Odd. My compiler is emitting the same exact byte code. But I get no FPs. I don't think I changed anything lately in that file but I'll double check

**Comment by ThrawnCA** [comment]
Still causing problems here, in a different project (but same Maven/compiler configuration), on ``String.format``

**Comment by mebigfatguy** [comment]
Ok, thanks for the report, you are indeed correct that Arrays.asList and String.format show similar problems.

There were three problems really

1) These bugs were reported at EXP_PRIORITY, and the findbugs gui doesn't show experimental bugs by default
2) I had bad logic in there determining how large the stack had to be when a static method was called, by passing the args checking there
3) FindBugs itself attaches a constant value of the array length to an array, which is wrong, that's not the constant value. Which led me to believe i was comparing constants when i wasn't. OK, changed code to be cognizant of findbugs issue.

Hopefully it is fixed. If you could retest with the trunk version, and approve, i'll cut a new version shortly.

Thanks for the report.

**Comment by ThrawnCA** [comment]
Well, I've built 6.1.0-SNAPSHOT, and it fixes this specific issue :).

It introduces its own problems (false positives on new detectors), but I probably should raise separate issues for them.

Thanks!

**Comment by mebigfatguy** [comment]
cool. Yeah, there are a bunch of detectors in trunk that 
(a) won't see the light of day anytime soon (probably never)
(b) may be coming in 6.2.0, but i've got to clean out the FPs first

so, especially issues with

CharSetIssues, ContainsBasedConditional, OverlyPermissiveMethod
ClassImpersonatingString, SuspiciousLoopSearch, ConflatingResourcesAndFiles

would be greatly appreciated.

If there are other detectors that are 'new' to you, they are actually, old, broken, detectors, that i never could get clean enough, or were just bad ideas, that i never released. (But never the less, leave available on the dev - trunk version). Real versions won't have them.

Ok, so i'll cut a 6.0.2 shortly -- probably tomorrow. (just bug fixes).
