### ISSUE TITLE
NMCS_NEEDLESS_MEMBER_COLLECTION_SYNCHRONIZATION false positive

### ISSUE THREAD

**Issue by djelinski** [mebigfatguy/fb-contrib#402]
computeIfAbsent is not listed as modifyingMethod; as a result the following piece of code generates a false positive:
```
public abstract class CacheFbBug {

	private final Map<String, String> hashableStringCache;

	public CacheFbBug() {
		hashableStringCache = Collections.synchronizedMap(new HashMap<>());
	}

	public String getHashedString(String val) {
		return hashableStringCache.computeIfAbsent(val, this::hashString);
	}

	public abstract String hashString(String stringToHash);
}
```

**Comment by djelinski** [comment]
looking at https://download.java.net/java/early_access/jdk15/docs/api/java.base/java/util/Map.html I see a few more methods missing:
- compute
- computeIfAbsent
- computeIfPresent
- merge
- putAll
- putIfAbsent
- replace
- replaceAll

**Comment by andrei-ivanov** [comment]
would be nice to get this fixed 👍

**Comment by mebigfatguy** [comment]
looks like i fixed this a bit ok, sorry didn't close it. Thanks for the info.
