### ISSUE TITLE
FII_USE_METHOD_REFERENCE false positive

### ISSUE THREAD

**Issue by Tomlincoln** [mebigfatguy/fb-contrib#403]
Hello! I think the following can not be simplified to method reference:

```
long matchingCounter = StreamSupport.stream(workbook.getSheetAt(0).spliterator(), false).skip(1)
                .map(row -> userCashbacks.stream()
                        .filter(cashback -> cashback.getOriginalTransactionCurrency() == CompanyCurrency.HUF)
                        .filter(cashback -> checkFoundTransaction(cashback, datetimeFieldOrder, amountFieldOrder, row))
                        .count())
                .mapToLong(i -> i)
                .sum();
```

Triggered on the 2nd line.

Could you please check? :)

**Comment by ThrawnCA** [comment]
Perhaps if you combine the two filter expressions instead of calling `filter` twice?

**Comment by Tomlincoln** [comment]
Thank you! Combined them with && and **works fine**. Although, I think this behavior is a bit strange.

**Comment by ThrawnCA** [comment]
Well, if you didn't need to filter twice, you could `map` first  to the currency and then pass an `equals` method reference.

**Comment by Tomlincoln** [comment]
Ah, I see. Thank you for explaining. :)
