### ISSUE TITLE
7.4.x.sb is missing in maven central

### ISSUE THREAD

**Issue by prabhu** [mebigfatguy/fb-contrib#404]
Are the .sb versions still required for spotbugs compatibility? If yes, will you be able to upload the 7.4.7.sb version to maven central? For example, you can see them missing here - https://repo1.maven.org/maven2/com/mebigfatguy/fb-contrib/fb-contrib/

Thanks.

**Comment by ThrawnCA** [comment]
Actually there's a whole new artifact, `com.mebigfatguy.sb-contrib:sb-contrib`.
