### ISSUE TITLE
Sourceforge site is outdated

### ISSUE THREAD

**Issue by jsotuyod** [mebigfatguy/fb-contrib#41]
http://fb-contrib.sf.net/ doesn't mention release 6.0.1, nor that it uses findbugs 3.0.1.

Also, I'm not sure if all detectors are listed there.

**Comment by mebigfatguy** [comment]
thanks, sorry about that. Hopefully it's updated now. Let me know if i missed something.

**Comment by jsotuyod** [comment]
Awesome, much better. But aren't the new detectors included in 6.0.1? The site says they are only in git repository.

**Comment by mebigfatguy** [comment]
No, versions differing in the third digit only are bug fix changes. These new detectors will come in 6.2.0. I still have some shaking out to do for these, running them on more codebases, and then decide which ones are ready to go. Hopefully not too long.

Thanks for your interest.
dave
