### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException during sonar maven plugin execution

### ISSUE THREAD

**Issue by elballa** [mebigfatguy/fb-contrib#410]
sonar-maven-plugin:3.7.0.1746:sonar execution outputs a lot of java.lang.ArrayIndexOutOfBoundsException exceptions:

[INFO] Findbugs output report: /workspace/module/rest/target/sonar/findbugs-result.xml
The following errors occurred during analysis:
  Exception analyzing acme.RestService1 using detector com.mebigfatguy.fbcontrib.detect.JAXRSIssues
    java.lang.ArrayIndexOutOfBoundsException: 4
      At com.mebigfatguy.fbcontrib.detect.JAXRSIssues.processJAXRSMethod(JAXRSIssues.java:210)
      At com.mebigfatguy.fbcontrib.detect.JAXRSIssues.visitMethod(JAXRSIssues.java:173)
      At org.apache.bcel.classfile.Method.accept(Method.java:108)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:312)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:403)
      At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
      At com.mebigfatguy.fbcontrib.detect.JAXRSIssues.visitClassContext(JAXRSIssues.java:127)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
      At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
      At java.util.concurrent.FutureTask.run(FutureTask.java:266)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      At java.lang.Thread.run(Thread.java:748)
  Exception analyzing acme.RestService2 using detector com.mebigfatguy.fbcontrib.detect.JAXRSIssues
    java.lang.ArrayIndexOutOfBoundsException: 2
      At com.mebigfatguy.fbcontrib.detect.JAXRSIssues.processJAXRSMethod(JAXRSIssues.java:210)
      At com.mebigfatguy.fbcontrib.detect.JAXRSIssues.visitMethod(JAXRSIssues.java:173)
      At org.apache.bcel.classfile.Method.accept(Method.java:108)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:312)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:403)
      At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
      At com.mebigfatguy.fbcontrib.detect.JAXRSIssues.visitClassContext(JAXRSIssues.java:127)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
      At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
      At java.util.concurrent.FutureTask.run(FutureTask.java:266)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      At java.lang.Thread.run(Thread.java:748)
  Exception analyzing acme.RestService3 using detector com.mebigfatguy.fbcontrib.detect.JAXRSIssues
    java.lang.ArrayIndexOutOfBoundsException: 11
      At com.mebigfatguy.fbcontrib.detect.JAXRSIssues.processJAXRSMethod(JAXRSIssues.java:210)
      At com.mebigfatguy.fbcontrib.detect.JAXRSIssues.visitMethod(JAXRSIssues.java:173)
      At org.apache.bcel.classfile.Method.accept(Method.java:108)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:312)
      At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:403)
      At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:213)
      At com.mebigfatguy.fbcontrib.detect.JAXRSIssues.visitClassContext(JAXRSIssues.java:127)
      At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
      At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1080)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:281)
      At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
      At java.util.concurrent.FutureTask.run(FutureTask.java:266)
      At java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      At java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      At java.lang.Thread.run(Thread.java:748)

**Comment by elballa** [comment]
Any news?

**Comment by mebigfatguy** [comment]
what version of fb-contrib/sb-contrib is this?

**Comment by mebigfatguy** [comment]
added synthetic guard against running off the param table.

targetted for 7.6.4
