### ISSUE TITLE
 False-positive for PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS

### ISSUE THREAD

**Issue by Vampire** [mebigfatguy/fb-contrib#416]
Following code triggers a false-positive for `PRMC_POSSIBLY_REDUNDANT_METHOD_CALLS` for the `length` call:
```java
left.insert(left.length() - 2, "(?:");
left.insert(left.length() - 2, PARAMETER_SEPARATOR_PATTERN_STRING);
left.insert(left.length() - 2, "|$)");
```
It seems the check misses that this is used as parameter to an `insert` call on that same instance which then of course is evaluated after the `length()` call and thus changes the returned value.

`left` is a `StringBuilder` in this case.

**Comment by mebigfatguy** [comment]
targetted for 7.6.3
