### ISSUE TITLE
false positive for LO_TOSTRING_PARAMETER

### ISSUE THREAD

**Issue by MatsLP** [mebigfatguy/fb-contrib#419]
Dear Maintainers,
I think the `LO_TOSTRING_PARAMETER` rule, that is meant to warn on unnecessary `.toString()` calls when logging is a little bit too eager.

In this piece of code it is desired to not print the stacktrace of the exception. The way to do this, is to explicitly call `.toString()`.
`LOG.info("User login failed due to {}", exception.toString()); // does not log stacktrace`

If we omit `.toString()` a different overload of the log function will be called that results in the exception being printed.
`LOG.info("User login failed due to {}", exception); // logs stacktrace`

The rule should probably be adapted so that a `.toString()` call on an exception that is the last parameter does not trigger a violation

**Comment by mebigfatguy** [comment]
targetted for 7.6.3
