### ISSUE TITLE
OPM_OVERLY_PERMISSIVE_METHOD does not take account of libraries

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#42]
The new OPM_OVERLY_PERMISSIVE_METHOD detector does not consider the possibility that a method may validly be used outside the visible codebase (eg if it is a library). This makes it so noisy that it usually needs to be turned off. Perhaps it should be lowered in priority to reflect this.

However, there may still be more reliable uses of this detector, eg there is no need for the constructor of an abstract class to be public.

**Comment by mebigfatguy** [comment]
Hmm. i only report on methods that are actually called, so that should limit the API case. Also i would have assumed there was unit tests or what not that would be calling them.

But you have a point. Perhaps i will lower them.

**Comment by ThrawnCA** [comment]
Well, yes, comprehensive unit testing for public methods is the ideal...we're working toward it gradually.

**Comment by ThrawnCA** [comment]
Do you think it makes sense for the special case of an abstract class to have its own detector, perhaps at a higher priority?

**Comment by mebigfatguy** [comment]
two problems i see with that is
1) there will be many abstract classes with a default public constructor
2) doesn't hurt anything to be public

**Comment by ThrawnCA** [comment]
Fair enough.

By the way, when it comes to unit testing, typically (at least in my experience) the unit tests are in the same package. So, will that mean that even with comprehensive testing, the detector may still fire on classes that are only used in anger outside the current codebase?

**Comment by mebigfatguy** [comment]
i only differentiate private/public, not protected or package private

**Comment by mebigfatguy** [comment]
changed to LOW_PRIORITY
