### ISSUE TITLE
`JXI_INVALID_CONTEXT_PARAMETER_TYPE` false-positive with `CloseableService`

### ISSUE THREAD

**Issue by boris-petrov** [mebigfatguy/fb-contrib#425]
According to the [documentation](https://github.com/eclipse-ee4j/jersey/blob/2.35/core-server/src/main/java/org/glassfish/jersey/server/CloseableService.java#L26), `CloseableService` should be used with `javax.ws.rs.core.Context` but `JXI_INVALID_CONTEXT_PARAMETER_TYPE` warns that this type is not valid. That's a bug.

**Comment by mebigfatguy** [comment]
targetted for  7.6.1
