### ISSUE TITLE
Build with Maven?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#43]
Is there a specific blocker preventing fb-contrib from having a Maven build? After all, it already exists in the Maven repository ecosystem...

This would eliminate the need to manually download JARs first; anyone with Maven could just clone the repository and run ``mvn clean install``.

**Comment by ThrawnCA** [comment]
If it's just a matter of taking time to write the POM, I'd be happy to give it a go sometime.

**Comment by mebigfatguy** [comment]
There already is a pom, and I believe it works, altho can't say that i use it. If you find something wrong with it, welcome to add a pull request.

**Comment by ThrawnCA** [comment]
True! I hadn't noticed that. Perhaps it should be mentioned in the readme as an alternative build strategy?

The Maven build seems to result in a usable plugin, but it doesn't have the Eclipse metadata that the Ant build does.
