### ISSUE TITLE
OPM_OVERLY_PERMISSIVE_METHOD False Positive on Interface Method

### ISSUE THREAD

**Issue by kev22257** [mebigfatguy/fb-contrib#437]
When using the `org.springframework.jdbc.core.SqlReturnType` interface I get a SpotBugs warning for `OPM_OVERLY_PERMISSIVE_METHOD` for my implementation of `getTypeValue` because I have it defined as public when the interface requires it to be.  I am wondering if the detector is confused because the interface method is not explicitly denoted public, but by definition [IS](https://docs.oracle.com/javase/specs/jls/se17/html/jls-9.html#jls-9.4).

> A method in the body of an interface declaration may be declared public or private ([§6.6](https://docs.oracle.com/javase/specs/jls/se17/html/jls-6.html#jls-6.6)). If no access modifier is given, the method is implicitly public. It is permitted, but discouraged as a matter of style, to redundantly specify the public modifier for a method declaration in an interface declaration.

Snip of the Spring class:

```
public interface SqlReturnType {

	/**
	 * Constant that indicates an unknown (or unspecified) SQL type.
	 * Passed into setTypeValue if the original operation method does
	 * not specify an SQL type.
	 * @see java.sql.Types
	 * @see JdbcOperations#update(String, Object[])
	 */
	int TYPE_UNKNOWN = Integer.MIN_VALUE;


	/**
	 * Get the type value from the specific object.
	 * @param cs the CallableStatement to operate on
	 * @param paramIndex the index of the parameter for which we need to set the value
	 * @param sqlType the SQL type of the parameter we are setting
	 * @param typeName the type name of the parameter (optional)
	 * @return the target value
	 * @throws SQLException if an SQLException is encountered setting parameter values
	 * (that is, there's no need to catch SQLException)
	 * @see java.sql.Types
	 * @see java.sql.CallableStatement#getObject
	 */
	Object getTypeValue(CallableStatement cs, int paramIndex, int sqlType, @Nullable String typeName)
			throws SQLException;

}
```

And my class (specifically the getTypeValue method):

```
public class OracleSqlReturnIntegerArray implements SqlReturnType {
    static Integer[] toIntegerArray(Array array) throws SQLException {
        BigDecimal[] bdArray = (BigDecimal[]) array.getArray();
        return Arrays.stream(bdArray)
                .map(BigDecimal::intValue)
                .toArray(Integer[]::new);
    }

    @Override
    @SuppressFBWarnings(value = "OPM_OVERLY_PERMISSIVE_METHOD",
                        justification = "Cannot reduce the visibility of the inherited method")
    public Integer[] getTypeValue(CallableStatement cs, int paramIndex,
            int sqlType, String typeName) throws SQLException {
        Array array = cs.getArray(paramIndex);
        return (array == null) ? new Integer[0] : toIntegerArray(array);
    }
}
```

Without public (or with any other modifier) I get the following warning:

```
Multiple markers at this line
	- Cannot reduce the visibility of the inherited method from SqlReturnType
	- implements org.springframework.jdbc.core.SqlReturnType.getTypeValue
```

**Comment by kev22257** [comment]
Was anyone able to look at this and confirm?

**Comment by kev22257** [comment]
I looked into this a little, and found that because the interface return type is `Object` and my return type is `Integer[]` the test on line 342 in `OverlyPermissiveMethod` fails.

https://github.com/mebigfatguy/fb-contrib/blob/28c23d607aa5d4eee2982cf5c0ccbbce491db8db/src/main/java/com/mebigfatguy/fbcontrib/detect/OverlyPermissiveMethod.java#L337-L344

The logic then ends up in `isConstrainedByInterface` and tries to match the signatures.  When it checks the second argument it compares `int` to `int` (really `"I"` to `"I"`) and returns false; this seems incorrect, @mebigfatguy, should there be a `!` on the equals test on line 354?

https://github.com/mebigfatguy/fb-contrib/blob/28c23d607aa5d4eee2982cf5c0ccbbce491db8db/src/main/java/com/mebigfatguy/fbcontrib/detect/OverlyPermissiveMethod.java#L349-L358

**Comment by mebigfatguy** [comment]
the problem is that when comparing signatures we have to drop  the return type. so it's comparing

(.....)Ljava/lang/Object; to (.....)[java/lang/Integer;

**Comment by mebigfatguy** [comment]
targetted for  7.6.1
