### ISSUE TITLE
Valid reason for ENMI_ONE_ENUM_VALUE

### ISSUE THREAD

**Issue by ben-manes** [mebigfatguy/fb-contrib#439]
> Item 3: Enforce the singleton property with a private constructor or an enum type; EJ, 3rd ed.
> A third way to implement a singleton is to declare a single-element enum:
```java
// Enum singleton - the preferred approach
public enum Elvis {
    INSTANCE;
    public void leaveTheBuilding() { ... }
}
```
>This approach is similar to the public field approach, but it is more concise, provides the serialization machinery for free, and provides an ironclad guarantee against multiple instantiation, even in the face of sophisticated serialization or reflection attacks. This approach may feel a bit unnatural, but a single-element enum type is often the best way to implement a singleton. Note that you can’t use this approach if your singleton must extend a superclass other than Enum (though you can declare an enum to implement interfaces).

---

This rule's explanation does not mention this valid use-case, as it states:

> ENMI_ONE_ENUM_VALUE: Enum class only declares one enum value
>
>This enum class only declares one value (or perhaps 0!). As such it is pointless, as its value will always be the same thing. Therefore use of this enum is just bloating the code base. One exception is if you are using a null value as a second value. This is a mistake, and should be replaced with a second enum value, even if it's NULL, or UNKNOWN, or NON_INTITIALIZED or some other sentinel value.

It is certainly fine if you prefer to keep this enabled (as serialization is devil's work) and the rule easily excluded. However, the valid use-case is a security precaution and that description might prompt a developer to refactor code to become insecure.

**Comment by mebigfatguy** [comment]
targetted for 7.6.1

**Comment by mebigfatguy** [comment]
(sorry misapplied comment)

**Comment by mebigfatguy** [comment]
targetted for 7.6.1

**Comment by ben-manes** [comment]
fyi, I still see this being erroneously reported.

```console
➜  gradle caffeine:dependencies | rg mebigfatguy
\--- com.mebigfatguy.sb-contrib:sb-contrib:7.6.1
```

<img src="https://github.com/mebigfatguy/fb-contrib/assets/378614/fe04f4d4-14fa-474b-9933-3512370cddd8" width="75%">

```java
enum DisabledTicker implements Ticker {
  INSTANCE;

  @Override public long read() {
    return 0L;
  }
}
```
See [Ticker](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Ticker.java).
