### ISSUE TITLE
Incorrect detection of ENMI_ONE_ENUM_VALUE in version 7.6.0

### ISSUE THREAD

**Issue by donalmurtagh** [mebigfatguy/fb-contrib#440]
After upgrading to version 7.6.0, the following enum is wrongly detected to be in violation of the ENMI_ONE_ENUM_VALUE rule, i.e. an enum must have more than one (constant) value. This did not happen in version 7.4.7

```java
public enum MyEnum {
    VAL1 {
        @Override
        public String toString() {
            return "val1";
        }
    },
    VAL2 {
        @Override
        public String toString() {
            return "val2";
        }
    };
}
```

If I remove the `toString` overrides, a violation is still erroneously detected

```java
public enum MyEnum {
    VAL1 {
    },
    VAL2 {
    };
}
```

If the empty blocks are removed, no violations are detected

```java
public enum MyEnum {
    VAL1,
    VAL2;
}
```

**Comment by mebigfatguy** [comment]
targetted for 7.6.1
