### ISSUE TITLE
7.6.0.sb is missing from maven central

### ISSUE THREAD

**Issue by a1dutch** [mebigfatguy/fb-contrib#448]
Hi,

is it possible you could publish 7.6.0.sb to maven central? the last version available there is 7.4.3.sb

Cheers

Andy

**Comment by pzygielo** [comment]
That cannot be true, check
- #346

and close this issue, please.

**Comment by a1dutch** [comment]
@pzygielo thanks, got it working but also ran into #438 at the same time
