### ISSUE TITLE
Regressoin of BAS_BLOATED_ASSIGNMENT_SCOPE after update from 7.6.0 to 7.6.1 

### ISSUE THREAD

**Issue by romani** [mebigfatguy/fb-contrib#450]
detected during dependency bump com.mebigfatguy.sb-contrib:sb-contrib from 7.6.0 to 7.6.1 https://github.com/checkstyle/checkstyle/pull/14063

BAS_BLOATED_ASSIGNMENT_SCOPE started to put violation of code that is ok (IMO).

**Comment by mebigfatguy** [comment]
BAS was accidentally added in 7.6.1, try 7.6.2
