### ISSUE TITLE
WOC_WRITE_ONLY_COLLECTION_LOCAL false positive if collection is read in lambda

### ISSUE THREAD

**Issue by donalmurtagh** [mebigfatguy/fb-contrib#451]
This was introduced when I upgraded sb-contrib from 7.6.0 to 7.6.1 and spotbugs from 5.2.3 to 5.2.4. It looks like a regression of #39 

```java
public class FbFail {

    private final List<String> list = List.of("foo", "bar");

    public void fail() {
        list.forEach(System.out::println);
        /*
        for (var obj : list) {
            System.out.println(obj);
        }
         */
    }
}
```

The `forEach` fails the `WOC_WRITE_ONLY_COLLECTION_LOCAL` check, but if it is replaced by the for-loop the check passes.

**Comment by mebigfatguy** [comment]
oops, not  sure what happened. targetted at 7.6.2
