### ISSUE TITLE
Why not just rename repo to 'sb-contrib' and stop deploying 'fb-contrib'

### ISSUE THREAD

**Issue by hazendaz** [mebigfatguy/fb-contrib#452]
@mebigfatguy 

findbugs itself is dead now for 8 years.  spotbugs successfully 100% replaced it.  It feels a little silly to me to still see fb-contrib getting released along side sb-contrib. I think its time to retire fb-contrib.  Plus I imagine that would make things a bit easier since it managed on 2 branches.  WDYT?

**Comment by mebigfatguy** [comment]
october downloads from maven
~20k for spotbugs
~8k for findbugs

not quite dead yet.

**Comment by hazendaz** [comment]
I get the same findings on repos I support and I dropped old support.  Some people just don't upgrade their software.  If you released fb-contrib again with a relocation pom in it, that might make those that are not using right one change. Of course I don't think I did that with spotbugs maven plugin either and not sure it was done at all with spotbugs.  I also don't recall how difficult that is to do to central and many times I've seen that land with more problems.  It is quite surprising that folks are still using the fb based version for such a long time at this point but then again maybe they just don't know to rename this one.

Has that number been at least decreasing?

**Comment by mebigfatguy** [comment]
surprisingly the downloads for fb-contrib are pretty flat month on month.

**Comment by hazendaz** [comment]
ok sounds like they do need a relocation pom.

**Comment by ThrawnCA** [comment]
Sometimes projects just remain untouched for years on the principle of If It Ain't Broke...
