### ISSUE TITLE
Thoughts on donating this project to spotbugs as its so frequently used with spotbugs

### ISSUE THREAD

**Issue by hazendaz** [mebigfatguy/fb-contrib#457]
I think most uses and even most of our tests show we are using sb-contrib at this point.  I feel like this makes a good candidate to be part of the spotbugs camp.  If you are not a contributor there clearly you would be one with same access as you have here but this would get more broad attention as part of spotbugs.  We are just starting a discussion of such feasibility so I wanted to ask what your thought would be of doing a transfer to spotbugs if we decide that does make sense.  If it helps, we are getting some 2.5 million downloads a month and user base that contributes is rather high from what I've seen on other projects.  I think trying to bring all the parts together would be good for the community as a whole.  There has also been some track record of you and I working together here for a number of years and it feels like consolidation into the organization rather than personal repo would be a larger benefit to progress this framework.

Thoughts?

**Comment by mebigfatguy** [comment]
nah you use gradle. i'd have to shoot myself.

**Comment by hazendaz** [comment]
It would remain maven. I hate gradle too.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
FWIW - I updated our discussion that in no way would we force anyone to some other build platform.  In fact, the main contributors now on spotbugs seem on consensus we all dislike gradle.

**Comment by hazendaz** [comment]
FWIW. We don't plan to hard-fork anything.  If we were to do so, we would make it obvious that fb version is end of life and would rename sb-contrib to probably spotbugs-extensions or something similar.  At the moment we don't want to do that unless current authors come along in the process.  Anyway thank you for quick response as it will help the discussion.  Thanks.
