### ISSUE TITLE
False positive (OCP_OVERLY_CONCRETE_PARAMETER)

### ISSUE THREAD

**Issue by franciscopagliaricci** [mebigfatguy/fb-contrib#46]
Hi, I've come around a false positive with this check. It reports a parameter as overly concrete, yet it is clearly not the case. Possibly referred to issue 38, but not sure.
``` java
public class App 
{
	@Nonnull
	public Factory bazFactory(@Nonnull final Foo foo) {
		return (bar) -> baz(foo, bar);
	}
	
	@Nonnull
	public Baz baz(@Nonnull final Foo foo, @Nonnull final Bar bar) {
		return new Baz(foo, bar);
	}
}

public class Baz {

	private final Foo foo;
	private final Bar bar;

	public Baz(@Nonnull final Foo foo, @Nonnull final Bar bar) {
		this.foo = foo;
		this.bar = bar;
	}
	
	public void method() {
		foo.methodB(bar);
	}
}

public interface Foonterface<T> {
	void methodA(@Nonnull final T elem);
}

public class Foo implements Foonterface<Bar> {
	public void methodA(final Biar bar) {
	}

	public void methodB(@Nonnull final Bar bar) {
	}	
}

public interface Factory {
	@Nonnull Baz create(@Nonnull final Bar bar);
}
```

It reports:
"1st parameter 'foo' could be declared as Foonterface instead" in line: return (bar) -> baz(foo, bar);

Yet it clearly should be class Foo, as it is needed to create a Baz, and Baz can't use a Foonterface since it has to call methodB, that is not part of the interface

**Comment by mebigfatguy** [comment]
Thanks for the report. Yes it is similar. Pushed a fix to trunk as cbebcf798b83fa73fafaa9778a728bc506f62a4f

Will push a 6.2.1 in the next week.
