### ISSUE TITLE
CSI_CHAR_SET_ISSUES_USE_STANDARD_CHARSET_NAME is case-sensitive (false negative)

### ISSUE THREAD

**Issue by jsotuyod** [mebigfatguy/fb-contrib#49]
The detector is case-sensitive, therefore, it reports usages of strings such as `"UTF-8"`, but not usages of `"utf-8"`.

This is wrong, since charsets in Java are case-insensitive, as seen [in the documentation](http://docs.oracle.com/javase/7/docs/api/java/nio/charset/Charset.html).

> Charset names are not case-sensitive; that is, case is always ignored when comparing charset names.

**Comment by mebigfatguy** [comment]
thanks for the report, fixed in e5d5274345343ec8f258e93641484eea43ea3af6
