### ISSUE TITLE
DRE_DECLARED_RUNTIME_EXCEPTION false positive on method generated in implementing class

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#51]
When an interface from a third-party library declares a RuntimeException in the ``throws`` clause of a method that returns a type, and then one of our classes implements that interface with a method that returns a subtype and does *not* declare the RuntimeException, we get a DRE_DECLARED_RUNTIME_EXCEPTION false positive.

This appears to happen because when the implementing method returns a subtype, Java generates a second method with the original signature, delegating to the first method, and that generated method still declares the RuntimeException.

It would be correct for the rule to fire on the third-party interface, but we cannot fix that (in this case, it's from Spring).

**Comment by ThrawnCA** [comment]
Sample code to reproduce:

    package findbugs.sample;

    public class TestRuntimeExceptionOnImplementingClass implements ThrowsRuntimeException {
        @Override
        public String someMethod() {
            return "foo";
        }
    }

    interface ThrowsRuntimeException {
        public Object someMethod() throws RuntimeException;
    }

The rule should fire for the interface, but not for the class.

**Comment by ThrawnCA** [comment]
Output from javap -v showing generated method:

    Classfile findbugs/sample/TestRuntimeExceptionOnImplementingClass.class
      Last modified 31/07/2015; size 673 bytes
      MD5 checksum 8f8e7aa015c835f6a217ba9266e663b9
      Compiled from "TestRuntimeExceptionOnImplementingClass.java"
    public class findbugs.sample.TestRuntimeExceptionOnImplementingClass implements findbugs.sample.ThrowsRuntimeException
      SourceFile: "TestRuntimeExceptionOnImplementingClass.java"
      minor version: 0
      major version: 51
      flags: ACC_PUBLIC, ACC_SUPER
    Constant pool:
       #1 = Methodref          #5.#21         //  java/lang/Object."<init>":()V
       #2 = String             #22            //  foo
       #3 = Methodref          #4.#23         //  findbugs/sample/TestRuntimeExceptionOnImplementingClass.someMethod:()Ljava/lang/String;
       #4 = Class              #24            //  findbugs/sample/TestRuntimeExceptionOnImplementingClass
       #5 = Class              #25            //  java/lang/Object
       #6 = Class              #26            //  findbugs/sample/ThrowsRuntimeException
       #7 = Utf8               <init>
       #8 = Utf8               ()V
       #9 = Utf8               Code
      #10 = Utf8               LineNumberTable
      #11 = Utf8               LocalVariableTable
      #12 = Utf8               this
      #13 = Utf8               Lfindbugs/sample/TestRuntimeExceptionOnImplementingClass;
      #14 = Utf8               someMethod
      #15 = Utf8               ()Ljava/lang/String;
      #16 = Utf8               ()Ljava/lang/Object;
      #17 = Utf8               Exceptions
      #18 = Class              #27            //  java/lang/RuntimeException
      #19 = Utf8               SourceFile
      #20 = Utf8               TestRuntimeExceptionOnImplementingClass.java
      #21 = NameAndType        #7:#8          //  "<init>":()V
      #22 = Utf8               foo
      #23 = NameAndType        #14:#15        //  someMethod:()Ljava/lang/String;
      #24 = Utf8               findbugs/sample/TestRuntimeExceptionOnImplementingClass
      #25 = Utf8               java/lang/Object
      #26 = Utf8               findbugs/sample/ThrowsRuntimeException
      #27 = Utf8               java/lang/RuntimeException
    {
      public findbugs.sample.TestRuntimeExceptionOnImplementingClass();
        flags: ACC_PUBLIC
        Code:
          stack=1, locals=1, args_size=1
             0: aload_0       
             1: invokespecial #1                  // Method java/lang/Object."<init>":()V
             4: return        
          LineNumberTable:
            line 3: 0
          LocalVariableTable:
            Start  Length  Slot  Name   Signature
                   0       5     0  this   Lfindbugs/sample/TestRuntimeExceptionOnImplementingClass;

      public java.lang.String someMethod();
        flags: ACC_PUBLIC
        Code:
          stack=1, locals=1, args_size=1
             0: ldc           #2                  // String foo
             2: areturn       
          LineNumberTable:
            line 6: 0
          LocalVariableTable:
            Start  Length  Slot  Name   Signature
                   0       3     0  this   Lfindbugs/sample/TestRuntimeExceptionOnImplementingClass;

      public java.lang.Object someMethod() throws java.lang.RuntimeException;
        flags: ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
        Code:
          stack=1, locals=1, args_size=1
             0: aload_0       
             1: invokevirtual #3                  // Method someMethod:()Ljava/lang/String;
             4: areturn       
          LineNumberTable:
            line 3: 0
          LocalVariableTable:
            Start  Length  Slot  Name   Signature
                   0       5     0  this   Lfindbugs/sample/TestRuntimeExceptionOnImplementingClass;
        Exceptions:
          throws java.lang.RuntimeException
    }

**Comment by mebigfatguy** [comment]
ah, i just have to ignore synthetic methods, ok. thanks for the report.

**Comment by mebigfatguy** [comment]
fixed in commit with hash 0159e4454c8c845a90d611a72ac183c668a93600

thanks again for the report.

**Comment by ThrawnCA** [comment]
Thanks!

By the way, if you put a # before the issue number in your commits, then Github will automatically link them.
