### ISSUE TITLE
Add TestNGAssertionOddities?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#52]
TestNG tests work similarly in most respects to JUnit tests, and have most of the same considerations, they just have slightly different annotations and assertion styles.

- No base class or naming convention for tests
- Test annotation is org.testng.annotation.Test
- Assertions come from org.testng.Assert
- Assertions have different parameter order: "actual, expected, failure message" instead of "failure message, expected, actual"

Is it worth copying (or expanding) JUnitAssertionOddities to include it?

**Comment by mebigfatguy** [comment]
yeah, probably would be. should be pretty trivial to expand JUnitAssertionOddities to include it. I'll see what i can do.

**Comment by mebigfatguy** [comment]
implemented

**Comment by ThrawnCA** [comment]
Looking pretty good :). I neglected to mention that TestNG also has an AssertJUnit class, with assertion parameters in the same order as JUnit (expected first).

On the other hand, I tend to add Checkstyle rules to forbid anyone from using this class, because it usually signifies that their IDE picked the wrong import to autocomplete. So I personally don't care if it's not included.

Now I just have to go fix our TestNG tests. Several of them rely on throwing exceptions; pretty simple fix, just call 'fail' after the method call that should throw the exception and give a nice failure message.
