### ISSUE TITLE
Add bug detector for non-static constants?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#53]
It might be valuable to add a performance-related bug detector for known-immutable classes being initialized from literal/constant parameters in a non-static context. A classic example is compiling a Pattern from a literal string; it is costly and will always produce the same output, so it should be done statically and saved in a constant.

Numbers probably should *not* be included, since they already have an efficient ``valueOf`` mechanism.

Guava's immutable collection/map builders might also be a candidate, when their parameters are all literals, along with most of the Joda Time classes (except the constructors that use the current time).

This might, of course, have false positives on unit tests, which could initialize an object that is only relevant to one test and therefore needed only once. (On the other hand, I tend to disable all performance-related bug detectors on tests anyway; there's not much point in micro-optimizing them.)

**Comment by jsotuyod** [comment]
For the specific case of `Pattern`, my company [has developed a detector in our own plugin](https://github.com/Monits/findbugs-plugin/blob/master/src/main/java/com/monits/findbugs/jdk/NonStaticPatternCompileDetector.java) just a couple weeks ago.

Similar detectors for immutable objects may be interesting, but only when the cost of actually creating such elements is considerable (the JVM is very efficient handling short-lived objects in general, so allocations on their own are probably not enough to justify this)....

Usually immutable objects are fast to build (for instance, `BigDecimal` / `BigInteger` are really fast in general, except maybe when parsing `String`s to create new instances). Also listing such immutable objects may be hard... using jcip's `@Immutable` annotation will help, but not cut it with JDK's classes and methods (`Collections.emptyList()`, `Collections.unmodifiableSet()`, `BigDecimal`, `BigInteger`, etc.) which are not marked that way as immutable.

A blacklist approach for "slow creation of immutable object" seems viable, but hard to scale / mantain, specially when considering third-party libraries.

**Comment by ThrawnCA** [comment]
Hmm...I pretty much agree with the above (numbers aren't worth it, etc). And the point about the Immutable annotation is a good one; anything marked as Immutable should be considered as a candidate.

Does your custom detector take account of whether the pattern is assembled from dynamic data? I was only thinking to apply this in cases where the inputs are literals/constants. For example, I recently set up a Spring controller to restrict redirects to one domain; the domain was injected by Spring, so it was a constructor parameter, but then it was compiled for reuse. The resulting field was final, though, so perhaps your detector would accept it?

**Comment by jsotuyod** [comment]
The detector reports on:
* [string literals](https://github.com/Monits/findbugs-plugin/blob/master/src/test/java/samples/findbugs/jdk/patterncompile/NonStaticPatternCompile.java#L19)
* [final static String variables](https://github.com/Monits/findbugs-plugin/blob/master/src/test/java/samples/findbugs/jdk/patterncompile/NonStaticPatternCompile.java#L30)
* [final local String variables made of literals](https://github.com/Monits/findbugs-plugin/blob/master/src/test/java/samples/findbugs/jdk/patterncompile/NonStaticPatternCompile.java#L43)

It does not report on:
* method arguments ([final](https://github.com/Monits/findbugs-plugin/blob/master/src/test/java/samples/findbugs/jdk/patterncompile/NonStaticPatternCompile.java#L68) or [not](https://github.com/Monits/findbugs-plugin/blob/master/src/test/java/samples/findbugs/jdk/patterncompile/NonStaticPatternCompile.java#L80)).
* [return values from methods](https://github.com/Monits/findbugs-plugin/blob/master/src/test/java/samples/findbugs/jdk/patterncompile/NonStaticPatternCompile.java#L92)
* [non-final local String variable made of literals](https://github.com/Monits/findbugs-plugin/blob/master/src/test/java/samples/findbugs/jdk/patterncompile/NonStaticPatternCompile.java#L57)

**Comment by ThrawnCA** [comment]
What about making use of MutabilityDetector?

https://github.com/MutabilityDetector/MutabilityDetector

**Comment by ThrawnCA** [comment]
Bump.

- Is the detector by @jsotuyod suitable for adding to fb-contrib?
- Is it feasible/desirable to extend this to other immutable classes, using the Immutable annotation and/or the MutabilityDetector library?

**Comment by mebigfatguy** [comment]
seems reasonable. Up to him.

Is there a list of other things besides Pattern that comes to mind?

**Comment by jsotuyod** [comment]
Our plugin is open source, freely available under Apache License, actively mantained, with great code coverage (97%) and Findbugs **does** allow to load several different plugins at once, so people can use `fb-contrib` along our own plugin if they see value to it (we know we do it). We even host it publicly on our own repository (Maven Central is in backlog, but we are not actively pushing for it at the moment).

Therefore, I see no point in dropping it from where it is, to move it to a different project.

You can still freely fork from it given proper credit to it's author, but forking means more maintenance work, and I feel it won't benefit either project.

**Comment by mebigfatguy** [comment]
Makes sense to me. If you want me to link to your repository/plugin on fb-contrib's github readme, let me know.
