### ISSUE TITLE
FalsePositive on AssertionError

### ISSUE THREAD

**Issue by Lonzak** [mebigfatguy/fb-contrib#54]
There seems to be a false positive when creating an AssertionError using fb-contrib (4.6.1?): 

    try {
     //do someting which might throw an exception
    } 
    catch (SomeException se) {
     throw new AssertionError(se);
    }

Findbugs throws: **Correctness - Method throws alternative exception from catch block without history [fb-contrib]** which is not true since the AssertionError sets the cause:

    public AssertionError(Object detailMessage) {
        this("" +  detailMessage);
        if (detailMessage instanceof Throwable)
            initCause((Throwable) detailMessage);
    }

**UPDATE: Fixed in a newer version...**

**Comment by mebigfatguy** [comment]
Thanks for the report. That is indeed an issue. Didn't realize there was an Object parm'ed constructor there. Will fix soon.

**Comment by mebigfatguy** [comment]
Actually after looking at this, it was an issue at one time, but i thought i fixed it, awhile back. I have added a sample test for it here be5267b3acc and I don't see it happening. Does this test report an issue for you?

What version are you using?

**Comment by mebigfatguy** [comment]
and here is where i thought i fixed it, close to 3 years ago.  4f973cfe8df6c70871f17bb9fff990239ad323d4

If you have a found a different case, that would be good to know, but i'm currently not seeing it.

**Comment by Lonzak** [comment]
In our sonar server we use an older version (4.6.1 or something like that) so its probably still in there.
Thanks for the info!
