### ISSUE TITLE
Should WEM apply to static initializers?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#55]
Static initializers have no parameters, and typically no state to log, so should they be an exception to the WEM_WEAK_EXCEPTION_MESSAGING detector? Adding the root cause is about as much information as we can meaningfully give.

For example, we use a static initializer to configure features on a constant javax.xml.parsers.DocumentBuilderFactory. If it fails, all we can really report is a static message and the root cause.

Actually, instance initializers may be in the same position.

**Comment by mebigfatguy** [comment]
seems right

**Comment by ThrawnCA** [comment]
Testing passes for static initializers. Do you think it makes sense to exclude instance initializers too?

**Comment by mebigfatguy** [comment]
you can't differentiate instance initializers from zero arg constructors. One could argue i suppose to ignore zero arg constructors, but i'm not sure that's right.

**Comment by ThrawnCA** [comment]
Huh. From javap output, it looks like the compiler merges instance initializers with the constructor(s). Actually, that's even documented at https://docs.oracle.com/javase/tutorial/java/javaOO/initial.html

Fair enough then. I agree that no-arg constructors should probably be checked (and there shouldn't be too many circumstances where a no-arg constructor does something that might throw an exception anyway).
