### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by jsotuyod** [mebigfatguy/fb-contrib#56]
Is there any release schedule ahead? Over the last couple months there have been several fp / fn fixes to existing detectors that would be quiet interesting to have available on Maven. Are there any plans for a 6.2.2 release?

Or are we looking straight ahead to 6.3.0 with the changes to JAO? (and maybe MRC, not sure if it's ready for prime time yet)

**Comment by mebigfatguy** [comment]
i guess i could cut a 6.2.2 at some point. Maybe this weekend.
