### ISSUE TITLE
IICU_INCORRECT_INTERNAL_CLASS_USE false positive with JavaMail

### ISSUE THREAD

**Issue by jsotuyod** [mebigfatguy/fb-contrib#57]
The current detector reports on `com.sun.xxx`, however, there are libraries fully documented and intended for developer's use under such package.

For instance [JavaMail](https://java.net/projects/javamail/pages/Home) offers a number of APIs under `com.sun.mail`.

I believe these packages should be whitelisted.

**Comment by mebigfatguy** [comment]
I see this from the javadoc

 The JavaMail reference implementation includes protocol providers in subpackages of com.sun.mail. Note that the APIs to these protocol providers are not part of the standard JavaMail API. Portable programs will not use these APIs.

Nonportable programs may use the APIs of the protocol providers by (for example) casting a returned Folder object to a com.sun.mail.imap.IMAPFolder object. Similarly for Store and Message objects returned from the standard JavaMail APIs. 


This is sort of a grey area it would seem.

**Comment by jsotuyod** [comment]
What that's saying is that those methods are not part of the standard `javax.mail`, but the reference implementation itself is open-source, pure Java, and can be added as a dependency and used safely even outside Oracle's JRE.

The APIs are safe to use, and intended for developer use. The only warning is that replacing that dependency with another `javax.mail` implementation (currently, the only other one is [GNU JavaMail](http://www.gnu.org/software/classpathx/javamail/javamail.html), which is stuck in version 1.3 of the spec) will not work (and hence they are in a separate packge).

[Actually other implementation do the exact same thing](http://www.gnu.org/software/classpathx/javamail/javadoc/overview-summary.html), creating their providers outside `javax.mail` since they are not portable, for instance [GNU JavaMail's IMAPFolder](http://www.gnu.org/software/classpathx/javamail/javadoc/gnu/mail/providers/imap/IMAPFolder.html)

**Comment by mebigfatguy** [comment]
ok thanks

**Comment by ThrawnCA** [comment]
Xws-security also uses com.sun packages
