### ISSUE TITLE
UTAO_JUNIT_ASSERTION_ODDITIES_NO_ASSERT does not handle tests expecting exceptions

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#58]
The documentation for UTAO_JUNIT_ASSERTION_ODDITIES_NO_ASSERT states:

"While a unit test could still be valid if it relies on whether or not an exception is thrown, it is usually a sign of a weak test if there are no assertions."

However, in the case where the unit test is indeed checking whether an exception is thrown, this makes the whole functionality of expecting an exception (which is built into JUnit and TestNG) nearly useless; the programmer must either use a try-catch block in every test, or add a redundant 'fail' instruction at the point where the exception should have been thrown.

Is it feasible for this detector to ignore methods that are specifically annotated to expect an exception?

    @Test(expected = FooException.class)
    public void shouldThrowFooException() {
        ...blah...

**Comment by mebigfatguy** [comment]
yes. i can add that. thanks.
