### ISSUE TITLE
HCP_HTTP_REQUEST_RESOURCES_NOT_FREED_* does not apply to HttpClient 4.4

### ISSUE THREAD

**Issue by kdeenanauth** [mebigfatguy/fb-contrib#59]
FindBugs noticed our usage of HttpClient as per http://fb-contrib.sourceforge.net/bugdescriptions.html#HCP_HTTP_REQUEST_RESOURCES_NOT_FREED_LOCAL . The fix is to call .reset:

``` java
public String requestInfo(URI u) {
    HttpGet httpGet = new HttpGet(u);
    try(CloseableHttpResponse response = client.execute(httpGet);) {
        return getResponseAsString(response);
    }
    catch (IOException e) {
        e.printStackTrace();
    }
    finally {
        httpGet.reset();
    }
    return null;
}
```

I was very surprised to see that this is an issue as it is not documented anywhere on Apache's site. I dug into code for HttpClient 4.4 to investigate. It appears that calling `HttpGet.reset()` (or any of the Http request objects that extend from `AbstractExecutionAwareRequest`) calls `.cancel` on an arbitrary `Cancellable` object held on the request. Throughout the operation of `client.execute` the cancellable is swapped depending on the stage the request might be in (e.g. requesting a connection from the connection pool, consuming the http entity).

Calling `.reset()` prior to `.execute(...)` does nothing because the cancellable would not be set. The call to `.execute(...)` is well encapsulated in a try-catch block to abort the connection if needed:

``` java
try {
...
} catch (final ConnectionShutdownException ex) {
            final InterruptedIOException ioex = new InterruptedIOException(
                    "Connection has been shut down");
            ioex.initCause(ex);
            throw ioex;
        } catch (final HttpException ex) {
            releaseTrigger.abortConnection();
            throw ex;
        } catch (final IOException ex) {
            releaseTrigger.abortConnection();
            throw ex;
        } catch (final RuntimeException ex) {
            releaseTrigger.abortConnection();
            throw ex;
        }
```

The only time calling `.reset()` would be handy is if the http request object is being reused or to cancel the request asynchronously.

Can the documentation for HCP_HTTP_REQUEST_RESOURCES_NOT_FREED_\* be updated to clarify which version(s) of HttpClient this applies to?

I realize a more thorough investigation may be needed for older versions of HttpClient.

**Comment by kjlubick** [comment]
Hello kdeenanauth,
Disclosure: I am the original author of this detector.

From personal experience with HttpClient 4.4, this pattern of resetting
after all gets was needed, even though the HttpGet was not being reused.
Failure to reset the local variable before the method returned would cause
the program to lock up after a few (successful) gets (a few dozen at the
most).

Is the second block of code a suggestion of what an okay fix is?  Or is
that a false positive?


I'll concede that I don't quite remember whether it was 4.4 or 4.3.x,
although I am fairly certain it was 4.4.  I see 4.4.1 has been released
recently, perhaps that fixed this unintended behavior?

**Comment by kdeenanauth** [comment]
I'm surprised this is the behavior you were experiencing. It's possible you were actually failing to consume the entire entity (if you don't use `EntityUtils.consume(...)` under streaming conditions you would fail to close the connection.) Can you reproduce this in a test?

The second block of code is just seen within `MainClientExec` and `MinimalClientExec` which are delegated to execute the request from HttpClient.

**Comment by kjlubick** [comment]
I was unaware EntityUtils.consume was the proper way to do this.  Do you think changing the recommendation/detector to detect failures of this would be the appropriate course of action?

**Comment by mebigfatguy** [comment]
sounds like a good idea

**Comment by kdeenanauth** [comment]
It's possible, but it would need to be a little elaborate. Any code that makes a call to `httpResponseInstance.getEntity()` needs to ensure that it closes the `InputStream`. Some of the methods on `EntityUtils` do this automatically (`EntityUtils.toString`, `EntityUtils.toByteArray` and `EntityUtils.consume`).

It's also possible the user doesn't use any of these methods and uses the `InputStream` directly (see "Ensuring release of system resources" http://hc.apache.org/httpcomponents-core-4.4.x/tutorial/html/fundamentals.html#d5e136).

**Comment by mebigfatguy** [comment]
So what's the verdict here? Should we disable this one till we decide what to do?

**Comment by cogman** [comment]
Can I bring this up again?

It depends a lot on usage when you need to call reset or even entityutils.consume.  Circa 4.2 or 4.3 (I can't remember which) they added a response handler parameter to the execute.   If you use that, the client will automatically consume the entity at the end of the request ( see the documentation here https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/CloseableHttpClient.html#execute(org.apache.http.HttpHost,%20org.apache.http.HttpRequest,%20org.apache.http.client.ResponseHandler) )

**Comment by mebigfatguy** [comment]
alright, i'm going to disable this. i'm happy to re-enable if someone comes up with a patch that resolves these issues.
