### ISSUE TITLE
Dogfooding - pass core FindBugs checks

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#69]
fb-contrib has a pretty good FindBugs result, but still a handful of issues, and some false positives that should be specifically excluded.

I'll send through a pull request for these.

**Comment by mebigfatguy** [comment]
cool

**Comment by ThrawnCA** [comment]
Still one outstanding; I think it might be a false positive, but I'm hesitant to assume I know best?

    <BugInstance rank='13' category='STYLE' instanceHash='bf4a0cb217c0f35e8fcf5e63a9837841' instanceOccurrenceNum='0' priority='2' abbrev='NP' type='NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE' cweid='476' instanceOccurrenceMax='0'>
      <ShortMessage>Possible null pointer dereference due to return value of called method</ShortMessage>
      <LongMessage>Possible null pointer dereference in com.mebigfatguy.fbcontrib.utils.XClassUtils.getXMethod(XClass, String, String) due to return value of called method</LongMessage>
      <Class classname='com.mebigfatguy.fbcontrib.utils.XClassUtils' primary='true'>
        <SourceLine start='31' classname='com.mebigfatguy.fbcontrib.utils.XClassUtils' sourcepath='com/mebigfatguy/fbcontrib/utils/XClassUtils.java' sourcefile='XClassUtils.java' end='103'>
          <Message>At XClassUtils.java:[lines 31-103]</Message>
        </SourceLine>
        <Message>In class com.mebigfatguy.fbcontrib.utils.XClassUtils</Message>
      </Class>
      <Method isStatic='false' classname='com.mebigfatguy.fbcontrib.utils.XClassUtils' name='getXMethod' primary='true' signature='(Ledu/umd/cs/findbugs/ba/XClass;Ljava/lang/String;Ljava/lang/String;)Ledu/umd/cs/findbugs/ba/XMethod;'>
        <SourceLine endBytecode='177' startBytecode='0' start='78' classname='com.mebigfatguy.fbcontrib.utils.XClassUtils' sourcepath='com/mebigfatguy/fbcontrib/utils/XClassUtils.java' sourcefile='XClassUtils.java' end='87' />
        <Message>In method com.mebigfatguy.fbcontrib.utils.XClassUtils.getXMethod(XClass, String, String)</Message>
      </Method>
      <LocalVariable register='-1' name='?' pc='29' role='LOCAL_VARIABLE_UNKNOWN'>
        <Message>Local variable stored in JVM register ?</Message>
      </LocalVariable>
      <SourceLine endBytecode='29' startBytecode='29' start='84' classname='com.mebigfatguy.fbcontrib.utils.XClassUtils' primary='true' sourcepath='com/mebigfatguy/fbcontrib/utils/XClassUtils.java' role='SOURCE_LINE_INVOKED' sourcefile='XClassUtils.java' end='84'>
        <Message>Method invoked at XClassUtils.java:[line 84]</Message>
      </SourceLine>
      <SourceLine endBytecode='24' startBytecode='24' start='84' classname='com.mebigfatguy.fbcontrib.utils.XClassUtils' sourcepath='com/mebigfatguy/fbcontrib/utils/XClassUtils.java' role='SOURCE_LINE_KNOWN_NULL' sourcefile='XClassUtils.java' end='84'>
        <Message>Known null at XClassUtils.java:[line 84]</Message>
      </SourceLine>
    </BugInstance>

The relevant code looks null-proof to me:

    public XMethod getXMethod(final XClass xClass, final String methodName, final String methodSig) {
        if (xClass == null) {
            return null;
        }

        XMethod xMethod = xClass.findMethod(methodName, methodSig, false);
        if (xMethod == null) {
    // we know xClass isn't null, so why does FindBugs complain about this line?
    ***        final XClass superClass = getXClass(xClass.getSuperclassDescriptor());
            xMethod = getXMethod(superClass, methodName, methodSig);
        }
        return xMethod;
    }

**Comment by ThrawnCA** [comment]
Bump.

The outstanding issue looks like a false positive to me, but I don't understand why it's firing at all, so I don't want to assume that. Any insights?

**Comment by mebigfatguy** [comment]
I'm assuming it's because

xClass.getSuperclassDescriptor()

has a @CheckForNull on it,

and somewhere down in the bowels of getXClass it assumes the descriptor isn't null.

**Comment by ThrawnCA** [comment]
You're right, that resolves it. FindBugs is usually right about these things...

I'm opening another pull request to enforce FindBugs checks in the Maven build; not sure how you feel about merging it. Up to you.
