### ISSUE TITLE
OCP_OVERLY_CONCRETE_PARAMETER complains when implementing parameterised interface

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#72]
I've written a JPA ``AttributeConverter`` for converting Joda ``DateTime`` instances to/from ``java.sql.Timestamp`` instances, but since I only need the millisecond value to convert them, the OCP_OVERLY_CONCRETE_PARAMETER detector claims that I could change a method parameter to type ``ReadableInstant`` instead of ``DateTime``.

I don't want to do this, because I want the return type from converting a ``Timestamp`` to be of type ``DateTime``, so to implement the interface properly, I need to use the concrete type.

Is there a better way to do this?

    package findbugs.sample;

    import java.sql.Timestamp;
    import javax.persistence.AttributeConverter;
    import javax.persistence.Converter;

    import org.joda.time.DateTime;
    import org.joda.time.DateTimeZone;

    @Converter(autoApply = true)
    public class DateTimeConverter implements AttributeConverter<DateTime, Timestamp> {

        @Override
        public Timestamp convertToDatabaseColumn(DateTime attribute) {
            if (attribute == null) {
                return null;
            }
            return new Timestamp(attribute.getMillis());
        }

        @Override
        public DateTime convertToEntityAttribute(Timestamp dbData) {
            if (dbData == null) {
                return null;
            }
            return new DateTime(dbData.getTime(), DateTimeZone.UTC);
        }

    }

**Comment by mebigfatguy** [comment]
I suppose I could skip classes with @Converter annotations. And perhaps other similar annotations whatever they might be.

-------- Original message --------

**Comment by ThrawnCA** [comment]
That could work, but the annotation isn't actually mandatory; it's possible to configure attribute converters in XML instead.

I suppose, due to type erasure, it's not possible to detect the fact that the types on the two methods are linked by the interface?

**Comment by ThrawnCA** [comment]
Workaround: I defined two methods, with the two different signatures, and delegated from one to the other.

    @Override
    public Timestamp convertToDatabaseColumn(DateTime attribute) {
        return convertInstantToDatabaseColumn(attribute);
    }

    public Timestamp convertInstantToDatabaseColumn(ReadableInstant attribute) {
        if (attribute == null) {
            return null;
        }
        return new Timestamp(attribute.getMillis());
    }

**Comment by ThrawnCA** [comment]
There is one clue that could identify the fact that this is a parameterised interface: the synthetic methods generated in the class to satisfy the interface.

      public java.lang.Object convertToEntityAttribute(java.lang.Object);
        flags: ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
        Code:
          stack=2, locals=2, args_size=2
             0: aload_0       
             1: aload_1       
             2: checkcast     #3                  // class java/sql/Timestamp
             5: invokevirtual #12                 // Method convertToEntityAttribute:(Ljava/sql/Timestamp;)Lorg/joda/time/DateTime;
             8: areturn       
          LineNumberTable:
            line 11: 0
          LocalVariableTable:
            Start  Length  Slot  Name   Signature
                   0       9     0  this   Lau/gov/qld/ssq/cofa/domain/jpa/DateTimeConverter;

      public java.lang.Object convertToDatabaseColumn(java.lang.Object);
        flags: ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
        Code:
          stack=2, locals=2, args_size=2
             0: aload_0       
             1: aload_1       
             2: checkcast     #6                  // class org/joda/time/DateTime
             5: invokevirtual #13                 // Method convertToDatabaseColumn:(Lorg/joda/time/DateTime;)Ljava/sql/Timestamp;
             8: areturn       
          LineNumberTable:
            line 11: 0
          LocalVariableTable:
            Start  Length  Slot  Name   Signature
                   0       9     0  this   Lau/gov/qld/ssq/cofa/domain/jpa/DateTimeConverter;

**Comment by ThrawnCA** [comment]
0aee9e2ab3acba32787ac3288d5f880fd5417b8a fixed it, thanks :)
