### ISSUE TITLE
False positive on IMC_IMMATURE_CLASS_NO_EQUALS

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#73]
The following class incorrectly triggers IMC_IMMATURE_CLASS_NO_EQUALS with the latest trunk version of fb-contrib (dc8d0867bee07371195a1884c35cf664b6797bef), and I can't work out why:

    package findbugs.sample;

    import org.apache.commons.lang3.builder.*;

    public class DomainObject {

        private String field;

        public DomainObject(String field) {
            this.field = field;
        }

        public String getField() {
            return field;
        }

        public void setField(String field) {
            this.field = field;
        }

        @Override
        public boolean equals(Object o) {
            return EqualsBuilder.reflectionEquals(this, o);
        }

        @Override
        public int hashCode() {
            return HashCodeBuilder.reflectionHashCode(this);
        }

        @Override
        public String toString() {
            return String.format("DomainObject{ field=%s }", field);
        }
    }

**Comment by mebigfatguy** [comment]
thanks! stupid i didn't see this already... great to have a more eyes on it.
