### ISSUE TITLE
FP on FCBL field could be local

### ISSUE THREAD

**Issue by DTecheira** [mebigfatguy/fb-contrib#74]
Given the following Android code:

```
public class MultiStateButton extends LinearLayout {
	private final int normalStateBackgroundResource;

	public MultiStateButton(final Context context, final AttributeSet attrs, final int defStyleAttr) {
		super(context, attrs, defStyleAttr);

		final TypedArray attr = context.obtainStyledAttributes(attrs, R.styleable.MultiStateButton, defStyleAttr, 0);
		normalStateBackgroundResource = attr.getResourceId(R.styleable.MultiStateButton_normalStateBackground, 0);
		attr.recycle();
	}

	public void showAsNormal() {
		setBackgroundResource(normalStateBackgroundResource);
	}
}
```

`normalStateBackgroundResource` gets flagged as could be local. But in truth it can't. It's a value obtained at one point in the lifecycle, and used at another, therefore needing to be stored as internal state (and since it won't change, properly flagged as `final`).

The only alternative would be to keep the `TypedArray` or `AttributeSet` instead of the single int. This is not viable. Those objects wrap around a STAX parser you don't want to keep around in memory at all, and even without the memory concerns, the performance of parsing the XML each time should be enough to prefer keeping the single cached int value.

I believe the detector currently just checks on how many different places the variable is read, but I believe it should also check if it's being written from somewhere else and the value being written depends somehow on that method's parameters (I understand his may be hard, since such dependency may be direct or indirect).

**Comment by mebigfatguy** [comment]
thanks for the report.

you are right that FCBL can have some tricky false positives, but your sample should not be one of them. Clearly on the surface your code is fine, and so either something tricky is going on, like synthetic methods or such, or I'm an idiot... either being equally likely. Let me see what's up.

**Comment by mebigfatguy** [comment]
Would it be possible to send me the .class file for this class?

**Comment by DTecheira** [comment]
This is really weird, I went back to check this today without changing anything to my code, I re-run the checks and the error no longer shows.
Maybe was something on my side. Sorry for the troubles.
