### ISSUE TITLE
LO_APPENDED_STRING_IN_FORMAT_STRING does not check whether message is reused

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#75]
The LO_APPENDED_STRING_IN_FORMAT_STRING detector is flagging a situation where a message is generated through string appending, used as an email body, and logged via SLF4J.

Since the concatenated string is in fact always needed, the detector should ignore this case.

Code looks like:

    public void sendRecipientNotification(Recipient recipient, int changeCount) {
        SimpleMailMessage msg = new SimpleMailMessage();
        msg.setTo(recipient.getEmail());
        String subject;
        if (changeCount == 0) {
            subject = "There are no requests for " + recipient;
        } else {
            subject = recipient + " has new requests";
        }
        msg.setSubject(subject);

        try {
            LOG.trace(subject);
            sender.send(msg);
        } catch (MailException e) {
            LOG.error("Could not send notification email to recipient", e);
        }
    }

**Comment by mebigfatguy** [comment]
Ok, makes sense. I guess if the string is also used for something else....ignore

**Comment by mebigfatguy** [comment]
Thanks, see if that resolves your issue.

**Comment by ThrawnCA** [comment]
Yep, warning is gone :).

Any idea how soon until a new release? We still have code sitting on 6.2.1 due to #58
