### ISSUE TITLE
False Positive on FCBL field could be local

### ISSUE THREAD

**Issue by jcnoriega** [mebigfatguy/fb-contrib#76]
Hi there! :)
Here is a simplified version of an adapter I'm implementing in my Android project:
[MyAdapter.class](https://github.com/mebigfatguy/fb-contrib/files/45194/MyAdapter.txt)
```
public class MyAdapter {

	private final CallbackManager callbackManager;
	private final Fragment fragment;

	public MyAdapter(final Fragment fragment, final CallbackManager callbackManager) {
		this.fragment = fragment;
		this.callbackManager = callbackManager;
	}

	public View getView(final ViewGroup parent) {
		final View view;
		final ViewHolder holder;
		final LayoutInflater inflater = LayoutInflater.from(fragment.getActivity());
		view = inflater.inflate(R.layout.campaign_list_element, parent, false);
		holder = new ViewHolder();
		holder.buttonShare = (ImageButton) view.findViewById(R.id.share_button);

		holder.buttonShare.setOnClickListener(new CampaignShareListener(fragment, null, callbackManager));

		return null;
	}

	private static class ViewHolder {
		public ImageButton buttonShare;
	}
}
```
As you can see, `CallbackManager` can not be a local variable, yet findbugs reports it as such. Help :(

Thanks!!

**Comment by mebigfatguy** [comment]
Thanks for the report. Hmm yup... seems pretty stupid on my part. will fix shortly.

**Comment by mebigfatguy** [comment]
Hmm. I've tried to reproduce, but am unable to do so. I had to stub in various crap, but that shouldn't effect things
[MyAdapter.java.txt](https://github.com/mebigfatguy/fb-contrib/files/45209/MyAdapter.java.txt)

Would it be possible to email me the .class file for MyAdapter.class ?

**Comment by jcnoriega** [comment]
Sent! :)

**Comment by mebigfatguy** [comment]
thanks. and what version of fb-contrib are you using?

**Comment by jcnoriega** [comment]
at the moment, 6.2.3

**Comment by ThrawnCA** [comment]
Did you compile with debugging info enabled?

**Comment by mebigfatguy** [comment]
I am unable to reproduce.

**Comment by jcnoriega** [comment]
Thats wierd, I tried to narrow it down as much as I could. It only happens
in this class, across the app works just fine. If I come across it again, I
'll try to provide you with more information. Thank you very much! Cheers!

**Comment by mebigfatguy** [comment]
ok. sorry, if you can get a version that reproduces, please reopen.
