### ISSUE TITLE
Need to specify encoding when invoking javac tasks in Ant build file

### ISSUE THREAD

**Issue by richardfearn** [mebigfatguy/fb-contrib#78]
In 6.4.0, one of the fb-contrib source files is now UTF-8, due to commit 302fb9023665b7a4e6426ba65a6a2bbbe4ead96f.

The Fedora package for 6.4.0 [failed to build](https://kojipkgs.fedoraproject.org//work/tasks/1609/12011609/build.log) due to this:

    compile:
        [javac] Compiling 153 source files to /builddir/build/BUILD/findbugs-contrib-6.4.0/target/classes/main
        [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
        [javac] /builddir/build/BUILD/findbugs-contrib-6.4.0/src/com/mebigfatguy/fbcontrib/detect/UnitTestAssertionOddities.java:4: error: unmappable character for encoding ASCII
        [javac]  * Copyright (C) 2015 - Juan Mart??n Sotuyo Dodero
        [javac]                                  ^
        [javac] /builddir/build/BUILD/findbugs-contrib-6.4.0/src/com/mebigfatguy/fbcontrib/detect/UnitTestAssertionOddities.java:4: error: unmappable character for encoding ASCII
        [javac]  * Copyright (C) 2015 - Juan Mart??n Sotuyo Dodero
        [javac]                                   ^
        [javac] 2 errors
        [javac] 1 warning
    BUILD FAILED

I added an `ant -diagnostics` call that shows:

    file.encoding : ANSI_X3.4-1968

I don't know why the encoding is `ANSI_X3.4-1968` (otherwise known as ASCII) on that host, but the fb-contrib build depends on the system encoding, and is therefore a bit fragile.

I recommend adding an explicit encoding to the `javac` and `javadoc` task invocations.

**Comment by richardfearn** [comment]
To get the Fedora package to build, I added a `<presetdef>` task for `javac` and `javadoc` to set the encoding for both to UTF-8:

http://pkgs.fedoraproject.org/cgit/findbugs-contrib.git/diff/findbugs-contrib-encoding.patch?id=e586f4410da2943639a5d85371f6597ed44e792b

**Comment by mebigfatguy** [comment]
thanks for the report. that is odd. Hopefully i've updated the file to remove that problem.
