### ISSUE TITLE
False Positive on "Dls dead local store"

### ISSUE THREAD

**Issue by jcnoriega** [mebigfatguy/fb-contrib#79]
Hi Dave! It appears i have a false positive on this warning. In my Android project, I try to make a file where i'm going to store some profile pictures. I'm doing this on a `singleton` service, inside a static method:
```
private static File createCameraImageFile() throws IOException {
		final String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(new Date());
		final String cameraPhotoFileName = String.format("UMW_PROFILE_%1$s.jpeg", timeStamp);
		final File storageDir = Environment.getExternalStoragePublicDirectory(
				Environment.DIRECTORY_PICTURES);
		return new File(storageDir, cameraPhotoFileName);
	}
```
The warning says I have a `dead local store` on `cameraPhotoName`. I tried deleting the variable and just put it directly in the `return`, like this:
```
private static File createCameraImageFile() throws IOException {
		final String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(new Date());
		final File storageDir = Environment.getExternalStoragePublicDirectory(
				Environment.DIRECTORY_PICTURES);
		return new File(storageDir, String.format("UMW_PROFILE_%1$s.jpeg", timeStamp));
```
But it would point out that i have a `dead local store` in `timeStamp`. Its seems that it doesnt like local variables! Thank you very much! Cheers

**Comment by jsotuyod** [comment]
`DLS_DEAD_LOCAL_STORE` is a Findbugs detector, not an fb-contrib detectos. The report should be done to [findbugs itself](https://github.com/findbugsproject/findbugs).
