### ISSUE TITLE
Redundant nullcheck in SillynessPotPourri.checkTrimDupStore

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#85]
``checkTrimDupStore`` performs a nullcheck on ``uv`` twice.

Is this just a mistaken copy-and-paste, or was the second check supposed to be doing something else (eg null-checking ``item``)?

    /**
     * determines whether this operation is storing the result of a trim() call, where the trimmed string was duplicated on the stack. If it was, it clears any
     * trim uservalue that was left behind in the dupped stack object
     */
    private void checkTrimDupStore() {
        if ((stack.getStackDepth() >= 2) && (getPrevOpcode(1) == Constants.DUP)) {
            OpcodeStack.Item item = stack.getStackItem(0);
            SPPUserValue uv = (SPPUserValue) item.getUserValue();
            if ((uv == null) || (uv.getMethod() != SPPMethod.TRIM)) {
                return;
            }

            item = stack.getStackItem(1);
    **** this is redundant **** if ((uv == null) || (uv.getMethod() != SPPMethod.TRIM)) {
                return;
            }

            item.setUserValue(null);
        }
    }

**Comment by mebigfatguy** [comment]
good catch, fixed.

**Comment by ThrawnCA** [comment]
:D I can't claim credit; it tripped ``RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE``

But you're welcome - and thanks for the quick response :).
