### ISSUE TITLE
PRMC false positive on try-finally blocks

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#88]
The PRMC detector fires when there are duplicate method calls inside a ``try`` block and its corresponding ``finally`` block.

Since the nature of ``try`` blocks is that we never know which statements will or won't be called, they probably should only be analysed in isolation (ie redundant method calls within the ``try`` block), not in conjunction with code outside the block.

This applies to many parts of the ``fb-contrib`` codebase itself! However, here is a minimalist sample:

    package findbugs.sample;

    class DuplicateMethodCallInsideFinally {

        public void run() {
            Object foo = new Object();
            try {
                willThrow();
                System.err.println(foo.toString());
            } finally {
                System.out.println(foo.toString());
            }
        }

        void willThrow() {
            throw new RuntimeException("kaboom!");
        }

    }

**Comment by mebigfatguy** [comment]
thanks for the report. damn javac at it again. I'll have to see if there's something that can be done
Notice the opcodes starting at offset 25. If does the out.println as if it's part of the try block.

public void fpWithFinally();
    descriptor: ()V
    flags: ACC_PUBLIC
    Code:
      stack=2, locals=3, args_size=1
         0: new           #39                 // class java/lang/Object
         3: dup
         4: invokespecial #1                  // Method java/lang/Object."<init>":()V
         7: astore_1
         8: aload_0
         9: invokevirtual #40                 // Method willThrow:()V
        12: getstatic     #41                 // Field java/lang/System.err:Ljava/io/PrintStream;
        15: aload_1
        16: invokevirtual #42                 // Method java/lang/Object.toString:()Ljava/lang/String;
        19: invokevirtual #43                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
        22: getstatic     #14                 // Field java/lang/System.out:Ljava/io/PrintStream;
        25: aload_1
        26: invokevirtual #42                 // Method java/lang/Object.toString:()Ljava/lang/String;
        29: invokevirtual #43                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
        32: goto          48
        35: astore_2
        36: getstatic     #14                 // Field java/lang/System.out:Ljava/io/PrintStream;
        39: aload_1
        40: invokevirtual #42                 // Method java/lang/Object.toString:()Ljava/lang/String;
        43: invokevirtual #43                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
        46: aload_2
        47: athrow
        48: return

**Comment by mebigfatguy** [comment]
ahh! found the solution

      Exception table:
         from    to  target type
             8    22    35   any

note the ENDPC(to)=22 address is actually way before the HANDLERPC(finally block)=35.

javac on crack, but ok, play along.

**Comment by ThrawnCA** [comment]
Progress, but there are still a bunch of hits within the fb-contrib codebase, eg;

``JDBCVendorReliance.sawOpcode``, line 158
``MethodReturnsConstant.sawOpcode``, line 205
And in a fine twist of irony, the detector itself!
``PossiblyRedundantMethodCalls.sawOpcode`` line 379

As well as a different false positive when ``indexOf`` is called a second time on a String variable *after it has been reassigned*, in ``LoggerOddities.visitClassContext`` (line 112)

**Comment by mebigfatguy** [comment]
![prmc_1_6_2016](https://cloud.githubusercontent.com/assets/170161/12108169/7ddcc3be-b342-11e5-9d83-f49edaad60d0.png)

odd i don't seem them here

**Comment by ThrawnCA** [comment]
My mistake; I was still scanning fb-contrib using fb-contrib 6.4.3 :o
