### ISSUE TITLE
FCBL false positives on field being modified from multiple methods

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#89]
``FCBL_FIELD_COULD_BE_LOCAL`` is firing on several fb-contrib detectors that maintain state in instance fields. I'm not entirely clear on why; perhaps it's unable to trace the method calls and recognise that calling ``super.visitCode`` will result in a call to ``seenOpcode``?

Sample instances:
``SuspiciousComparatorReturnValues`` lines 109-112 (``seenNegative``, ``seenPositive``, ``seenZero``, ``seenUnconditionalNonZero``)
``MethodReturnsConstant`` line 92 (``returnPC``)
``UnitTestAssertionOddities`` line 159 (``sawAssert``)

Actually, the ``MethodReturnsConstant`` instance does look like a genuine hit, because there doesn't seem to be any other method that alters ``returnPC``.

**Comment by mebigfatguy** [comment]
Yeah these are real FPs, and are hard to detect. altho MRC just looks like a bug

**Comment by mebigfatguy** [comment]
MRC bug (not the FCBL bug) is fixed

**Comment by mebigfatguy** [comment]
it appears the FCBL at least wrt findbugs have been fixed. so closing

**Comment by ThrawnCA** [comment]
Er...I wish it were so, but actually I just annotated the methods to ignore the bug pattern. Commit 7a92c18bfe39b207dc839f2f68a13cf53d97ed4c / issue #86

**Comment by ThrawnCA** [comment]
``FieldCouldBeLocal.checkBlock`` (line 257) only tries to remove the field from the list of localizable fields when it is read, not written.

The false positives appear to be occurring when multiple methods write to a field, but only one method reads it.

**Comment by ThrawnCA** [comment]
While editing the FCBL class: the early return on lines 260-262 isn't really needed (other parts of the logic don't bother), and the ``size() > 0`` check on line 123 should be replaced with ``!isEmpty()``.

**Comment by mebigfatguy** [comment]
yeah, i have to perform a closure operation on all methods of the class at once. Just got to rev up the energy to pull that detector apart an redo. :)

**Comment by mebigfatguy** [comment]
Was to difficult a fix, so took the easy way out. There may still be more FPs here, but the super.xxx() problem should be fixed.

**Comment by ThrawnCA** [comment]
Shame about the difficulty, but thanks for fixing the false positives anyway. Maybe someday you'll have a fit of inspiration and come up with a comprehensive algorithm :).
