### ISSUE TITLE
Bogus Exception should handle all methods, not only private/static/etc

### ISSUE THREAD

**Issue by krzyk** [mebigfatguy/fb-contrib#92]
Current javadoc for Bogus Exception says:
> looks for constructors, private methods or static methods

But it should handle all methods, especially public ones (those are the ones that cause the most trouble for the library users).

I'm trying this rule on following class:
```
package test;
class Main {
    public void foo() throws InterruptedException {
        System.out.println("test");
    }
}
```
For the above class (and even when I change method to `private`) this bug is not reported.

**Comment by mebigfatguy** [comment]
The problem with public methods is that derived methods may actually throw that InterruptedException.

**Comment by krzyk** [comment]
@mebigfatguy Yes, but those deived methods can declare this, the ones lower in the inheritance tree shouldn't

**Comment by krzyk** [comment]
@mebigfatguy and also overriden methods can reduce number of exceptions thrown, if you are talking about such case

**Comment by mebigfatguy** [comment]
So lets suppose i have

    public class Parent {
        public foo() throws IOException {
        }
    }

    public class Child {
        public foo() throws IOException {
              try (FileInputStream = new FileInputStream("/somefile")) {
              }
        }
    }

i can't report on Parent.foo, because Child.foo needs Parent to declare it. But i may not even see Child, as Parent might be some api class, that some other code is expected to derive from.

**Comment by krzyk** [comment]
@mebigfatguy OK, I see your point.
What about the problem with this detector not working for private methods also? I tried it on:
```
package test;
class Main {
    private void foo() throws InterruptedException {
        System.out.println("test");
    }
}
```

and also on (I saw that it handles final methods/classes also):
```
package test;
final class Main {
    private void foo() throws InterruptedException {
        System.out.println("test");
    }
}
```

I tried also `static` method, but it doesn't report any problem with those also.

**Comment by mebigfatguy** [comment]
If that is the case then likely a bug on my.part. i'll take a look.

**Comment by mebigfatguy** [comment]
Thanks for the report. seems like a foolish mistake on my part, or a failed attempt to guard against a confusing class file... I probably was just wrong, here. Had to do with when a method called methods that had no exception tables attached to them at all (as opposed to zero length array for 'ET'. But will play with it as is to see if something spurious shows up. Anyway fixed, and should produce a bunch more issues.

**Comment by krzyk** [comment]
@mebigfatguy do you plan to release new version soon?

**Comment by mebigfatguy** [comment]
I've got a bunch of issues i'd like to clean up, first. But hopefully soon.
