### ISSUE TITLE
STT_TOSTRING_STORED_IN_FIELD trips on result of String concatenation

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#93]
The STT_TOSTRING_STORED_IN_FIELD detector fires when a String is assembled via String concatenation (which creates StringBuilders behind the scenes).

Sample class:

```
public class StoreConcatenatedString {

    private String message;

    public StoreConcatenatedString(int value) {
        message = "Value was: " + value;
    }

    public String getMessage() {
        return message;
    }

}
```

**Comment by ThrawnCA** [comment]
Also, the detector should not object to storing the String value of ``java.util.UUID``.

**Comment by mebigfatguy** [comment]
If these are false positives, i'll live with them. I realize that examples are often quite fabricated in nature, but really te first one seems suspect to me. Likely, you'd want that 18n'ed so that would be wrong on that count, but even so, I'd rather the appending be done at the very last second possible (in getMessage).

As for the UUID, splitting hairs i suppose, but i'd rather people store the field as a UUID.

**Comment by ThrawnCA** [comment]
The actual case for the first scenario was setting a status message in an object that would become a Freemarker template's data model. Doing the String formatting at the point of rendering isn't really feasible, since the status message is a generic field that can contain whatever message the application specifies, and Freemarker isn't really designed for string interpolation.

Performance is not a concern in this context, so if ``String.format`` will make the problem go away, it's probably a suitable approach.

As for UUID, we use it to generate random IDs within Hibernate domain objects (not the actual ``@Id`` field). We don't care about them as UUIDs after creation, so it's not really worth having a type converter, and ``toString`` looks like the official method for obtaining the value.

**Comment by ThrawnCA** [comment]
Bump.

Can this be ignored for ``java.util.UUID``, since ``toString`` appears to be the canonical way of retrieving the value (https://docs.oracle.com/javase/7/docs/api/java/util/UUID.html)?

**Comment by ThrawnCA** [comment]
Bump.

What about the possibility of ignoring this rule when the field is annotated as a JPA column?

**Comment by mebigfatguy** [comment]
wouldn't you normally have @Converter s on them?

**Comment by ThrawnCA** [comment]
We *could* use a `Converter`, but as previously mentioned, often we really don't care about the value after creation - we just use `java.util.UUID` as a way of generating the ID - so constantly converting between String and UUID would be wasted effort for us.
