### ISSUE TITLE
UTAO_TESTNG_ASSERTION_ODDITIES_USE_ASSERT_NOT_NULL can't tell when annotated fields are externally populated

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#94]
We use Mockito to automagically populate annotated fields with mock objects for testing, but fb-contrib can't tell that these fields are ever assigned, and if we use them in equality assertions, it fires UTAO_TESTNG_ASSERTION_ODDITIES_USE_ASSERT_NOT_NULL

    import org.mockito.Mock;
    import org.mockito.MockitoAnnotations;
    import org.testng.annotations.BeforeMethod;
    import org.testng.annotations.Test;

    import static org.mockito.Mockito.*;
    import static org.testng.Assert.*;

    public class EqualMockTest {

        private Object realObject;

        @Mock private Object mockObject;

        @BeforeMethod
        public void setUp() throws Exception {
            MockitoAnnotations.initMocks(this);

            realObject = new Object();
        }

        @Test
        public void shouldNotEqualMockObject() {
            assertNotEquals(realObject, mockObject);
        }

    }

**Comment by mebigfatguy** [comment]
Thanks, good issue... i believe it should be fixed now.
