### ISSUE TITLE
Best way to do concatenation of single character with integer?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#97]
The ``PoorlyDefinedParameter`` detector does String concatenation to surround an int with brackets. Since brackets are single characters, UCPM_USE_CHARACTER_PARAMETERIZED_METHOD doesn't like this, saying that it should ``char`` instead of String; however, if we do that, then we will get  addition instead of concatenation.

``String.format`` would resolve this, but with slower performance. Manually creating the implicit ``StringBuilder`` would also work, but seems verbose for such a simple operation.

Is it feasible for UCPM_USE_CHARACTER_PARAMETERIZED_METHOD to recognise this situation (1-character String + numeric type) where we must use the String type in order to get String concatenation?

**Comment by mebigfatguy** [comment]
Thanks, good issue.

I just ruled out inline appending so "foo" + 3 + ")" won't report either, but i can live with that.
