### ISSUE TITLE
Compiling samples?

### ISSUE THREAD

**Issue by ThrawnCA** [mebigfatguy/fb-contrib#99]
The Ant build compiles the sample code, while the Maven build does not. However, as far as I can tell, there are no automated tests that actually use the sample code.

Are the sample classes used just for manual testing?

I would like to enhance the POM to compile the sample classes, but first need to clarify their use case. Should the build compile them after creating the JAR file, as a sanity check? Compile them only on demand, in a separate build profile? Should there be unit tests for them?

**Comment by mebigfatguy** [comment]
I do everything manually with sample classes so I can debug easily using the Gui tool. If you want to add them to the POM build that is fine

**Comment by ThrawnCA** [comment]
OK.

The pull request puts the sample classes in the ``test`` scope, so it's possible to view them in the FindBugs GUI if you want.

**Comment by mebigfatguy** [comment]
thanks... nice, merged
